### ISSUE TITLE
org.apache.commons.lang.exception.NestableRuntimeException: find table xxx error

### ISSUE THREAD

**Issue by bryant-ba** [alibaba/otter#1007]
被拉取的数据库中有对应表报错：
pid:142 nid:44 exception:setl:com.google.common.collect.ComputationException: org.apache.commons.lang.exception.NestableRuntimeException: find table [xxxx] error
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:111)
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:115)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:115)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:50)
at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: find table [copm_baddebt.tb_uhome_acct_item_owes_bad_34] error
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:199)
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:183)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
... 14 more
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: no found table [copm_baddebt.tb_uhome_acct_item_owes_bad_34] , pls check
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:193)
... 16 more

**Comment by lee-cq** [comment]
使用的是哪一个版版本呢？
