### ISSUE TITLE
:canal:canal-dev02:java.lang.IllegalArgumentException: Invalid charset id: 255

### ISSUE THREAD

**Issue by ahJames** [alibaba/otter#1046]
canal-dev02是我配的
![image](https://user-images.githubusercontent.com/41892722/154923350-11cd40a4-9f68-45b0-831a-3b8e526cb05f.png)

管道日志
pid:4 nid:1 exception:canal:canal-dev02:java.lang.IllegalArgumentException: Invalid charset id: 255
at com.taobao.tddl.dbsync.binlog.CharsetConversion.getEntry(CharsetConversion.java:41)
at com.taobao.tddl.dbsync.binlog.CharsetConversion.getJavaCharset(CharsetConversion.java:299)
at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.(QueryLogEvent.java:503)
at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:162)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
at java.lang.Thread.run(Thread.java:748)

**Comment by ahJames** [comment]
pull 镜像千万别用lastest

**Comment by wslyyy** [comment]
遇到了同样的问题，得用哪个版本？

**Comment by liangyaoren** [comment]
遇到了同样的问题，用 v4.2.18 就没问题
