### ISSUE TITLE
connect /192.168.14.88:3306 failure

### ISSUE THREAD

**Issue by hope-courage** [alibaba/otter#1069]
pid:5 nid:1 exception:canal:test_to_me:com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /192.168.11.87:3306 failure
Caused by: java.io.IOException: connect /192.168.14.88:3306 failure
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:183)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'root'@'192.168.12.101' (using password: YES), sqlState=28000, sqlStateMarker=#]
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:271)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80)
    ... 4 more

**Comment by whhe** [comment]
连接失败了，确认下mysql用户名和密码填对了没

**Comment by hope-courage** [comment]
> 连接失败了，确认下mysql用户名和密码填对了没
哈哈，多谢大佬，确实是数据库链接问题，不过用户名、密码都是对的，我把数据库的密码重置之后就好了
