### ISSUE TITLE
LoadException : Unknown Types value

### ISSUE THREAD

**Issue by hope-courage** [alibaba/otter#1072]
pid:12 nid:3 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [update `company_his`.`alltype_1` set `name` = ? , `mobilephone` = ? , `fixedtelephone` = ? , `idnumber` = ? , `email` = ? , `address` = ? , `organization` = ? , `businesslicense` = ? , `taxation` = ? , `unifiedsocialcreditcode` = ? , `passport` = ? , `zipcode` = ? , `commpany` = ? , `bankcard` = ? , `dates` = ? where ( `id` = ? )]; Unknown Types value; nested exception is java.sql.SQLException: Unknown Types value
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:107)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:625)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:617)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:545)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:462)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:275)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown Types value
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3794)
at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:99)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3620)
at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:83)
at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:166)
at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:166)
at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:370)
at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:217)
at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:164)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doPreparedStatement(DbLoadAction.java:810)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.access$800(DbLoadAction.java:517)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2$1.setValues(DbLoadAction.java:628)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:816)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
... 21 more
:-----------------
- PairId: 20 , TableId: 15 , EventType : U , Time : 1656753378000
- Consistency : M , Mode :
-----------------
---Pks
EventColumn[index=0,columnType=4,columnName=id,columnValue=807,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
EventColumn[index=1,columnType=12,columnName=name,columnValue=王二小,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=mobilephone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=fixedtelephone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=idnumber,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=email,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=address,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=organization,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=businesslicense,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=taxation,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=unifiedsocialcreditcode,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=passport,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=zipcode,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=commpany,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=bankcard,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=dates,columnValue=,isNull=false,isKey=false,isUpdate=true]
---Sql
update `company_his`.`alltype_1` set `name` = ? , `mobilephone` = ? , `fixedtelephone` = ? , `idnumber` = ? , `email` = ? , `address` = ? , `organization` = ? , `businesslicense` = ? , `taxation` = ? , `unifiedsocialcreditcode` = ? , `passport` = ? , `zipcode` = ? , `commpany` = ? , `bankcard` = ? , `dates` = ? where ( `id` = ? )

Caused by: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [update `company_his`.`alltype_1` set `name` = ? , `mobilephone` = ? , `fixedtelephone` = ? , `idnumber` = ? , `email` = ? , `address` = ? , `organization` = ? , `businesslicense` = ? , `taxation` = ? , `unifiedsocialcreditcode` = ? , `passport` = ? , `zipcode` = ? , `commpany` = ? , `bankcard` = ? , `dates` = ? where ( `id` = ? )]; Unknown Types value; nested exception is java.sql.SQLException: Unknown Types value
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:107)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:625)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:617)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:545)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:462)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:275)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown Types value
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3794)
at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:99)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3620)
at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:83)
at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:166)
at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:166)
at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:370)
at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:217)
at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:164)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doPreparedStatement(DbLoadAction.java:810)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.access$800(DbLoadAction.java:517)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2$1.setValues(DbLoadAction.java:628)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:816)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
... 21 more
:-----------------
- PairId: 20 , TableId: 15 , EventType : U , Time : 1656753378000
- Consistency : M , Mode :
-----------------
---Pks
EventColumn[index=0,columnType=4,columnName=id,columnValue=807,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
EventColumn[index=1,columnType=12,columnName=name,columnValue=王二小,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=mobilephone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=fixedtelephone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=idnumber,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=email,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=address,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=organization,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=businesslicense,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=taxation,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=unifiedsocialcreditcode,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=passport,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=zipcode,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=commpany,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=bankcard,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=dates,columnValue=,isNull=false,isKey=false,isUpdate=true]
---Sql
update `company_his`.`alltype_1` set `name` = ? , `mobilephone` = ? , `fixedtelephone` = ? , `idnumber` = ? , `email` = ? , `address` = ? , `organization` = ? , `businesslicense` = ? , `taxation` = ? , `unifiedsocialcreditcode` = ? , `passport` = ? , `zipcode` = ? , `commpany` = ? , `bankcard` = ? , `dates` = ? where ( `id` = ? )

at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader.load(DataBatchLoader.java:107)
at com.alibaba.otter.node.etl.load.loader.OtterLoaderFactory.load(OtterLoaderFactory.java:50)
at com.alibaba.otter.node.etl.load.LoadTask$1.run(LoadTask.java:85)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [update `company_his`.`alltype_1` set `name` = ? , `mobilephone` = ? , `fixedtelephone` = ? , `idnumber` = ? , `email` = ? , `address` = ? , `organization` = ? , `businesslicense` = ? , `taxation` = ? , `unifiedsocialcreditcode` = ? , `passport` = ? , `zipcode` = ? , `commpany` = ? , `bankcard` = ? , `dates` = ? where ( `id` = ? )]; Unknown Types value; nested exception is java.sql.SQLException: Unknown Types value
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:107)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:625)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:617)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:545)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:462)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:275)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown Types value
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3794)
at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:99)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3620)
at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:83)
at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:166)
at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:166)
at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:370)
at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:217)
at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:164)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doPreparedStatement(DbLoadAction.java:810)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.access$800(DbLoadAction.java:517)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2$1.setValues(DbLoadAction.java:628)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:816)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
... 21 more
:-----------------
- PairId: 20 , TableId: 15 , EventType : U , Time : 1656753378000
- Consistency : M , Mode :
-----------------
---Pks
EventColumn[index=0,columnType=4,columnName=id,columnValue=807,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
EventColumn[index=1,columnType=12,columnName=name,columnValue=王二小,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=mobilephone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=fixedtelephone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=idnumber,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=email,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=address,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=organization,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=businesslicense,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=taxation,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=unifiedsocialcreditcode,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=passport,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=zipcode,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=commpany,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=bankcard,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=0,columnType=0,columnName=dates,columnValue=,isNull=false,isKey=false,isUpdate=true]
---Sql
update `company_his`.`alltype_1` set `name` = ? , `mobilephone` = ? , `fixedtelephone` = ? , `idnumber` = ? , `email` = ? , `address` = ? , `organization` = ? , `businesslicense` = ? , `taxation` = ? , `unifiedsocialcreditcode` = ? , `passport` = ? , `zipcode` = ? , `commpany` = ?

**Comment by hope-courage** [comment]
请问有没有大佬碰到过这个问题？？
