### ISSUE TITLE
主备配置数据源验证失败

### ISSUE THREAD

**Issue by rsy93** [alibaba/otter#1074]
数据源配置中，单独配置主数据库地址或备份数据库地址都可以验证通过，但是配置jdbc:mysql://groupKey=db后验证失败

db是我在主备配置中的groupkey，jdbc:mysql://groupKey=db之前实验是可以验证通过的，请问可能是哪里的问题

manager日志如下
2022-07-06 16:33:34.301 [/dwr/call/plaincall/Hello.check.dwr] WARN  c.a.o.s.a.i.communication.ArbitrateCommmunicationClient - call manager [10.193.145.33:33330] event [FindMediaEvent[dataId=db-test,type=findMedia]] failed, maybe can try another manager.
2022-07-06 16:33:34.302 [/dwr/call/plaincall/Hello.check.dwr] ERROR c.alibaba.otter.common.push.media.MediaSubscribeManager - call_manager_error
com.alibaba.otter.shared.communication.core.exception.CommunicationException: call[10.193.145.33:33330] , Event[FindMediaEvent[dataId=db-test,type=findMedia]]
Caused by: com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote method: acceptEvent, provider: dubbo://10.193.145.33:33330/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&iothreads=4&lazy=true&payload=8388608&serialization=java&threads=50, cause: client(url: dubbo://10.193.145.33:33330/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&payload=8388608&send.reconnect=true&serialization=java&threads=50) failed to connect to server /10.193.145.33:33330, error message is:connection timed out
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:101) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.common.bytecode.proxy0.acceptEvent(proxy0.java) ~[na:2.5.3]
        at com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationConnection.call(DubboCommunicationConnection.java:45) ~[shared.communication-4.2.18.jar:na]
        at com.alibaba.otter.shared.communication.core.impl.DefaultCommunicationClientImpl.call(DefaultCommunicationClientImpl.java:96) ~[shared.communication-4.2.18.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.communication.ArbitrateCommmunicationClient.callManager(ArbitrateCommmunicationClient.java:74) ~[shared.arbitrate-4.2.18.jar:na]
        at com.alibaba.otter.common.push.media.MediaSubscribeManager$1.apply(MediaSubscribeManager.java:67) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.media.MediaSubscribeManager$1.apply(MediaSubscribeManager.java:61) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.shared.common.utils.cache.RefreshMemoryMirror.get(RefreshMemoryMirror.java:65) [shared.common-4.2.18.jar:na]
        at com.alibaba.otter.common.push.media.MediaSubscribeManager.fetchConfig(MediaSubscribeManager.java:118) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.media.MediaSubscribeManager.fetchConfig(MediaSubscribeManager.java:114) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.supplier.media.MediaDatasourceSupplier.init(MediaDatasourceSupplier.java:102) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.supplier.media.MediaDatasourceSupplier.doStart(MediaDatasourceSupplier.java:87) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.supplier.AbstractDatasourceSupplier.start(AbstractDatasourceSupplier.java:34) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSource.init(MediaPushDataSource.java:100) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler.createDataSource(MediaPushDataSourceHandler.java:106) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler$1$1.apply(MediaPushDataSourceHandler.java:65) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler$1$1.apply(MediaPushDataSourceHandler.java:62) [shared.push-4.2.18.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356) [guava-18.0.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182) [guava-18.0.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151) [guava-18.0.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67) [guava-18.0.jar:na]
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885) [guava-18.0.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler.create(MediaPushDataSourceHandler.java:87) [shared.push-4.2.18.jar:na]
        at com.alibaba.otter.manager.biz.common.DataSourceCreator.preCreate(DataSourceCreator.java:116) [manager.biz-4.2.18.jar:na]
        at com.alibaba.otter.manager.biz.common.DataSourceCreator.createDataSource(DataSourceCreator.java:70) [manager.biz-4.2.18.jar:na]
        at com.alibaba.otter.manager.biz.utils.DataSourceChecker.check(DataSourceChecker.java:146) [manager.biz-4.2.18.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
        at org.directwebremoting.impl.ExecuteAjaxFilter.doFilter(ExecuteAjaxFilter.java:34) [dwr-2.0.10.jar:na]
        at org.directwebremoting.impl.DefaultRemoter$1.doFilter(DefaultRemoter.java:428) [dwr-2.0.10.jar:na]
        at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:431) [dwr-2.0.10.jar:na]
        at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:283) [dwr-2.0.10.jar:na]
        at org.directwebremoting.servlet.PlainCallHandler.handle(PlainCallHandler.java:52) [dwr-2.0.10.jar:na]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:101) [dwr-2.0.10.jar:na]
        at org.directwebremoting.spring.DwrSpringServlet.doPost(DwrSpringServlet.java:158) [dwr-2.0.10.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [javax.servlet-3.0.0.v201112011016.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at com.alibaba.citrus.webx.support.AbstractWebxRootController.giveUpControl(AbstractWebxRootController.java:306) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.support.AbstractWebxRootController.service(AbstractWebxRootController.java:168) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.servlet.WebxFrameworkFilter.doFilter(WebxFrameworkFilter.java:152) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.servlet.FilterBean.doFilter(FilterBean.java:147) [citrus-webx-all-3.2.0.jar:3.2.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at com.alibaba.citrus.webx.servlet.SetLoggingContextFilter.doFilter(SetLoggingContextFilter.java:61) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.servlet.FilterBean.doFilter(FilterBean.java:147) [citrus-webx-all-3.2.0.jar:3.2.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:559) [jetty-security-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.Server.handle(Server.java:365) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856) [jetty-http-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627) [jetty-io-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51) [jetty-io-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
Caused by: com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://10.193.145.33:33330/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&payload=8388608&send.reconnect=true&serialization=java&threads=50) failed to connect to server /10.193.145.33:33330, error message is:connection timed out
        at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.AbstractClient.<init>(AbstractClient.java:103) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.netty.NettyClient.<init>(NettyClient.java:61) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.netty.NettyTransporter.connect(NettyTransporter.java:37) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.Transporter$Adpative.connect(Transporter$Adpative.java) ~[na:2.5.3]
        at com.alibaba.dubbo.remoting.Transporters.connect(Transporters.java:67) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchanger.connect(HeaderExchanger.java:37) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.exchange.Exchangers.connect(Exchangers.java:102) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.initClient(LazyConnectExchangeClient.java:79) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.request(LazyConnectExchangeClient.java:104) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96) ~[dubbo-2.5.3.jar:2.5.3]
        ... 72 common frames omitted
Caused by: java.net.ConnectException: connection timed out
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:371) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:283) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) ~[netty-3.2.2.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
        ... 1 common frames omitted
2022-07-06 16:33:34.305 [/dwr/call/plaincall/Hello.check.dwr] ERROR com.alibaba.otter.manager.biz.utils.DataSourceChecker - check error!
com.google.common.collect.ComputationException: java.lang.NullPointerException
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889) ~[guava-18.0.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler.create(MediaPushDataSourceHandler.java:87) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.manager.biz.common.DataSourceCreator.preCreate(DataSourceCreator.java:116) ~[manager.biz-4.2.18.jar:na]
        at com.alibaba.otter.manager.biz.common.DataSourceCreator.createDataSource(DataSourceCreator.java:70) ~[manager.biz-4.2.18.jar:na]
        at com.alibaba.otter.manager.biz.utils.DataSourceChecker.check(DataSourceChecker.java:146) ~[manager.biz-4.2.18.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
        at org.directwebremoting.impl.ExecuteAjaxFilter.doFilter(ExecuteAjaxFilter.java:34) [dwr-2.0.10.jar:na]
        at org.directwebremoting.impl.DefaultRemoter$1.doFilter(DefaultRemoter.java:428) [dwr-2.0.10.jar:na]
        at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:431) [dwr-2.0.10.jar:na]
        at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:283) [dwr-2.0.10.jar:na]
        at org.directwebremoting.servlet.PlainCallHandler.handle(PlainCallHandler.java:52) [dwr-2.0.10.jar:na]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:101) [dwr-2.0.10.jar:na]
        at org.directwebremoting.spring.DwrSpringServlet.doPost(DwrSpringServlet.java:158) [dwr-2.0.10.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [javax.servlet-3.0.0.v201112011016.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at com.alibaba.citrus.webx.support.AbstractWebxRootController.giveUpControl(AbstractWebxRootController.java:306) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.support.AbstractWebxRootController.service(AbstractWebxRootController.java:168) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.servlet.WebxFrameworkFilter.doFilter(WebxFrameworkFilter.java:152) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.servlet.FilterBean.doFilter(FilterBean.java:147) [citrus-webx-all-3.2.0.jar:3.2.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at com.alibaba.citrus.webx.servlet.SetLoggingContextFilter.doFilter(SetLoggingContextFilter.java:61) [citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.webx.servlet.FilterBean.doFilter(FilterBean.java:147) [citrus-webx-all-3.2.0.jar:3.2.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:559) [jetty-security-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.Server.handle(Server.java:365) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856) [jetty-http-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627) [jetty-io-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51) [jetty-io-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
Caused by: java.lang.NullPointerException: null
        at com.alibaba.otter.common.push.supplier.media.MediaDatasourceSupplier.parse(MediaDatasourceSupplier.java:135) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.supplier.media.MediaDatasourceSupplier.init(MediaDatasourceSupplier.java:103) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.supplier.media.MediaDatasourceSupplier.doStart(MediaDatasourceSupplier.java:87) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.supplier.AbstractDatasourceSupplier.start(AbstractDatasourceSupplier.java:34) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSource.init(MediaPushDataSource.java:100) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler.createDataSource(MediaPushDataSourceHandler.java:106) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler$1$1.apply(MediaPushDataSourceHandler.java:65) ~[shared.push-4.2.18.jar:na]
        at com.alibaba.otter.common.push.datasource.media.MediaPushDataSourceHandler$1$1.apply(MediaPushDataSourceHandler.java:62) ~[shared.push-4.2.18.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356) ~[guava-18.0.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182) ~[guava-18.0.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151) ~[guava-18.0.jar:na]
        at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67) ~[guava-18.0.jar:na]
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885) ~[guava-18.0.jar:na]
        ... 49 common frames omitted

**Comment by aaaxian** [comment]
> 找到问题了，manager中otter.domainName配置的ip无法访问本机的端口导致的，将ip换了就行了

什么意思
