### ISSUE TITLE
pipeline错误

### ISSUE THREAD

**Issue by szlaigithub** [alibaba/otter#125]
2016-03-24 16:51:41.726 [pipelineId = 1,taskName = ProcessTermin] ERROR com.alibaba.otter.node.etl.select.SelectTask - [1] ProcessTermin is error!
org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /otter/canal/destinations/gdcanal/1/mark
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47) ~[zkclient-0.1.jar:na]
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685) ~[zkclient-0.1.jar:na]
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:413) ~[zkclient-0.1.jar:na]
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:409) ~[zkclient-0.1.jar:na]
	at com.alibaba.otter.canal.meta.ZooKeeperMetaManager.clearAllBatchs(ZooKeeperMetaManager.java:231) ~[canal.meta-1.0.20.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.rollback(CanalServerWithEmbedded.java:388) ~[canal.server-1.0.20.jar:na]
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.rollback(CanalEmbedSelector.java:292) ~[node.etl-4.2.12.jar:na]
	at com.alibaba.otter.node.etl.select.SelectTask$3.run(SelectTask.java:380) ~[node.etl-4.2.12.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.6.0_38]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.6.0_38]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) ~[na:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.6.0_38]
	at java.lang.Thread.run(Thread.java:701) ~[na:1.6.0_38]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /otter/canal/destinations/gdcanal/1/mark
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1468) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1496) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at com.alibaba.otter.canal.common.zookeeper.ZooKeeperx.getChildren(ZooKeeperx.java:107) ~[canal.common-1.0.20.jar:na]
	at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:416) ~[zkclient-0.1.jar:na]
	at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:413) ~[zkclient-0.1.jar:na]
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675) ~[zkclient-0.1.jar:na]
	... 12 common frames omitted
版主，上面是日志；otter小白一枚，这个报错没有思路；求版主给个思路。

**Comment by agapple** [comment]
可以做下重试后即可恢复，比如停用启用
