### ISSUE TITLE
otter 查看node500

### ISSUE THREAD

**Issue by szlaigithub** [alibaba/otter#129]
HTTP ERROR 500

Problem accessing /node_info.htm. Reason:

    Failed to invoke Valve[#2/3, level 3]: com.alibaba.citrus.turbine.pipeline.valve.PerformTemplateScreenValve#73c71319:PerformTemplateScreenValve

Caused by: com.google.common.collect.ComputationException: com.alibaba.otter.manager.biz.common.exceptions.ManagerException: java.rmi.NoSuchObjectException: no such object in table
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
	at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
	at com.alibaba.otter.manager.biz.remote.impl.NodeMBeanServiceImpl.getAttribute(NodeMBeanServiceImpl.java:201)
	... 60 more

您好，大拿；otter添加本地的node和异地的node  状态都显示正常，但是点击查看的时候 ，远端。node信息显示如上：大拿，请问这个如何解决？

**Comment by agapple** [comment]
看下causedby，也多搜索下历史issue

**Comment by szlaigithub** [comment]
好的大拿，这个解决了
