### ISSUE TITLE
PipeException: deserial_error

### ISSUE THREAD

**Issue by ghqaz3633** [alibaba/otter#142]
pid:39 nid:18 exception:setl:com.alibaba.otter.node.etl.common.pipe.exception.PipeException: deserial_error
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large. May be malicious. Use CodedInputStream.setSizeLimit() to increase the size limit.
at com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:89)
at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:720)
at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:99)
at com.alibaba.otter.node.etl.model.protobuf.BatchProto$RowData$Builder.mergeFrom(BatchProto.java:2959)
at com.alibaba.otter.node.etl.model.protobuf.BatchProto$RowData$Builder.mergeFrom(BatchProto.java:2605)
at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:275)
at com.alibaba.otter.node.etl.model.protobuf.BatchProto$RowBatch$Builder.mergeFrom(BatchProto.java:863)
at com.alibaba.otter.node.etl.model.protobuf.BatchProto$RowBatch$Builder.mergeFrom(BatchProto.java:675)
at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:300)
at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:238)
at com.google.protobuf.AbstractMessageLite$Builder.mergeFrom(AbstractMessageLite.java:202)
at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:738)
at com.alibaba.otter.node.etl.model.protobuf.BatchProto$RowBatch.parseFrom(BatchProto.java:620)
at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:221)
at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71)
at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
Protocol message was too large，看着像是记录过大. pb默认的序列化大小为64 << 20;  // 64MB
一个建议，调小canal的批量参数
