### ISSUE TITLE
时不时会报异常，然后就同步不了，产生大量日志

### ISSUE THREAD

**Issue by duson** [alibaba/otter#157]
开始报：
pid:3 nid:3 exception:canal:canal-mkkq:java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:745)

然后报大量的：
pid:3 nid:3 exception:canal:canal-mkkq:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:745)

中间间隔性的报：
pid:3 nid:3 exception:mainstem:pid:3 canal elapsed 50 seconds no data

这种不稳定性，导致每天需要上来看看没有报异常才能保证业务正常运行了

**Comment by agapple** [comment]
Could not find first log file name in binary log index file，  binlog被删除了

**Comment by duson** [comment]
看了源的二进制日志是有的，我在Canal中使用Piple中的同步进度的position，日志文件名不变，然后删除进度，重启Channel就好了

**Comment by duson** [comment]
问题还没解决阿。可能由于网络暂时几秒的连接不通导致Connection reset by peer，后来网络通了，一直再重试，再不断的报Could not find first log file name in binary log index file，实际Bin-Log是存在的，没被删除。另外，是否能设置一个重试的次数，不能日志太多，数据库或硬盘会被撑爆的

**Comment by agapple** [comment]
需要查看对应的binlog文件是否存在, show binlog events in 'xxxx' from xxx;

2016-07-05 9:05 GMT+08:00 duson <notifications@github.com>:

**Comment by duson** [comment]
旧数据已找不到了，下次出现时再查看。
另外请教个问题：
所有的Channel中的Pipeline配置中Select机器可以是同一个机器吗？按道理Load机器因为是具体执行的，所以要不同。但Select源的Bin-log应该所有都一样的。
