### ISSUE TITLE
otter由于磁盘满了产生错误，导致磁盘清理后仍然无法同步

### ISSUE THREAD

**Issue by heroghost** [alibaba/otter#158]
我的数据库服务器曾经磁盘满过。导致数据库挂了，otter也挂了，虽然后来清理磁盘，重新启动数据库。但是otter还是报磁盘错误，错误消息是这样，请问这种情况怎么恢复啊
pid:1 nid:2 exception:canal:216canal:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = binlog truncated in the middle of event; consider out of disk space on master; the first event 'mysql-bin.000019' at 349301750, the last event read from './mysql-bin.000019' at 349301987, the last byte read from './mysql-bin.000019' at 349302006.
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
需要重置下binlog位点，重新开启同步

**Comment by SunnySaman** [comment]
**我这磁盘没满，为什么还报这个错？**

```
pid:1019 nid:105 exception:canal:ce_canal53_otter_ce:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = binlog truncated in the middle of event; consider out of disk space on master; the first event 'log-bin.000025' at 343305700, the last event read from '/var/lib/mysql/logbin/log-bin.000025' at 126, the last byte read from '/var/lib/mysql/logbin/log-bin.000025' at 595843218.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:169)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:279)
	at java.lang.Thread.run(Thread.java:748)


```
