### ISSUE TITLE
binlog定位问题

### ISSUE THREAD

**Issue by weikuo0506** [alibaba/otter#176]
帮nico问个问题，如下：
manage页面日志报错：
pid:1 nid:1 exception:canal:t_order_canal:java.io.IOException: KILL DUMP 361461760 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 361461760, sqlState=HY000, sqlStateMarker=#]
with command: KILL CONNECTION 361461760
at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:168)
at java.lang.Thread.run(Thread.java:745)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:168)
at java.lang.Thread.run(Thread.java:745)

node日志报错：
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - set EntryPosition[included=false,journalName=binlog.005003,position=426754678,timestamp=1468916746000] to be pending start position before finding another proper one...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - compare exit condition:binlog.005003,426754678,1468916746000, startTimestamp=1468919185000...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - set EntryPosition[included=false,journalName=binlog.005003,position=426754678,timestamp=1468916746000] to be pending start position before finding another proper one...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - compare exit condition:binlog.005003,426758358,1468916746000, startTimestamp=1468919185000...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - set EntryPosition[included=false,journalName=binlog.005003,position=426758385,timestamp=1468916746000] to be pending start position before finding another proper one...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - compare exit condition:binlog.005003,426758385,1468916746000, startTimestamp=1468919185000...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - set EntryPosition[included=false,journalName=binlog.005003,position=426758385,timestamp=1468916746000] to be pending start position before finding another proper one...
2016-07-21 16:49:01.876 [destination = t_order_canal , address = /192.168.16.29:3306 , EventParser] DEBUG c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - compare exit condition:binlog.005003,426759498,1468916746000, startTimestamp=1468919185000...

请教各位大神 这是什么原因？

**Comment by agapple** [comment]
这是debug日志输出，第一条的异常可以忽略之，会自动重试
