### ISSUE TITLE
node连接不上zookeeper,实在没找出到底是node问题还是zookeeper问题

### ISSUE THREAD

**Issue by hjjoe1213123** [alibaba/otter#177]
zookeeper.out日志：
2016-07-22 14:20:53,489 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
2016-07-22 14:20:53,489 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
2016-07-22 14:20:53,489 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=3.10.0-327.10.1.el7.x86_64
2016-07-22 14:20:53,489 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=root
2016-07-22 14:20:53,489 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/root
2016-07-22 14:20:53,489 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/
2016-07-22 14:20:53,490 [myid:] - INFO  [main:ZooKeeperServer@787] - tickTime set to 2000
2016-07-22 14:20:53,490 [myid:] - INFO  [main:ZooKeeperServer@796] - minSessionTimeout set to -1
2016-07-22 14:20:53,490 [myid:] - INFO  [main:ZooKeeperServer@805] - maxSessionTimeout set to -1
2016-07-22 14:20:53,497 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2016-07-22 14:21:34,000 [myid:] - INFO  [SessionTracker:ZooKeeperServer@355] - Expiring session 0x156113ab8010000, timeout of 40000ms exceeded
2016-07-22 14:21:34,001 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@489] - Processed session termination for sessionid: 0x156113ab8010000
2016-07-22 14:21:34,001 [myid:] - INFO  [SyncThread:0:FileTxnLog@199] - Creating new log file: log.14
2016-07-22 14:21:45,285 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /127.0.0.1:9984
2016-07-22 14:21:45,333 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@900] - Client attempting to establish new session at /127.0.0.1:9984
2016-07-22 14:21:45,365 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@645] - Established session 0x1561143878b0000 with negotiated timeout 40000 for client /127.0.0.1:9984
2016-07-22 14:22:23,050 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x1561143878b0000, likely client has closed socket
    at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
    at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
    at java.lang.Thread.run(Thread.java:745)
2016-07-22 14:22:23,053 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /127.0.0.1:9984 which had sessionid 0x1561143878b0000
2016-07-22 14:23:04,000 [myid:] - INFO  [SessionTracker:ZooKeeperServer@355] - Expiring session 0x1561143878b0000, timeout of 40000ms exceeded
2016-07-22 14:23:04,001 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@489] - Processed session termination for sessionid: 0x1561143878b0000
2016-07-22 14:23:39,830 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /127.0.0.1:9997
2016-07-22 14:23:39,833 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@900] - Client attempting to establish new session at /127.0.0.1:9997
2016-07-22 14:23:39,849 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@645] - Established session 0x1561143878b0001 with negotiated timeout 40000 for client /127.0.0.1:9997
2016-07-22 14:23:56,903 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception

node.log日志：
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_74]
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_74]
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
2016-07-22 14:34:25.863 [main-SendThread(localhost:2081)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

Caused by: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 60000
    at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.connect(ZkClientx.java:974)
    at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.<init>(ZkClientx.java:104)
    at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.<init>(ZkClientx.java:98)
    at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.<init>(ZkClientx.java:86)
    at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.createClient(ZooKeeperClient.java:86)
    at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.access$000(ZooKeeperClient.java:38)
    at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient$1.apply(ZooKeeperClient.java:45)
    at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient$1.apply(ZooKeeperClient.java:42)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
    ... 56 more

**Comment by hjjoe1213123** [comment]
反复看了别人的教程以为是zookeeper版本问题从3.4.8降到3.4.5也是一样的错误，node就是无法连接上zookeeper无法启动

**Comment by hjjoe1213123** [comment]
telnet ip 2181 是通的，能正确连接上去
2016-07-23 10:42:53,329 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /127.0.0.1:20341
2016-07-23 10:42:56,939 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@354] - Exception causing close of session 0x0 due to java.io.IOException: Len error 1685414498
2016-07-23 10:42:56,940 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1001] - Closed socket connection for client /127.0.0.1:20341 (no session established for client)
2016-07-23 10:43:36,327 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.18.24:64333
2016-07-23 10:43:39,939 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@354] - Exception causing close of session 0x0 due to java.io.IOException: Len error 1685414498
2016-07-23 10:43:39,939 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1001] - Closed socket connection for client /192.168.18.24:64333 (no session established for client)

**Comment by hjjoe1213123** [comment]
但是telnet 请求，包括写了一个简单的socket连接zookeeper，都能连接的上，zookeeper日志也有正确显示有客户端连接，包括注释IPV6，凡是会导致zookeeper出问题的点都测试了，node还是无法连接上

**Comment by QuincyChen** [comment]
@hjjoe1213123 解决了吗？我也遇到相同的问题，折腾了很久都没成功啊，怎么办？

**Comment by QuincyChen** [comment]
zookeeper的日志和otter node的日志都是： IOException: Connection reset by peer.

**Comment by hjjoe1213123** [comment]
@QuincyChen 暂时无法解决，找了N多办法，IPV6都杠上了都没搞定，感觉根本不是zookeeper的问题

**Comment by CrystalSun1992** [comment]
两个机器互信

**Comment by hjjoe1213123** [comment]
就是单机器弄，不存在两个机器互信问题

**Comment by LWT1118** [comment]
我在搞otter的时侯遇到，zookeeper里面的NodeCount 一直为0,telnet都是通的，憋了好几天，发现少装了服务器上少装了一个nc还是什么的东西，yum装上之后通了。那个东西放到zookeeper地址上的时侯会显示一个找不到命令之类的提示，希望对你有帮助

**Comment by soniazhai** [comment]
@hjjoe1213123 这个问题最后搞定了吗？怎么解决的？

**Comment by a534432302** [comment]
最后怎么解决的这个问题？

**Comment by Win-Man** [comment]
同样遇到了这个问题，希望能有人解答一下。
错误信息如下：
```
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.otter.shared.arbitrate.impl.setl.rpc.ExtractRpcArbitrateEvent]: Constructor threw exception; nested exception is com.google.common.collect.ComputationException: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 60000
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:76)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:990)
        ... 43 more
Caused by: com.google.common.collect.ComputationException: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 60000
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
        at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
        at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.getInstance(ZooKeeperClient.java:61)
        at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.getInstance(ZooKeeperClient.java:54)
        at com.alibaba.otter.shared.arbitrate.impl.setl.rpc.ExtractRpcArbitrateEvent.<init>(ExtractRpcArbitrateEvent.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        ... 45 more
Caused by: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 60000
        at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.connect(ZkClientx.java:974)
        at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.<init>(ZkClientx.java:104)
        at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.<init>(ZkClientx.java:98)
        at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.<init>(ZkClientx.java:86)
        at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.createClient(ZooKeeperClient.java:86)
        at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.access$000(ZooKeeperClient.java:38)
        at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient$1.apply(ZooKeeperClient.java:45)
        at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient$1.apply(ZooKeeperClient.java:42)
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
        ... 56 more
```
但是ip能ping通，zookeeper的2181端口也通过telnet能通，求指教。

**Comment by zhaochl** [comment]
请问各位大神，我现在也遇见这样的问题了，有谁解决了吗

**Comment by zhaochl** [comment]
我自己解决了，有有需要请git上联系我吧

**Comment by wadekun** [comment]
@zhaochl 兄台怎么解决的呀，不方便在这里直说嘛？？

**Comment by LWT1118** [comment]
我当时的问题是缺少组件，好像是nc，装上就好了

**Comment by zhaochl** [comment]
@wadekun 过去大半年了，有点记不清了，似乎是有个地方跟服务器上不太兼容，你的具体什么问题了

**Comment by sololodestar** [comment]
/bin/bash: nc: command not found

yum install nc

**Comment by sololodestar** [comment]
或者看看manager的lib里zk版本是否与zk集群版本一致

**Comment by ErYoung2** [comment]
同遇到此问题，日志报错如下：
Established session 0x1052f2e82bb0005 with negotiated timeout 30000
原因未知。

**Comment by xiaokai111** [comment]
> 我自己解决了，有有需要请git上联系我吧

怎么解决的啊，麻烦贴一下过程

**Comment by PearceDuan** [comment]
使用[zookeeper-3.4.13](https://archive.apache.org/dist/zookeeper/zookeeper-3.4.13/)版本试试。
