### ISSUE TITLE
双向同步时库select报错

### ISSUE THREAD

**Issue by Fredwt** [alibaba/otter#180]
你好，

我做了双向同步，其中一端的库使用的是阿里云的RDS，做数据同步时，发生node报错，且同步未成功。报错如下：
pid:2 nid:3 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT COUNT(*) FROM retl.retl_mark WHERE id BETWEEN 0 AND 999]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: **SELECT command denied to user 'username'@'10.151.132.116' for table 'retl_mark'**
    at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:94)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:456)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:464)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:472)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:477)
    at org.springframework.jdbc.core.JdbcTemplate.queryForInt(JdbcTemplate.java:486)
    at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.init(AbstractOperationInterceptor.java:76)
    at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.updateMark(AbstractOperationInterceptor.java:148)
    at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.transactionBegin(AbstractOperationInterceptor.java:119)
    at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.transactionBegin(AbstractOperationInterceptor
-------------------------------------分割线-----------------------------------------
我不太明白‘username’是我配置连接阿里RDS的账号，otter为什么要用这个账号去连接otter自己的库呢？还有，我明明使用是阿里RDS的外网连接地址，怎么回返回一个阿里代理层的内网地址10.151.132.116？

**Comment by agapple** [comment]
*SELECT command denied to user 'username'@'10.151.132.116' for table 'retl_mark'**
解决权限的问题

**Comment by Fredwt** [comment]
这个话很明显我是明白的，但是请问我需要设置otter库的访问权限，username是连接我源库的账号，系统为什么会用username去连otter库呢？而且manager里没有设置这个权限的地方。我已经手都将这个权限加到otter里了，虽然我觉得不应该是这样操作的。在username具备访问otter库的权限的情况下，一样报这个错。我不太理解其中的逻辑，能指点一二吗，谢谢

**Comment by Fredwt** [comment]
‘retl_mark’表是在manager的retl库里对吗？而不是在需要同步的业务数据库里对吗？

**Comment by agapple** [comment]
在业务的数据库里哦

**Comment by Fredwt** [comment]
谢谢，已解决
