### ISSUE TITLE
otter运行几天后，关闭manager再启动报错

### ISSUE THREAD

**Issue by muyuren** [alibaba/otter#191]
otter运行几天后，关闭manager再启动报如下错误：
ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'endpoint' defined in URL [jar:file:/usr/local/manager/lib/manager.biz-4.2.13.jar!/spring/otter-manager-remote.xml]: Invocation of init method failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Fail to start server(url: dubbo://127.0.0.1:1099/endpoint?channel.readonly.sent=true&codec=dubbo&connections=30&heartbeat=5000&iothreads=4&serialization=java&server=netty&threads=50) Failed to bind NettyServer on /127.0.0.1:1099, cause: Failed to bind to: /0.0.0.0:1099
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383) ~[spring-web-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283) ~[spring-web-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at com.alibaba.citrus.webx.context.WebxComponentsLoader.initWebApplicationContext(WebxComponentsLoader.java:117) [citrus-webx-all-3.2.0.jar:3.2.0]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111) [spring-web-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:771) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:411) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:763) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:247) [jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1238) [jetty-webapp-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480) [jetty-webapp-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.Server.doStart(Server.java:277) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
	at com.alibaba.otter.manager.deployer.JettyEmbedServer.start(JettyEmbedServer.java:61) [manager.deployer-4.2.13.jar:na]
	at com.alibaba.otter.manager.deployer.OtterManagerLauncher.main(OtterManagerLauncher.java:49) [manager.deployer-4.2.13.jar:na]
Caused by: com.alibaba.dubbo.rpc.RpcException: Fail to start server(url: dubbo://127.0.0.1:1099/endpoint?channel.readonly.sent=true&codec=dubbo&connections=30&heartbeat=5000&iothreads=4&serialization=java&server=netty&threads=50) Failed to bind NettyServer on /127.0.0.1:1099, cause: Failed to bind to: /0.0.0.0:1099
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:289) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.openServer(DubboProtocol.java:266) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.export(DubboProtocol.java:253) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationEndpoint.initial(DubboCommunicationEndpoint.java:54) ~[shared.communication-4.2.13.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1581) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1522) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	... 26 common frames omitted
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to bind NettyServer on /127.0.0.1:1099, cause: Failed to bind to: /0.0.0.0:1099
	at com.alibaba.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:72) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.netty.NettyServer.<init>(NettyServer.java:63) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.netty.NettyTransporter.bind(NettyTransporter.java:33) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.Transporter$Adpative.bind(Transporter$Adpative.java) ~[na:2.5.3]
	at com.alibaba.dubbo.remoting.Transporters.bind(Transporters.java:48) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchanger.bind(HeaderExchanger.java:41) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.Exchangers.bind(Exchangers.java:63) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:287) ~[dubbo-2.5.3.jar:2.5.3]
	... 36 common frames omitted
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:1099
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:303) ~[netty-3.2.2.Final.jar:na]
	at com.alibaba.dubbo.remoting.transport.netty.NettyServer.doOpen(NettyServer.java:94) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:67) ~[dubbo-2.5.3.jar:2.5.3]
	... 43 common frames omitted
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.7.0_79]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:148) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:100) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:74) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.bind(Channels.java:468) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:200) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:348) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:176) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:142) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:90) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:282) ~[netty-3.2.2.Final.jar:na]
	... 45 common frames omitted
2016-08-29 15:37:35.940 [] WARN  org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext{/,file:/usr/local/manager/webapp/}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'endpoint' defined in URL [jar:file:/usr/local/manager/lib/manager.biz-4.2.13.jar!/spring/otter-manager-remote.xml]: Invocation of init method failed; nested exception is com.alibaba.dubbo.rpc.RpcException: Fail to start server(url: dubbo://127.0.0.1:1099/endpoint?channel.readonly.sent=true&codec=dubbo&connections=30&heartbeat=5000&iothreads=4&serialization=java&server=netty&threads=50) Failed to bind NettyServer on /127.0.0.1:1099, cause: Failed to bind to: /0.0.0.0:1099
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383) ~[spring-web-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283) ~[spring-web-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at com.alibaba.citrus.webx.context.WebxComponentsLoader.initWebApplicationContext(WebxComponentsLoader.java:117) ~[citrus-webx-all-3.2.0.jar:3.2.0]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111) ~[spring-web-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:771) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:411) ~[jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:763) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:247) ~[jetty-servlet-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1238) ~[jetty-webapp-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480) ~[jetty-webapp-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.Server.doStart(Server.java:277) [jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.7.v20120910.jar:8.1.7.v20120910]
	at com.alibaba.otter.manager.deployer.JettyEmbedServer.start(JettyEmbedServer.java:61) [manager.deployer-4.2.13.jar:na]
	at com.alibaba.otter.manager.deployer.OtterManagerLauncher.main(OtterManagerLauncher.java:49) [manager.deployer-4.2.13.jar:na]
Caused by: com.alibaba.dubbo.rpc.RpcException: Fail to start server(url: dubbo://127.0.0.1:1099/endpoint?channel.readonly.sent=true&codec=dubbo&connections=30&heartbeat=5000&iothreads=4&serialization=java&server=netty&threads=50) Failed to bind NettyServer on /127.0.0.1:1099, cause: Failed to bind to: /0.0.0.0:1099
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:289) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.openServer(DubboProtocol.java:266) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.export(DubboProtocol.java:253) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationEndpoint.initial(DubboCommunicationEndpoint.java:54) ~[shared.communication-4.2.13.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1581) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1522) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	... 26 common frames omitted
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to bind NettyServer on /127.0.0.1:1099, cause: Failed to bind to: /0.0.0.0:1099
	at com.alibaba.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:72) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.netty.NettyServer.<init>(NettyServer.java:63) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.netty.NettyTransporter.bind(NettyTransporter.java:33) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.Transporter$Adpative.bind(Transporter$Adpative.java) ~[na:2.5.3]
	at com.alibaba.dubbo.remoting.Transporters.bind(Transporters.java:48) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchanger.bind(HeaderExchanger.java:41) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.Exchangers.bind(Exchangers.java:63) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:287) ~[dubbo-2.5.3.jar:2.5.3]
	... 36 common frames omitted
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:1099
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:303) ~[netty-3.2.2.Final.jar:na]
	at com.alibaba.dubbo.remoting.transport.netty.NettyServer.doOpen(NettyServer.java:94) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:67) ~[dubbo-2.5.3.jar:2.5.3]
	... 43 common frames omitted
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_79]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_79]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.7.0_79]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:148) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:100) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:74) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.bind(Channels.java:468) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:200) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:348) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:176) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:142) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:90) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:282) ~[netty-3.2.2.Final.jar:na]
	... 45 common frames omitted

**Comment by agapple** [comment]
Caused by: java.net.BindException: Address already in use
没关干净
