### ISSUE TITLE
双向同步时出现No database selected错误

### ISSUE THREAD

**Issue by Shannon1** [alibaba/otter#194]
配置好了双写的同步，向其中一个节点插入一条数据之后，channel状态变成了挂起，对应的pipeline产生了标题为`	EXCEPTION`的日志，内容

> pid:17 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [insert into aa-test.tb_aa_test(`username` , `phone` , `mail` , `id`) values (? , ? , ? , ?) on duplicate key update `username`=values(`username`) , `phone`=values(`phone`) , `mail`=values(`mail`) , `id`=values(`id`)]; SQL state [3D000]; error code [1046]; No database selected; nested exception is java.sql.SQLException: No database selected
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
...

其中数据表结构是，其中id是自增键
```
+----+----------+-------+------+
| id | username | phone | mail |
+----+----------+-------+------+
|  1 | a        | a     | a    |
|  9 | b        | b     | b    |
+----+----------+-------+------+
```

**Comment by yjp211** [comment]
pipline--》同步进度---》 position 状态 这个值可以手动调整吗？
通过手动修改这个值，跳过相应的ddl同步出错，进行修复。可行吗？
![image](https://cloud.githubusercontent.com/assets/3926181/20341635/fa0b03fa-ac21-11e6-9d58-c64e20e0f2b0.png)

**Comment by agapple** [comment]
---Sql
    insert into aa-test.tb_aa_test(`username` , `phone` , `mail` , `id`) values (? , ? , ? , ?) on duplicate key update `username`=values(`username`) , `phone`=values(`phone`) , `mail`=values(`mail`) , `id`=values(`id`)

你看生成的sql已经带上了对应的schema

**Comment by davidhefan** [comment]
我也遇到了同样的问题，请问是如何解决的啊？

**Comment by agapple** [comment]
aa-test库名需要转义
