### ISSUE TITLE
org.apache.commons.lang.exception.NestableRuntimeException: find table   [XXXX] error

### ISSUE THREAD

**Issue by huangdq1990** [alibaba/otter#202]
被拉取的库中存在该表，但otter日志报如下错误
pid:2 nid:1 exception:setl:com.google.common.collect.ComputationException: org.apache.commons.lang.exception.NestableRuntimeException: find table 

[km.km_tbl_zookeeper_cluster] error
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
    at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:111)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:115)
    at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:102)
    at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:49)
    at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
    at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: find table [kmcommon.km_tbl_zookeeper_cluster] error
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:191)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:175)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
    ... 14 more
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: no found table [kmcommon.km_tbl_zookeeper_cluster] , pls check
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:185)
    ... 16 more

**Comment by agapple** [comment]
检查是否是大小写问题

**Comment by huangdq1990** [comment]
大小写都一致，我们的库中大概有1万表

**Comment by agapple** [comment]
no found table [kmcommon.km_tbl_zookeeper_cluster] , pls check
目前遇到的只有这么几类场景：
1. 表名大小写问题
2. 表物理被删除
3. 表权限问题，同步的DB账号没有对应表的权限

**Comment by aiaix** [comment]
@huangdq1990  有解决吗， 我的也是一样，同步过程中无缘无故就报错了。

**Comment by woson-wang** [comment]
@agapple  你好，我也遇到这个问题了，报的find table **** error，而不是table not found哦，请问下怎么排查呢

**Comment by xmapst** [comment]
@agapple 你好，我也遇到这个问题了，报的find table **** error，而不是table not found哦，请问下怎么排查呢
