### ISSUE TITLE
同步运行一段时间后出错，提示找不到mysql.user

### ISSUE THREAD

**Issue by lixqhuoli** [alibaba/otter#237]
nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.google.common.collect.ComputationException: org.apache.commons.lang.exception.NestableRuntimeException: find table [mysql.user] error
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:209)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:258)
    at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
    at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
    at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.collect.ComputationException: org.apache.commons.lang.exception.NestableRuntimeException: find table [mysql.user] error
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
    at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:111)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:115)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:429)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:388)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:139)
    ... 9 more
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: find table [mysql.user] error
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:191)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:175)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
    ... 17 more
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: no found table [mysql.user] , pls check
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:185)
    ... 19 more

**Comment by agapple** [comment]
估计没有对mysql.user表的权限，授权一下或者忽略这张表的同步
