### ISSUE TITLE
OTTER运行一段时间报错Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by aiaix** [alibaba/otter#241]
2016-12-19 17:30:00.004 [pipelineId = 17,taskName = SelectTask] WARN  c.a.o.shared.arbitrate.impl.setl.monitor.MainstemMonitor - mainstem is not run any in node
2016-12-19 17:30:00.063 [destination = sz-router-can , address = /xx.xx.xx.xx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
2016-12-19 17:30:00.071 [destination = sz-router-can , address = /xx.xx.xx.xx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.20.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.20.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.20.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2016-12-19 17:30:00.071 [destination = sz-router-can , address = /xx.xx.xx.xx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /xx.xx.xx.xx:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.20.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.20.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.20.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2016-12-19 17:30:00.071 [destination = sz-router-can , address = /xx.xx.xx.xx:3306 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:2[17:canal:sz-router-can:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:744)
]
2016-12-19 17:30:15.731 [destination = sz-router-can , address = /xx.xx.xx.xx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
2016-12-19 17:30:15.733 [destination = sz-router-can , address = /xx.xx.xx.xx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.20.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.20.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.20.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2016-12-19 17:30:15.733 [destination = sz-router-can , address = /xx.

**Comment by agapple** [comment]
Could not find first log file name in binary log index file， binlog文件被删除了

**Comment by aiaix** [comment]
没有删除，都能发现，最后我把canal删除了重建就好了

**Comment by duson** [comment]
这个问题应该是判断日志的名称错误导致的。上一个版本，在“同步进度”查看，可发现 "journalName":"bin-log.000041xxx"，会多出4个随机字符，当运行久了就会报打不到日志。新版本好像是修复了
