### ISSUE TITLE
otter的经常性断开并重连，binlog位点有更新，但是延迟递增。

### ISSUE THREAD

**Issue by luoyaogui** [alibaba/otter#244]
web控制台得到如下异常：
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:197)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:78)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:116)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)

通过跟踪分析，发现binlog拉取使用的是JDK的SocketChannel。

测试：
编写JDK的SocketChannel的C/S测试代码，发现SocketChannel的客户端无法感知连接的断开，只有通过读写异常来进行确定。

初步分析：
SocketChannel（otter内）在连接不可用时无法及时感知，但仍然进行读操作（这段时间将累加到延迟中）。

初步解决方式：
使用netty重构了并替换了SocketChannel（otter内的JDK版本），动态感知连接不可用（不再通过读异常来确定），并通过锁机制进行读写控制。 正在测试验证中……………………

**Comment by agapple** [comment]
感谢，测试通过之后可以提交一个PR给我

**Comment by luoyaogui** [comment]
重构canal的SocketChannel过程如下（基于canal-1.0.22）：
1，在canal.common的pom.xml中引入netty包。

**Comment by luoyaogui** [comment]
[重构canal的SocketChannel过程如下（基于canal-1.0.22）：
1，在canal.common的pom.xml中引入netty包。
2，在canal.parse.driver，新建com.alibaba.otter.canal.parse.driver.mysql.socket（package）用netty实现
SocketChannel、SocketChannelPool两个类；修改com.alibaba.otter.canal.parse.driver.mysql.utils（package）的PacketManager实现；修改com.alibaba.otter.canal.parse.driver.mysql（package）的MysqlConnector、MysqlQueryExecutor、MysqlUpdateExecutor。
3，在canal.parse，修改com.alibaba.otter.canal.parse.inbound.mysql（package）的MysqlConnection，修改com.alibaba.otter.canal.parse.inbound.mysql.dbsync（package）的DirectLogFetcher。]([url]([url](url)))
提交在https://github.com/luoyaogui/canal，请知悉。

**Comment by agapple** [comment]
@luoyaogui 你在你的项目里提交一个Pull request给我吧，我可以合并到主干

**Comment by luoyaogui** [comment]
好的

**Comment by agapple** [comment]
tks
