### ISSUE TITLE
错误：find table [llyt.t_ll_secret] error

### ISSUE THREAD

**Issue by aiaix** [alibaba/otter#248]
pid:12 nid:1 exception:setl:com.google.common.collect.ComputationException: org.apache.commons.lang.exception.NestableRuntimeException: find table [llyt.t_ll_secret] error
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
    at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:111)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:115)
    at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:102)
    at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:49)
    at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
    at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: find table [llyt.t_ll_secret] error
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:191)
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:175)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
    ... 14 more
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: no found table [llyt.t_ll_secret] , pls check
    at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$3.apply(AbstractDbDialect.java:185)

为什么在运行过程中总是报错，当重启同步就好了，可是表也没啥问题啊 ， otter 4.2.12 ；各位有碰到过吗，这怎么解释？ @agapple

**Comment by agapple** [comment]
4.2.14试试这个版本

**Comment by aiaix** [comment]
这个个版本升级会影响到现在的同步吗

**Comment by agapple** [comment]
不会影响现有同步，主要是增加了映射规则中源库有DDL变更时，同步刷新一下目标库的表结构

**Comment by aiaix** [comment]
这不是发送在DDL操作中，是在正常的DML过程中时常发生。需要手动重启channel. 除了升级还有其他规避方法吗

**Comment by angelmm126** [comment]
用的已经是4.2.14这个版本，同步中还是会出现错误：find table [llyt.t_ll_secret] error to 错误：find table [schema.t_ll_xxx] error

**Comment by cslingjun** [comment]
> 这不是发生在DDL操作中，是在正常的DML过程中时常发生。需要手动重启channel. 除了升级还有其他规避方法吗

4.2.18  mysql也配置了忽略大小写 ，仍然出现了find table [xxx] error，但是channel会重启，会恢复，然后该表数据也同步正常 。这个有办法解决吗？

**Comment by LiuYinglovecode** [comment]
用的也是4.2.18，在做压测同步时也遇到了这个问题，从库是专门建的空表，但过一会儿自动好了，并不影响运行，可能是bug吧。

**Comment by xmapst** [comment]
@agapple 你好，我也遇到这个问题. 源和目标的大小写一致的
