### ISSUE TITLE
双向同步报主键冲突和唯一索引冲突，如何解决或跳过

### ISSUE THREAD

**Issue by zhuhuawu** [alibaba/otter#251]
因为主键冲突和唯一索引冲突导致挂起不能同步，不知如何解决
唯一索引冲突：
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into ysod.product_gd_detail(`gd_id` , `ws_id` , `comp_number` , `pass_number` , `nopass_number` , `effect_pass` , `operator_id` , `work_hour` , `comp_date` , `owner_id` , `finish` , `station_id` , `real_pass_number` , `real_comp_number` , `id`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `gd_id`=values(`gd_id`) , `ws_id`=values(`ws_id`) , `comp_number`=values(`comp_number`) , `pass_number`=values(`pass_number`) , `nopass_number`=values(`nopass_number`) , `effect_pass`=values(`effect_pass`) , `operator_id`=values(`operator_id`) , `work_hour`=values(`work_hour`) , `comp_date`=values(`comp_date`) , `owner_id`=values(`owner_id`) , `finish`=values(`finish`) , `station_id`=values(`station_id`) , `real_pass_number`=values(`real_pass_number`) , `real_comp_number`=values(`real_comp_number`) , `id`=values(`id`)]; Duplicate entry '3466728-1198-49287' for key 'gd_id_2'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3466728-1198-49287' for key 'gd_id_2'

主键冲突：
pid:15 nid:6 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [update ysod.product_gd_detail set `gd_id` = ? , `ws_id` = ? , `comp_number` = ? , `pass_number` = ? , `nopass_number` = ? , `effect_pass` = ? , `operator_id` = ? , `work_hour` = ? , `comp_date` = ? , `owner_id` = ? , `finish` = ? , `station_id` = ? , `real_pass_number` = ? , `real_comp_number` = ? , `id` = ? where ( `id` = ? )]; Duplicate entry '29830031' for key 'PRIMARY'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '29830031' for key 'PRIMARY'

**Comment by agapple** [comment]
如果涉及唯一键的变更，建议是先删除后插入的模式，否则针对多个唯一键的记录进行交换的时候会出错

**Comment by zhuhuawu** [comment]
先删除后插入的模式在哪里开启，第二这种模式是不是会删除已有的数据，造成数据丢失？？

**Comment by jin544642965** [comment]
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into `ehuzhu`.`member`(`createDate` , `modifyDate` , `deposit` , `email` , `isAccountEnabled` , `isAccountLocked` , `lockedDate` , `loginDate` , `loginFailureCount` , `loginIp` , `password` , `passwordRecoverKey` , `point` , `registerIp` , `safeAnswer` , `safeQuestion` , `username` , `memberRank_id` , `szMemberUserId` , `IDNO` , `IDType` , `QQNO` , `VIPChannel` , `VIPFrom` , `VIPType` , `address` , `birthday` , `expiricalValue` , `faxno` , `hobby` , `industryType` , `location` , `marriageStatus` , `mobileNO` , `personalURL` , `position` , `realName` , `registerType` , `sex` , `telephoneNO` , `zipcode` , `isEmailBinding` , `isMobileNOBinding` , `currentValidatePoint` , `pictruePath` , `usedPoint` , `fullDegree` , `retrieveEmailSendDate` , `verifyEmailSendDate` , `retrieveEmailvalid` , `headPicPath` , `mBindInfoForLogin_id` , `fromWap` , `openID` , `eqz_open_id` , `jkgj_open_id` , `nation` , `province` , `city` , `country` , `verifyNo` , `contactPerson` , `contactNo` , `companyRecomandFlag` , `companyRecomandId` , `channelPromotion` , `employeeFlag` , `employeeInfoId` , `oldPerson` , `wxNo` , `MBindInfoForLogin` , `id`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `createDate`=values(`createDate`) , `modifyDate`=values(`modifyDate`) , `deposit`=values(`deposit`) , `email`=values(`email`) , `isAccountEnabled`=values(`isAccountEnabled`) , `isAccountLocked`=values(`isAccountLocked`) , `lockedDate`=values(`lockedDate`) , `loginDate`=values(`loginDate`) , `loginFailureCount`=values(`loginFailureCount`) , `loginIp`=values(`loginIp`) , `password`=values(`password`) , `passwordRecoverKey`=values(`passwordRecoverKey`) , `point`=values(`point`) , `registerIp`=values(`registerIp`) , `safeAnswer`=values(`safeAnswer`) , `safeQuestion`=values(`safeQuestion`) , `username`=values(`username`) , `memberRank_id`=values(`memberRank_id`) , `szMemberUserId`=values(`szMemberUserId`) , `IDNO`=values(`IDNO`) , `IDType`=values(`IDType`) , `QQNO`=values(`QQNO`) , `VIPChannel`=values(`VIPChannel`) , `VIPFrom`=values(`VIPFrom`) , `VIPType`=values(`VIPType`) , `address`=values(`address`) , `birthday`=values(`birthday`) , `expiricalValue`=values(`expiricalValue`) , `faxno`=values(`faxno`) , `hobby`=values(`hobby`) , `industryType`=values(`industryType`) , `location`=values(`location`) , `marriageStatus`=values(`marriageStatus`) , `mobileNO`=values(`mobileNO`) , `personalURL`=values(`personalURL`) , `position`=values(`position`) , `realName`=values(`realName`) , `registerType`=values(`registerType`) , `sex`=values(`sex`) , `telephoneNO`=values(`telephoneNO`) , `zipcode`=values(`zipcode`) , `isEmailBinding`=values(`isEmailBinding`) , `isMobileNOBinding`=values(`isMobileNOBinding`) , `currentValidatePoint`=values(`currentValidatePoint`) , `pictruePath`=values(`pictruePath`) , `usedPoint`=values(`usedPoint`) , `fullDegree`=values(`fullDegree`) , `retrieveEmailSendDate`=values(`retrieveEmailSendDate`) , `verifyEmailSendDate`=values(`verifyEmailSendDate`) , `retrieveEmailvalid`=values(`retrieveEmailvalid`) , `headPicPath`=values(`headPicPath`) , `mBindInfoForLogin_id`=values(`mBindInfoForLogin_id`) , `fromWap`=values(`fromWap`) , `openID`=values(`openID`) , `eqz_open_id`=values(`eqz_open_id`) , `jkgj_open_id`=values(`jkgj_open_id`) , `nation`=values(`nation`) , `province`=values(`province`) , `city`=values(`city`) , `country`=values(`country`) , `verifyNo`=values(`verifyNo`) , `contactPerson`=values(`contactPerson`) , `contactNo`=values(`contactNo`) , `companyRecomandFlag`=values(`companyRecomandFlag`) , `companyRecomandId`=values(`companyRecomandId`) , `channelPromotion`=values(`channelPromotion`) , `employeeFlag`=values(`employeeFlag`) , `employeeInfoId`=values(`employeeInfoId`) , `oldPerson`=values(`oldPerson`) , `wxNo`=values(`wxNo`) , `MBindInfoForLogin`=values(`MBindInfoForLogin`) , `id`=values(`id`)]; Duplicate entry '15960573671' for key 'idx_member_tel'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '15960573671' for key 'idx_member_tel'
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:625)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:617)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:545)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:462)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:275)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load(<generated>)
        at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
        at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '15960573671' for key 'idx_member_tel'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:818)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
        ... 21 more

遇到类似问题 唯一键经常出现重复。 数据操作是按先删后插入的。  感觉是不update语句丢失
