### ISSUE TITLE
同步挂起，报CommunicationException

### ISSUE THREAD

**Issue by zhuhuawu** [alibaba/otter#252]
pid:18 nid:2 exception:setl:com.alibaba.otter.shared.communication.core.exception.CommunicationException: call[172.16.51.223:2088] , Event[AbstractRpcPipe.RpcEvent[key=RpcPipeKey[nid=6,identity=Identity[channelId=9,pipelineId=18,processId=42389],time=1483937363315,dataType=DB_BATCH],type=get]]
Caused by: com.alibaba.dubbo.rpc.RpcException: Invoke remote method timeout. method: acceptEvent, provider: dubbo://172.16.51.223:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&iothreads=4&lazy=true&serialization=java&threads=50, cause: Waiting server-side response timeout. start time: 2017-01-09 12:51:59.012, end time: 2017-01-09 12:52:49.013, client elapsed: 0 ms, server elapsed: 50001 ms, timeout: 50000 ms, request: Request [id=9132793, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=acceptEvent, parameterTypes=[class com.alibaba.otter.shared.communication.core.model.Event], arguments=[AbstractRpcPipe.RpcEvent[key=RpcPipeKey[nid=6,identity=Identity[channelId=9,pipelineId=18,processId=42389],time=1483937363315,dataType=DB_BATCH],type=get]], attachments={path=endpoint, version=0.0.0}]], channel: /192.168.4.243:41671 -> /172.16.51.223:2088
at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:99)
at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
at com.alibaba.dubbo.common.bytecode.proxy3.acceptEvent(proxy3.java)
at com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationConnection.call(DubboCommunicationConnection.java:45)
at com.alibaba.otter.shared.communication.core.impl.DefaultCommunicationClientImpl.call(DefaultCommunicationClientImpl.java:96)
at com.alibaba.otter.node.common.communication.NodeCommmunicationClient.call(NodeCommmunicationClient.java:51)
at com.alibaba.otter.node.etl.common.pipe.impl.rpc.RowDataRpcPipe.get(RowDataRpcPipe.java:60)
at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:146)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout. start time: 2017-01-09 12:51:59.012, end time: 2017-01-09 12:52:49.013, client elapsed: 0 ms, server elapsed: 50001 ms, timeout: 50000 ms, request: Request [id=9132793, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=acceptEvent, parameterTypes=[class com.alibaba.otter.shared.communication.core.model.Event], arguments=[AbstractRpcPipe.RpcEvent[key=RpcPipeKey[nid=6,identity=Identity[channelId=9,pipelineId=18,processId=42389],time=1483937363315,dataType=DB_BATCH],type=get]], attachments={path=endpoint, version=0.0.0}]], channel: /192.168.4.243:41671 -> /172.16.51.223:2088
at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:107)
at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
... 14 more

**Comment by agapple** [comment]
网络超时，重试一下即可
