### ISSUE TITLE
数据不能同步

### ISSUE THREAD

**Issue by chenchangqun** [alibaba/otter#258]
按照教程安装后，数据不能同步，报出

[destination = test_cancal , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:1[1:canal:test_cancal:java.lang.NullPointerException
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:284)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:722)

**Comment by chenchangqun** [comment]
确定是4.2.14版本的一个bug
换了4.2.13后好用了。
系统环境如下
java： version "1.7.0_79"
linux:CentOS release 6.5 (Final)

**Comment by agapple** [comment]
已经在主干中修复，4.2.15会修复这个问题

**Comment by heroghost** [comment]
我换成4.2.13还是报这个错

**Comment by heroghost** [comment]
otter和node一起更换到4.2.13才有用

**Comment by wf2002** [comment]
我之前配了一台centos，一台windows。otter都正常，后来配两台centos之间同步。结果什么错误都没有，就是数据无法同步。换了几个版本，都是同样的问题，防火墙也关闭了，不知道为什么？
