### ISSUE TITLE
升级到otter4.2.14后出现异常

### ISSUE THREAD

**Issue by fashchina** [alibaba/otter#265]
目前mysql升级到5.7.13，otter升级到4.2.14.
其中manager升级后启动正常，node.deploy启动就报端口冲突，换了2台新机器，也出现同样的问题。
通过命令netstat -tln | grep 2089，并没有多个应用在使用
关闭掉node.deploy，通过netstat -tln | grep 2089命令找不到任何一条匹配数据。。。

把node的端口改成其他的比如3088/3089还是存在类似问题，是应用初始化问题还是？

[root@L-DB-109-70 node.deployer-4.2.14]# tail -f logs/node/node.log 
2017-02-06 15:48:17.323 [main] WARN  org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED SocketConnector@0.0.0.0:2089: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376) ~[na:1.7.0_79]
	at java.net.ServerSocket.bind(ServerSocket.java:376) ~[na:1.7.0_79]
	at java.net.ServerSocket.<init>(ServerSocket.java:237) ~[na:1.7.0_79]
	at java.net.ServerSocket.<init>(ServerSocket.java:181) ~[na:1.7.0_79]
	at org.eclipse.jetty.server.bio.SocketConnector.newServerSocket(SocketConnector.java:96) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.bio.SocketConnector.open(SocketConnector.java:85) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.server.bio.SocketConnector.doStart(SocketConnector.java:156) ~[jetty-server-8.1.7.v20120910.jar:8.1.7.v20120910]

**Comment by agapple** [comment]
我记得默认值不是2089吧，你改过端口参数？

**Comment by fashchina** [comment]
之前用4.2.12都好的，那在manager控制台需要如何调整？

**Comment by dusonchen** [comment]
https://github.com/alibaba/otter/releases 4.2.14 版本的下载不了，速度一直是0K，麻烦重新上传下

**Comment by aiaix** [comment]
4.2.14如果基于某个位点开始同步，是基于以前的binlog+pos,还是用GTID？？

**Comment by fashchina** [comment]
基于以前的binlog+pos,数据库没有开启GTID。后面我把数据库数据都删除后，node启动成功，但是我又得重新配置一遍，痛苦。。

**Comment by fashchina** [comment]
@dusonchen 
我把文件传到我的百度云山了，您可以通过下面地址下载
node--》http://pan.baidu.com/s/1pKEdgqZ
manager--》http://pan.baidu.com/s/1hs81YwW

**Comment by GreenJoson** [comment]
我用4.2.13目前还可以，4.2.14一直用不了，同步不成功，各种错误
