### ISSUE TITLE
做双向同步，channel挂起了，pipeline日志显示如下，是因为数据库命名使用错误么。数据库命名是这种格式 xxxxx_db

### ISSUE THREAD

**Issue by crysmail** [alibaba/otter#270]
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT COUNT(*) FROM retl.retl_mark WHERE id BETWEEN 0 AND 999]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'retl.retl_mark' doesn't exist
at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:456)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:464)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:472)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:477)
at org.springframework.jdbc.core.JdbcTemplate.queryForInt(JdbcTemplate.java:486)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.init(AbstractOperationInterceptor.java:76)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.updateMark(AbstractOperationInterceptor.java:148)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.transactionBegin(AbstractOperationInterceptor.java:119)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.transactionBegin(AbstractOperationInterceptor.java:51)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.OperationInterceptorFactory.transactionBegin(OperationInterceptorFactory.java:49)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.OperationInterceptorFactory.transactionBegin(OperationInterceptorFactory.java:39)
at com.alibaba.otter.node.etl.load.loader.interceptor.ChainLoadInterceptor.transactionBegin(ChainLoadInterceptor.java:61)
at com.alibaba.otter.node.etl.load.loader.interceptor.ChainLoadInterceptor.transactionBegin(ChainLoadInterceptor.java:26)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:619)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:613)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:541)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:458)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:251)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'retl.retl_mark' doesn't exist
at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
at com.mysql.jdbc.Util.getInstance(Util.java:372)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:441)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
... 32 more
:-----------------
- PairId: 2 , TableId: 2 , EventType : D , Time : 1486547621000 
- Consistency : , Mode : 
-----------------
---Pks
EventColumn[index=0,columnType=-5,columnName=id,columnValue=27,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
EventColumn[index=1,columnType=-5,columnName=sid,columnValue=0,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=2,columnType=-5,columnName=uid,columnValue=0,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=3,columnType=-5,columnName=ktuid,columnValue=0,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=4,columnType=-7,columnName=type,columnValue=0,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=5,columnType=12,columnName=username,columnValue=yh,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=6,columnType=1,columnName=password,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=7,columnType=12,columnName=true_name,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=8,columnType=12,columnName=email,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=9,columnType=12,columnName=telphone,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=10,columnType=-7,columnName=sex,columnValue=0,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=11,columnType=12,columnName=province,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=12,columnType=12,columnName=city,columnValue=,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=13,columnType=1,columnName=salt,columnValue=,isNull=false,isKey=false,isUpdate=true]
---Sql
delete from tongbu_db.kt_user where `id` = ? 

Caused by: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT COUNT(*) FROM retl.retl_mark WHERE id BETWEEN 0 AND 999]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'retl.retl_mark' doesn't exist
at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:456)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:464)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:472)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:477)
at org.springframework.jdbc.core.JdbcTemplate.queryForInt(JdbcTemplate.java:486)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.init(AbstractOperationInterceptor.java:76)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.updateMark(AbstractOperationInterceptor.java:148)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.transactionBegin(AbstractOperationInterceptor.java:119)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.AbstractOperationInterceptor.transactionBegin(AbstractOperationInterceptor.java:51)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.OperationInterceptorFactory.transactionBegin(OperationInterceptorFactory.java:49)
at com.alibaba.otter.node.etl.load.loader.db.interceptor.operation.OperationInterceptorFactory.transactionBegin(OperationInterceptorFactory.java:39)
at com.alibaba.otter.node.etl.load.loader.interceptor.ChainLoadInterceptor.transactionBegin(ChainLoadInterceptor.java:61)
at com.alibaba.otter.node.etl.load.loader.interceptor.ChainLoadInterceptor.transactionBegin(ChainLoadInterceptor.java:26)

**Comment by agapple** [comment]
retl.retl_mark表不存在，按照我的wiki双向同步需要创建一些系统表

**Comment by bytename** [comment]
有wiki双向同步地址没有,发下看看
