### ISSUE TITLE
mysql为两台机器内网ip时，抛出 SelectException，Communications link failure

### ISSUE THREAD

**Issue by MiaoZhou** [alibaba/otter#279]
在局域网中，尝试了如下架构

zookeeper: 192.168.1.2:2181
manager1: 192.168.1.2:8080
db: 192.168.1.2:3306 供manger使用的数据库

manager2: 192.168.1.3:8080
node1: 192.168.1.3:2088
node3: 192.168.1.3:2091
db1: 172.16.2.2:3306 docker启动的mysql，仅192.168.1.3可访问

node2: 192.168.1.4:2088
node4: 192.168.1.4:2091
db2: 172.16.3.2:3306 docker启动的mysql，仅192.168.1.4可访问

所有服务启动成功，按照wiki文档在manager中配置好db1->db2的单向同步
select 选择 node1 node3
load 选择 node2 node4

执行结果是，create table的ddl同步成功，尝试在db1中插入数据时报错，看报错信息，是数据库通信错误
但提示信息是select异常，而所配置的select机node3是能够访问db1的，按理说应该没有问题

而当我把db1 db2端口映射为局域网可访问时，单向同步、双A同步都成功
所以想请教一下，需要同步的mysql必须是公网地址，或者所有node都能访问到的地址吗？

> pid:1 nid:3 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
>     at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:211)
>     at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:258)
>     at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
>     at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
>     at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
>     at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
>     at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
>     at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
>     at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
>     at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory.getDbDialect(DbDialectFactory.java:117)
>     at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:442)
>     at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:390)
>     at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:141)
>     ... 9 more
> Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
>     at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
>     at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:331)
>     at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory$2$1.apply(DbDialectFactory.java:81)
>     at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory$2$1.apply(DbDialectFactory.java:76)
>     at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
>     ... 16 more
> Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
>     at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
>     at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
>     at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
>     at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
>     at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
>     ... 20 more
> Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>     at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
>     at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
>     at com.mysql.jdbc.MysqlIO.(MysqlIO.java:338)
>     at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2237)
>     at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270)
>     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
>     at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:794)
>     at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:44)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>     at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
>     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
>     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
>     at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
>     at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
>     at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
>     at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
>     ... 24 more
> Caused by: java.net.ConnectException: Connection timed out
>     at java.net.PlainSocketImpl.socketConnect(Native Method)
>     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
>     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
>     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
>     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>     at java.net.Socket.connect(Socket.java:579)
>     at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
>     at com.mysql.jdbc.MysqlIO.(MysqlIO.java:297)
>     ... 40 more

**Comment by agapple** [comment]
Caused by: java.net.ConnectException: Connection timed out
网络问题我不太懂

**Comment by dearplain** [comment]
遇到同样问题，难道mysql的地址要暴露到公网？用内部地址无法成功。 @agapple

**Comment by hittanic** [comment]
遇到同样的问题，帮忙回复一下，或者给个解决方案建议  @agapple

**Comment by guixincui** [comment]
我也遇到同样的问题，然后导致挂起

**Comment by tjoelsson** [comment]
Getting the same error in 4.2.15. It was working fine before upgrading. Will this be fixed in 4.2.16?

**Comment by jandison** [comment]
同样的问题，一直怀疑是网络架构问题导致的，node走的一台代理机器
