### ISSUE TITLE
突然报了这个错误，同步失败了 pid:1 nid:1 exception:canal:canal1:java.lang.NullPointerException

### ISSUE THREAD

**Issue by jimhj** [alibaba/otter#280]
pid:1 nid:1 exception:canal:canal1:java.lang.NullPointerException
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:398)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:313)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:162)
    at java.lang.Thread.run(Thread.java:745)

大神给看看，谢谢！！

**Comment by GreenJoson** [comment]
突然间也报这个，不知道什么问题~

**Comment by jimhj** [comment]
数据库是阿里云RDS，可能跟阿里云RDS突然间断网有关系，数据同步不一致了，发生了错误。只能手动清理了一些错误数据，然后删除同步位点重启channel了

**Comment by agapple** [comment]
可能是低版本的bug，等我发布一个最新的canal版本

**Comment by leiy88** [comment]
4.2.15始终报这个错，无法同步，有解决方法没？

**Comment by tmriver** [comment]
我也遇到了，双向同步时

**Comment by jimhj** [comment]
这个问题现在修正了吗?

**Comment by jimhj** [comment]
就这个问题，我想再问一下，如果由于网络问题，两边数据库互连不上了，应该怎么处理？

**Comment by jwcjlu** [comment]
这个问题产生的原因是网络的原因吗？

**Comment by tangdelong** [comment]
这个问题如何解决

**Comment by agapple** [comment]
aliyun rds的支持, canal目前有一个新版本做了处理, otter8月份会发布一个版本依赖新版canal

**Comment by Perterually** [comment]
> aliyun rds的支持, canal目前有一个新版本做了处理, otter8月份会发布一个版本依赖新版canal

4.2.17也有这个报错
