### ISSUE TITLE
Error converting from 'String' to 'BigDecimal' null

### ISSUE THREAD

**Issue by LWT1118** [alibaba/otter#281]
在同步的过程中报出如下异常，请问这个问题该怎么排查呢，是表里面某个字段为null引起的?
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.extract.exceptions.ExtractException: java.util.concurrent.ExecutionException: org.apache.commons.beanutils.ConversionException: Error converting from 'String' to 'BigDecimal' null
Caused by: java.util.concurrent.ExecutionException: org.apache.commons.beanutils.ConversionException: Error converting from 'String' to 'BigDecimal' null
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor.extract(DatabaseExtractor.java:139)
at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor.extract(DatabaseExtractor.java:81)
at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor$$FastClassByCGLIB$$f79e22c6.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor$$EnhancerByCGLIB$$de7bc45b.extract()
at com.alibaba.otter.node.etl.extract.extractor.OtterExtractorFactory.extract(OtterExtractorFactory.java:50)
at com.alibaba.otter.node.etl.extract.ExtractTask$1.run(ExtractTask.java:79)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.beanutils.ConversionException: Error converting from 'String' to 'BigDecimal' null
at org.apache.commons.beanutils.converters.AbstractConverter.handleError(AbstractConverter.java:267)
at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:164)
at org.apache.commons.beanutils.converters.ConverterFacade.convert(ConverterFacade.java:60)
at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:470)
at com.alibaba.otter.node.etl.common.db.utils.SqlUtils.stringToSqlValue(SqlUtils.java:149)
at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor$DatabaseExtractWorker.buildTableData(DatabaseExtractor.java:539)
at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor$DatabaseExtractWorker.run(DatabaseExtractor.java:306)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 5 more
Caused by: java.lang.NumberFormatException
at java.math.BigDecimal.(BigDecimal.java:494)
at java.math.BigDecimal.(BigDecimal.java:383)
at java.math.BigDecimal.(BigDecimal.java:806)
at org.apache.commons.beanutils.converters.NumberConverter.toNumber(NumberConverter.java:448)
at org.apache.commons.beanutils.converters.NumberConverter.convertToType(NumberConverter.java:268)
at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:156)
... 12 more

**Comment by agapple** [comment]
你用了自由 门造数据？

**Comment by LWT1118** [comment]
对，使用了自由门，我正在看源代码，定位到DatabaseExtractWorker.buildTableData方法的 `data.columnValues[i] = SqlUtils.stringToSqlValue(keyColumn.getColumnValue(),
                            tableColumn.getTypeCode(),
                            tableColumn.isRequired(),
                            false);`
从报错上应该是数据库里面有一个类型为decimal的字段值为null在转BigDecimal的时侯失败了，数据库为mysql，但是因为表非常多，不容易查找。
我看到ConvertUtilsBean类的convert方法里面有
`if (log.isDebugEnabled()) {
            log.debug("Convert string '" + value + "' to class '" +
                      clazz.getName() + "'");
        }`
这个debug模式怎么开启呢？

**Comment by LWT1118** [comment]
目前otter采用的版本为4.2.13

**Comment by LWT1118** [comment]
经过查看代码发现当mysql数据类型为numeric或者decimal的时侯会转成java的BigDeicmal。
经过查找，只找到了两张表的联合主键里面某个字段为decimal类型，但是这两张表里面都没有数据……

**Comment by LWT1118** [comment]
问题已解决，原因是retl_buffer的pk_data写入了列的名称而不是value
