### ISSUE TITLE
一数据源多节点，有些节点延时严重

### ISSUE THREAD

**Issue by duson** [alibaba/otter#310]
源目标是一个数据库，后面有20多个子节点同步里面的几个表。运行一段时间后，有几个节点的Bin-log的Position还是很早之前的。日志中不断输出：
[destination = xxx , address = /x.x.x.x:3306 , EventParser] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Received EOF packet from server, apparent master disconnected. It's may be duplicate slaveId , check instance config

在“同步进度”中查看的信息中"identity":{"slaveId":-1, 因为几个节点都是部署在不同的机器上，slaveId都是-1，不知道是不是这个原因导致的。

另外一个问题：偶尔会报下面的错，停止，重新启动又正常了。
2017-05-04 00:58:47.268 [pipelineId = 17,taskName = SelectTask] WARN  com.alibaba.otter.node.etl.select.SelectTask - WARN ## select is failed.
java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104) ~[canal.instance.core-1.0.23.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:116) ~[canal.server-1.0.23.jar:na]
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.stop(CanalEmbedSelector.java:225) ~[node.etl-4.2.14.jar:na]
	at com.alibaba.otter.node.etl.select.SelectTask.stopup(SelectTask.java:186) ~[node.etl-4.2.14.jar:na]
	at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:121) ~[node.etl-4.2.14.jar:na]
2017-05-04 00:58:47.341 [pipelineId = 17,taskName = SelectTask] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:18[17:setl:java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165)
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:116)
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.stop(CanalEmbedSelector.java:225)
	at com.alibaba.otter.node.etl.select.SelectTask.stopup(SelectTask.java:186)
	at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:121)
]

**Comment by agapple** [comment]
换canal 1.0.24试试

**Comment by duson** [comment]
换了canal 1.0.25后，仍然会报:
2017-05-12 09:06:45.529 [destination = mall , address = /172.30.248.148:3306 , EventParser] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Received EOF packet from server, apparent master disconnected. It's may be duplicate slaveId , check instance config

**Comment by duson** [comment]
附加一些其它信息：多个节点是在同一个数据库服务器中的不同的数据库。
是不是因为这样，所以被认为是重复的从库，只解析了一个，其它忽略了？但是我停止Channel，然后启动，又能继续将之前没同步的同步过来

**Comment by agapple** [comment]
重复的slaveId，看看mysql server对应的slave dump的链接是否还处于正常工作，如果不是kill一下

**Comment by dusonchen** [comment]
怎样看mysql server对应的slave dump的链接

**Comment by dusonchen** [comment]
@agapple 通过使用processlist 查看Binlog Dump的进程，其它节点的都是恒定不变。但提示上面错误的那4个节点就会：有时显示，有时消失，同时只能出现2个。比较奇怪

**Comment by agapple** [comment]
4.2.15已经修复
