### ISSUE TITLE
阿里云RDS binlog 丢失问题

### ISSUE THREAD

**Issue by qdql** [alibaba/otter#313]
运行几天就会出现找不到binlog文件问题，mainstem状态就是一直处于定位状态，position 状态中的"journalName":"mysql-bin.000xxx"已经不在阿里云RDS “show binary logs;” 列表中了，问题可能和链接页面 http://www.tuicool.com/articles/NrqMBrE 描述的问题有些相似。
日志中就会出现：
pid:3 nid:1 exception:canal:canal_3:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)
如何解决？

**Comment by qdql** [comment]
问题找到了，是ddl语句同步出错，导致position不更新导致
