### ISSUE TITLE
单向数据同步，同步一直报错

### ISSUE THREAD

**Issue by heroghost** [alibaba/otter#319]
你好，单向同步无法同步，一直报这个异常
pid:1 nid:1 exception:canal:canal1:java.lang.NullPointerException
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:284)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)

**Comment by heroghost** [comment]
otter和node一起更换到4.2.13解决这个问题。据说是4.2.14的Bug

**Comment by heroghost** [comment]
![image](https://cloud.githubusercontent.com/assets/2017291/26345140/8fc9e32a-3fd4-11e7-8c7c-e55e074e6c69.png)

我用这种映射方式，会报错
pid:1 nid:2 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: name is not found in column pairs: {id=[account_id]}
