### ISSUE TITLE
提示same server_uuid/server_id报错，但检查各节点都没有冲突

### ISSUE THREAD

**Issue by aricy** [alibaba/otter#321]
pid:23 nid:1 exception:canal:xxxx:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000037' at 380571072, the last event read from './mysql-bin.000037' at 380582680, the last byte read from './mysql-bin.000037' at 380582680.
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)

**Comment by tmriver** [comment]
我也遇到了，双向同步时，canal 1.0.22

**Comment by erictanghu** [comment]
我也遇到了 解决了吗。。

**Comment by agapple** [comment]
新版本canal 1.0.25可以解决

**Comment by agapple** [comment]
4.2.15已经修复

**Comment by linqh1** [comment]
我刚刚也遇到了，但是同步似乎有在进行。只是日志中一直有报这个错
