### ISSUE TITLE
RDS数据同步稳定运行十几天，出现这种异常，如何排查

### ISSUE THREAD

**Issue by qdql** [alibaba/otter#328]
pid:4 nid:1 exception:setl:java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165)
    at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104)
    at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:116)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.stop(CanalEmbedSelector.java:225)
    at com.alibaba.otter.node.etl.select.SelectTask.stopup(SelectTask.java:186)
    at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:121)

**Comment by agapple** [comment]
canal新版本已修复

**Comment by yeweilg** [comment]
请问是什么版本修复的

**Comment by jsrgqinbin** [comment]
@qdql 现在可以 RDS 同步到 自建库上了吗？

**Comment by qdql** [comment]
可以的，已经在线上运行

**Comment by trockxi** [comment]
请问阿里RDS同步到自建库，如何部署？

**Comment by eancoder** [comment]
请教一下使用阿里云的RDS如何做的配置的，我使用RDS的公网请求地址一直提示我配置信息有问题，这个怎么处理的？
