### ISSUE TITLE
现有连接被远程主机强行关闭

### ISSUE THREAD

**Issue by heshangdaben** [alibaba/otter#339]
开始同步的时候能正常运行，一段时间不会报错，运行了大概10个小时后，就会报existing connection was forcibly closed by the remote host，然后一直报Could not initialize class com.alibaba.otter.canal.common.utils.JsonUtils;
2017-07-01 07:28:54.445 INFO  c.a.otter.manager.biz.common.alarm.AbstractAlarmService - has sent alarm [AlarmMessage[message=pid:4 nid:1 exception:canal:citu_tdesk_canal:java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Unknown Source)
,receiveKey=otterteam]] to drgoon agent.
2017-07-01 07:59:09.040 INFO  c.a.otter.manager.biz.common.alarm.AbstractAlarmService - has sent alarm [AlarmMessage[message=pid:4 nid:1 exception:canal:citu_tdesk_canal:java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.otter.canal.common.utils.JsonUtils
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:415)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:315)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:161)
	at java.lang.Thread.run(Unknown Source)

**Comment by agapple** [comment]
canal:citu_tdesk_canal:java.io.IOException: An existing connection was forcibly closed by the remote host

远端强制关闭了？

**Comment by heshangdaben** [comment]
数据库重启或者服务关闭以后一直报Could not initialize class com.alibaba.otter.canal.common.utils.JsonUtils数据就不一致了，怎么处理才能保证数据一致？
