### ISSUE TITLE
大量java.lang.InterruptedException: null异常，数据没有同步

### ISSUE THREAD

**Issue by humphery755** [alibaba/otter#345]
otter运行了一段时间后，就停止了同步，Channel状态也是running的 , 查看日志出现大量的InterruptedException，看不出哪里出了问题

2017-07-14 17:51:08.172 [pipelineId = 3,taskName = transformWorker] ERROR c.a.o.n.e.common.io.download.impl.aria2c.Aria2cRetriever - java.lang.InterruptedException
com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: java.lang.InterruptedException
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[na:1.7.0_67]
        at java.lang.Object.wait(Object.java:503) ~[na:1.7.0_67]
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:263) ~[na:1.7.0_67]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:111) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:63) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:49) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandDownload.download(AbstractCommandDownload.java:70) ~[node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandRetriever.doRetrieve(AbstractCommandRetriever.java:62) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:199) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76) [node.etl-4.2.14.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
2017-07-14 17:51:08.173 [pipelineId = 3,taskName = transformWorker] ERROR c.a.o.n.e.common.io.download.impl.aria2c.Aria2cRetriever - java.lang.InterruptedException
com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: java.lang.InterruptedException
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[na:1.7.0_67]
        at java.lang.Object.wait(Object.java:503) ~[na:1.7.0_67]
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:263) ~[na:1.7.0_67]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:111) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:63) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:49) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandDownload.download(AbstractCommandDownload.java:70) ~[node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandRetriever.doRetrieve(AbstractCommandRetriever.java:62) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:199) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76) [node.etl-4.2.14.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
2017-07-14 17:51:08.173 [pipelineId = 3,taskName = transformWorker] ERROR c.a.o.n.e.common.io.download.impl.aria2c.Aria2cRetriever - java.lang.InterruptedException
com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: java.lang.InterruptedException
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[na:1.7.0_67]
        at java.lang.Object.wait(Object.java:503) ~[na:1.7.0_67]
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:263) ~[na:1.7.0_67]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:111) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:63) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:49) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandDownload.download(AbstractCommandDownload.java:70) ~[node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandRetriever.doRetrieve(AbstractCommandRetriever.java:62) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:199) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76) [node.etl-4.2.14.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
2017-07-14 17:51:08.173 [pipelineId = 3,taskName = transformWorker] ERROR c.a.o.n.e.common.io.download.impl.aria2c.Aria2cRetriever - java.lang.InterruptedException
com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: java.lang.InterruptedException
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[na:1.7.0_67]
        at java.lang.Object.wait(Object.java:503) ~[na:1.7.0_67]
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:263) ~[na:1.7.0_67]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:111) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:63) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:49) ~[shared.common-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandDownload.download(AbstractCommandDownload.java:70) ~[node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandRetriever.doRetrieve(AbstractCommandRetriever.java:62) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:199) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128) [node.etl-4.2.14.jar:na]
        at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76) [node.etl-4.2.14.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]

**Comment by agapple** [comment]
调用aria2c报错吧，参看一下quick start的wiki

**Comment by jeffreyji666** [comment]
手动执行aria2c命令显示正常，但log里还是大量这种error.
![15_56_08__07_14_2018](https://user-images.githubusercontent.com/2270558/42722440-a95c18a6-877e-11e8-982a-1e73c92a07eb.jpg)
