### ISSUE TITLE
canal

### ISSUE THREAD

**Issue by yangshike** [alibaba/otter#355]
大数据量的批量插入  类似select   into 的sql  （10w条记录），canal 报错：
pid:1 nid:2 exception:canal:canal_master:java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 63
    at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:650)
    at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.(QueryLogEvent.java:477)
    at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:154)
    at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:106)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:123)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: limit excceed: 63
    at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:561)
    at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:563)
    ... 6 more

**Comment by liyongcun** [comment]
修改启动脚本的参数-Xmx5120m

**Comment by agapple** [comment]
用的什么版本，otter、canal、mysql
