### ISSUE TITLE
com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask

### ISSUE THREAD

**Issue by caijie129** [alibaba/otter#358]
pid:1 nid:2 exception:setl:java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165)
at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:116)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.stop(CanalEmbedSelector.java:225)
at com.alibaba.otter.node.etl.select.SelectTask.stopup(SelectTask.java:186)
at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:121)
求大神指点，1天报二次 ，不影响同步，不知道是不是bug

**Comment by agapple** [comment]
尝试一下4.2.15版本吧
