### ISSUE TITLE
OTTER同步报错TODO HINT

### ISSUE THREAD

**Issue by swords1999** [alibaba/otter#359]
pid:3 nid:4 exception:setl:com.alibaba.druid.sql.parser.ParserException: TODO HINT
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:322)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2036)
at com.alibaba.otter.node.etl.common.db.utils.DdlUtils.convert(DdlUtils.java:31)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:80)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:50)
at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

**Comment by swords1999** [comment]
发现是临时表就报这个错误，canal版本1.0.24。
忽略临时表同步还是有别的方法呢？

**Comment by agapple** [comment]
可以在canal的黑名单里过滤一下临时变，不解析到otter中处理
