### ISSUE TITLE
otter数据同步报错

### ISSUE THREAD

**Issue by dnfhujun** [alibaba/otter#360]
otter做数据单向同步报错，异常信息如下：
pid:7 nid:2 exception:canal:zhenai_crm_member:com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:59)
at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:322)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:108)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:326)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:130)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.collect.ComputationException: com.alibaba.otter.canal.filter.exception.CanalFilterException: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
at com.alibaba.otter.canal.filter.PatternUtils.getPattern(PatternUtils.java:41)
at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24)
at Script_1502075147792_0.execute0(Unknown Source)
at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53)
... 9 more
Caused by: com.alibaba.otter.canal.filter.exception.CanalFilterException: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
Caused by: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.

是映射关系配置错了么？有分表的情况

**Comment by dnfhujun** [comment]
这个问题找到了，是因为需要同步的分表的数量太大了，改成多个canal同步，每个canal同步一部分分表就可以了，建议是不是可以把可以同步的表的数量改大点

**Comment by agapple** [comment]
或者同步的表使用正则来减少数量

**Comment by robert1070** [comment]
@dnfhujun 这个问题分表的极限大概是多少个，我们也有类似的业务，配置过了会出现同样的问题

**Comment by zk19930911** [comment]
@robert1070 我一个channel下同步了4个分表，一共1536张表，也报这个错误；一个channel下同步2个分表，一共718张表没问题。

**Comment by zk19930911** [comment]
四个分表
order1.order_[0-255],
order1.order_detail_[0-511],
order2.order_[0-255],
order2.order_detail_[0-511]
