### ISSUE TITLE
MysqlDetectingTimeTask异常导致同步停止

### ISSUE THREAD

**Issue by angelmm126** [alibaba/otter#363]
异常日志：
pid:1 nid:1 exception:setl:java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165)
    at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104)
    at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:116)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.stop(CanalEmbedSelector.java:225)
    at com.alibaba.otter.node.etl.select.SelectTask.stopup(SelectTask.java:186)
    at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:121)

报完此异常后，Manager会重启同步，但同步有时一直显示定位中，有时会显示运行，但位点不动，求大神指点一下，什么原因造成的，怎么解决这种问题？

**Comment by agapple** [comment]
低版本bug，当前master已经修复

**Comment by angelmm126** [comment]
我用的版本是4.2.13，是不是改成4.2.14就可以了，替换版本需要注意哪些？

**Comment by huogenghao** [comment]
@agapple 我使用的就是4.2.14，但是还是报出该异常。似乎最新的发布版本并没有修复这个bug。

**Comment by agapple** [comment]
我近期会发一个最新包

**Comment by agapple** [comment]
尝试一下4.2.15版本吧
