### ISSUE TITLE
KILL DUMP 12375013 failure:java.io.IOException: ErrorPacket

### ISSUE THREAD

**Issue by pdj408** [alibaba/otter#367]
pid:1 nid:1 exception:canal:otter_canal:java.io.IOException: KILL DUMP 12375013 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 12375013, sqlState=HY000, sqlStateMarker=#]
with command: KILL CONNECTION 12375013
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
    at java.lang.Thread.run(Thread.java:745)

    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
    at java.lang.Thread.run(Thread.java:745)

**Comment by pdj408** [comment]
刚开始没有出现这个问题，然后我停止Channel后，再重新启动就报这个错。。找了半天没找到原因。有谁短简什么原因导致的么？？

**Comment by agapple** [comment]
尝试一下4.2.15版本吧
