### ISSUE TITLE
为什么同步进度那里 position 状态 :无信息

### ISSUE THREAD

**Issue by heshangdaben** [alibaba/otter#375]
现在是一个数据库服务，分了6个数据库，分别向不同的服务器传输数据。对每一个服务器单独建立了一个canal，现在启动多了channel，就报错：
pid:9 nid:1 exception:canal:tdesk_test_canal:java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.otter.canal.common.utils.JsonUtils 
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:415) 
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:315) 
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:161) 
    at java.lang.Thread.run(Thread.java:748) 

发现在同步进度那里 position 状态 :无信息。

**Comment by agapple** [comment]
Could not initialize class com.alibaba.otter.canal.common.utils.JsonUtils

改动过代码？

**Comment by heshangdaben** [comment]
没改过代码啊

**Comment by heshangdaben** [comment]
找到原因是这个mainstem is not run any in node。没有位点信息，能正常同步，zookeeper的问题吗？

**Comment by trockxi** [comment]
我也遇到同样问题，做的是单向同步，不能同步，node日志提示如下
2017-11-15 22:15:51.519 [DubboServerHandler-127.0.0.1:2088-thread-12] WARN  c.a.o.shared.arbitrate.impl.setl.monitor.MainstemMonitor - mainstem is not run any in node
2017-11-15 22:21:36.522 [DubboServerHandler-127.0.0.1:2088-thread-16] ERROR com.alibaba.otter.node.etl.OtterController - ## stop s/e/t/l task error!
java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104) ~[canal.instance.core-1.0.23.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:116) ~[canal.server-1.0.23.jar:na]
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.stop(CanalEmbedSelector.java:225) ~[node.etl-4.2.14.jar:na]
	at com.alibaba.otter.node.etl.select.SelectTask.shutdown(SelectTask.java:524) ~[node.etl-4.2.14.jar:na]
	at com.alibaba.otter.node.etl.OtterController.stopPipeline(OtterController.java:215) [node.etl-4.2.14.jar:na]
	at com.alibaba.otter.node.etl.OtterController.process(OtterController.java:145) [node.etl-4.2.14.jar:na]
还望大侠指点迷津

**Comment by solarzc** [comment]
这个可能是你要的那个库没有开 bin-log

**Comment by dcdebug** [comment]
我的问题和@heshangdaben 差不多，只是一直显示如下：
![image](https://user-images.githubusercontent.com/28588794/35430752-9afdc74a-02b4-11e8-8127-9a49d519df5a.png)

**Comment by i323654** [comment]
解决了吗，我也碰到这个问题，同步正常，但是position一直没有值

**Comment by telltime** [comment]
我的也是这个问题，配置都正常运行，就是数据不同步。（mysql5.7.21    zookeeper3.4.12   otter4.2.17）

**Comment by sh20104510** [comment]
> 解决了吗，我也碰到这个问题，同步正常，但是position一直没有值

解决了吗，我也遇到这个问题，能正常同步也是

**Comment by sh20104510** [comment]
> 我的问题和@heshangdaben 差不多，只是一直显示如下： ![image](https://user-images.githubusercontent.com/28588794/35430752-9afdc74a-02b4-11e8-8127-9a49d519df5a.png)

解决了吗。遇到同样问题

**Comment by sh20104510** [comment]
> 解决了吗，我也碰到这个问题，同步正常，但是position一直没有值

解决了吗

**Comment by SunnySaman** [comment]
看看zookeeper里面是不是对应的canal数据有问题
