### ISSUE TITLE
管理页面zookeeper管理项点刷新报空指针

### ISSUE THREAD

**Issue by welyss** [alibaba/otter#381]
Caused by: com.alibaba.citrus.service.moduleloader.ModuleEventException: Failed to execute handler: public void com.alibaba.otter.manager.web.home.module.action.AutoKeeperClusterAction.doRefresh(java.lang.Long,com.alibaba.citrus.turbine.Navigator) throws java.lang.Exception
        at com.alibaba.citrus.service.moduleloader.impl.adapter.AbstractModuleEventAdapter.executeAndReturn(AbstractModuleEventAdapter.java:102) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.service.moduleloader.impl.adapter.AbstractModuleEventAdapter.execute(AbstractModuleEventAdapter.java:58) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.turbine.pipeline.valve.PerformActionValve.invoke(PerformActionValve.java:63) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        ... 50 common frames omitted
**Caused by: java.lang.NullPointerException: null**
        at com.alibaba.otter.manager.biz.autokeeper.impl.AutoKeeperCollector.groupSessionPath(AutoKeeperCollector.java:298) ~[manager.biz-4.2.14.jar:na]
        at com.alibaba.otter.manager.biz.autokeeper.impl.AutoKeeperCollector.collectorWatchStat(AutoKeeperCollector.java:241) ~[manager.biz-4.2.14.jar:na]
        at com.alibaba.otter.manager.web.home.module.action.AutoKeeperClusterAction.doRefresh(AutoKeeperClusterAction.java:86) ~[manager.web-4.2.14.jar:na]
        at com.alibaba.otter.manager.web.home.module.action.AutoKeeperClusterAction$$FastClassByCGLIB$$c01695d6.invoke(<generated>) ~[cglib-nodep-2.2.jar:na]
        at net.sf.cglib.reflect.FastMethod.invoke(FastMethod.java:53) ~[cglib-nodep-2.2.jar:na]
        at com.alibaba.citrus.service.moduleloader.impl.adapter.MethodInvoker.invoke(MethodInvoker.java:70) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.service.moduleloader.impl.adapter.AbstractModuleEventAdapter.executeAndReturn(AbstractModuleEventAdapter.java:100) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        ... 52 common frames omitted
===================================================================
好像是系统没有nc命令导致，这个在安装指南里没提到。。。。

**Comment by welyss** [comment]
close
