### ISSUE TITLE
同步一小段时间后，部分channel挂起：.PipeException: write_byte_error

### ISSUE THREAD

**Issue by shiwanjie** [alibaba/otter#388]
详细的错误日志是：
pid:2 nid:1 exception:setl:com.alibaba.otter.node.etl.common.pipe.exception.PipeException: com.alibaba.otter.node.etl.common.pipe.exception.PipeException: write_byte_error
Caused by: com.alibaba.otter.node.etl.common.pipe.exception.PipeException: write_byte_error
Caused by: java.io.FileNotFoundException: /srv/nbs/0/node/bin/../htdocs/DbBatch-2017-10-11-17-06-47-1-2-295.gzip (No such file or directory)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.(FileOutputStream.java:212)
at java.io.FileOutputStream.(FileOutputStream.java:160)
at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.saveDbBatch(RowDataHttpPipe.java:159)
at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.put(RowDataHttpPipe.java:66)
at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.put(RowDataPipeDelegate.java:92)
at com.alibaba.otter.node.etl.extract.ExtractTask$1.run(ExtractTask.java:89)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:701)

我一共配置了5个channel，来实现5个分库的数据合并同步到一个总库里去，起初运行正常，过一会后看channel状态发现，channel1、3、4挂起了，点击解挂后，马上再次挂起。
5个channel里用的node节点是相同的2个node节点，报错的是node1节点，但该node1节点在channel2和5上依然正常工作。
请大大指点迷津，谢谢！

**Comment by agapple** [comment]
/srv/nbs/0/node/bin/../htdocs/DbBatch-2017-10-11-17-06-47-1-2-295.gzip (No such file or directory).

是否你的同步速度太慢，gzip文件被自动清理了，我印象中是10分钟之后会清理历史的gzip包，如果你的同步时间慢于10分钟
