### ISSUE TITLE
com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#393]
有两个pipeline(单向，mysql5.7.16-log)跑着跑着突然就报了这个错，没找到其他相关日志。。

```
com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.NullPointerException
        at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:209) ~[node.etl-4.2.13.jar:na]
        at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:258) ~[node.etl-4.2.13.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236) [node.etl-4.2.13.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94) [node.etl-4.2.13.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208) [node.etl-4.2.13.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
2017-11-01 19:44:53.447 [pipelineId = 15,taskName = ProcessSelect] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:1[15:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.NullPointerException
        at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:209)
        at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:258)
        at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
        at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
        at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

**Comment by luyee** [comment]
加了log,这个DataMedia为null了。看到是ddl相关的(源/目标库名，表名均相同)，跳过关闭ddl与ddl异常，又正常了。

```
                DataMedia dataMedia = ConfigHelper.findSourceDataMedia(pipeline,
                    schemaName,
                    tableName,
                    notExistReturnNull);
                logger.warn("#####     schemaName: "+schemaName+" tableName: "+tableName+" notExistReturnNull "+notExistReturnNull+" dataMedia:"+ JSON.toJSONString(dataMedia));
                // 如果EventType是CREATE/ALTER，需要reload
                // DataMediaInfo;并且把CREATE/ALTER类型的事件丢弃掉.
                if (dataMedia != null && (eventType.isCreate() || eventType.isAlter() || eventType.isRename())) {
                    DbDialect dbDialect = dbDialectFactory.getDbDialect(pipeline.getId(),
                        (DbMediaSource) dataMedia.getSource());
                    dbDialect.reloadTable(schemaName, tableName);// 更新下meta信息
                }

                boolean ddlSync = pipeline.getParameters().getDdlSync();
                if (ddlSync) {
                    // 处理下ddl操作
                    EventData eventData = new EventData();
                    eventData.setSchemaName(schemaName);
                    eventData.setTableName(tableName);
                    eventData.setEventType(eventType);
                    eventData.setExecuteTime(entry.getHeader().getExecuteTime());
                    eventData.setSql(rowChange.getSql());
                    eventData.setDdlSchemaName(rowChange.getDdlSchemaName());
                    eventData.setTableId(dataMedia.getId());
                    return Arrays.asList(eventData);
```

**Comment by hittanic** [comment]
解决了吗兄弟，什么原因，遇到了类似的错误

**Comment by yhp353134** [comment]
@luyee 你好 请问下这个错误与 skipDdlException 有什么关系？

**Comment by quanllong** [comment]
遇到同样的问题，源表执行 ALTER TABLE xxxx MODIFY COLUMN name VARCHAR(100) NOT NULL 触发的，变更字段长度，从50变到100

**Comment by quanllong** [comment]
找到根因了，是otter不支持rename类型的DDL同步，源表rename会触发otter空指针异常
