### ISSUE TITLE
双向同步主站点点位更新但不同步

### ISSUE THREAD

**Issue by JerryChin** [alibaba/otter#402]
有中国节点和新加坡节点，其中以中国节点主节点建立双向channel，新加坡 -> 中国同步正常，但中国节点不同步到新加坡，控制台可以看到点位信息不断更新，但是最后同步时间为空。

![snipaste_20171113_150351](https://user-images.githubusercontent.com/11764942/32713476-68fa3612-c884-11e7-9a72-6b0fdb8c0893.png)

以下是新加坡node日志：
```
2017-11-13 06:42:18.627 [DubboClientReconnectTimer-thread-1] WARN  com.alibaba.dubbo.remoting.transport.AbstractClient -  [DUBBO] client reconnect to xxxxxxxxxx:2088 find error . url: dubbo://xxxxxxxx:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50, dubbo version: 2.5.3, current host: 172.31.4.203
		com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://xxxxxxxxxx:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50) failed to connect to server /xxxxxxxxxxxx:2088, error message is:connection timed out
		at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124) ~[dubbo-2.5.3.jar:2.5.3]
		at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280) ~[dubbo-2.5.3.jar:2.5.3]
		at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:145) ~[dubbo-2.5.3.jar:2.5.3]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
		at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
		Caused by: java.net.ConnectException: connection timed out
		at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:371) ~[netty-3.2.2.Final.jar:na]
		at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:283) ~[netty-3.2.2.Final.jar:na]
		at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.2.2.Final.jar:na]
		at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) ~[netty-3.2.2.Final.jar:na]
		... 3 common frames omitted
		2017-11-13 06:42:47.219 [dubbo-remoting-server-heartbeat-thread-1] WARN  c.a.dubbo.remoting.exchange.support.header.HeartBeatTask -  [DUBBO] Close channel NettyChannel [channel=[id: 0x16796b5a, /xxxxxxxxx:34506 => /172.31.4.203:2088]], because heartbeat read idle time out: 15000ms, dubbo version: 2.5.3, current host: 172.31.4.203
2017-11-13 06:42:18.627 [DubboClientReconnectTimer-thread-1] WARN  com.alibaba.dubbo.remoting.transport.AbstractClient -  [DUBBO] client reconnect to xxxxxxxxxx:2088 find error . url: dubbo://xxxxxxxx:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50, dubbo version: 2.5.3, current host: 172.31.4.203
		com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://xxxxxxxxxx:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50) failed to connect to server /xxxxxxxxxxxx:2088, error message is:connection timed out
		at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124) ~[dubbo-2.5.3.jar:2.5.3]
		at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280) ~[dubbo-2.5.3.jar:2.5.3]
		at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:145) ~[dubbo-2.5.3.jar:2.5.3]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
		at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
		Caused by: java.net.ConnectException: connection timed out
		at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:371) ~[netty-3.2.2.Final.jar:na]
		at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:283) ~[netty-3.2.2.Final.jar:na]
		at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.2.2.Final.jar:na]
		at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) ~[netty-3.2.2.Final.jar:na]
		... 3 common frames omitted
		2017-11-13 06:42:47.219 [dubbo-remoting-server-heartbeat-thread-1] WARN  c.a.dubbo.remoting.exchange.support.header.HeartBeatTask -  [DUBBO] Close channel NettyChannel [channel=[id: 0x16796b5a, /xxxxxxxxx:34506 => /172.31.4.203:2088]], because heartbeat read idle time out: 15000ms, dubbo version: 2.5.3, current host: 172.31.4.203
```

**Comment by hphuangpu** [comment]
请问您的问题解决了吗？什么原因该如何处理能分享一下不？

**Comment by hphuangpu** [comment]
这也可以？我出过几回这个问题，是通过重启node机器恢复正常的。不知具体原因。
