### ISSUE TITLE
配置node， 和manager 不在同一台机器时报错。node运行状态显示 已启动，但是同步数据库的时候报错

### ISSUE THREAD

**Issue by solarzc** [alibaba/otter#405]
pid:7 nid:1 exception:canal:246 (danduzk):com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error!
Caused by: java.io.IOException: ErrorPacket [errorNumber=1227, fieldCount=-1, message=Access denied; you need the SUPER,REPLICATION CLIENT privilege for this operation, sqlState=42000, sqlStateMarker=#]
with command: show master status
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:60)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:69)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPosition(MysqlEventParser.java:590)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:347)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:313)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:162)
    at java.lang.Thread.run(Thread.java:745)

**Comment by solarzc** [comment]
不是权限问题，已经赋予全部权限了

**Comment by luyee** [comment]
you need the SUPER,REPLICATION CLIENT privilege for this operation, sqlState
