### ISSUE TITLE
配置完任务后，启动同步任务总是挂起。

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [alibaba/otter#426]
报的是关于dubbo的一个错误：
15:45:22.300 [main] INFO  c.a.o.m.d.OtterManagerLauncher - ## the manager server is running now ......
15:47:12.772 [Self-Monitor-0] WARN  monitorInfo - no enabled alarm rule at all. Check the rule setting please!
15:47:28.234 [qtp2012744708-62] WARN  c.a.c.s.r.session.impl.SessionImpl - Requested session ID "_S4DKTI2I8mq_jpr9OSJQoqcMyvL_U6GFZrSYU2Z" does not match the ID in session model "XaDdKKRrOYWe5h4ts2vchRhvnzlFpJikhCRKexEZ".  Force expired the session.
15:48:34.875 [communication-async-0] INFO  c.a.d.r.p.d.LazyConnectExchangeClient -  [DUBBO] Lazy connect to dubbo://192.168.90.116:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50, dubbo version: 2.5.3, current host: 127.0.0.1
15:48:34.930 [communication-async-0] INFO  c.a.d.r.transport.AbstractClient -  [DUBBO] Successed connect to server /192.168.90.116:2088 from NettyClient 172.16.250.50 using dubbo version 2.5.3, channel is NettyChannel [channel=[id: 0x3083d4a8, /192.168.90.116:62230 => /192.168.90.116:2088]], dubbo version: 2.5.3, current host: 172.16.250.50
15:48:34.931 [communication-async-0] INFO  c.a.d.r.transport.AbstractClient -  [DUBBO] Start NettyClient LAPTOP-URSMTD89/172.16.250.50 connect to the server /192.168.90.116:2088, dubbo version: 2.5.3, current host: 172.16.250.50
15:48:35.160 [New I/O client worker #1-1] WARN  c.alibaba.dubbo.rpc.support.RpcUtils -  [DUBBO] Not found class endpoint, cause: endpoint, dubbo version: 2.5.3, current host: 172.16.250.50
java.lang.IllegalStateException: Not found class endpoint, cause: endpoint
	at com.alibaba.dubbo.common.utils.ReflectUtils.forName(ReflectUtils.java:610) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:68) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:82) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:109) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:97) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:126) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:87) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:134) [dubbo-2.5.3.jar:2.5.3]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:540) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.2.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: endpoint
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_112]
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:420) ~[jetty-webapp-8.1.7.v20120910.jar:8.1.7.v20120910]
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:382) ~[jetty-webapp-8.1.7.v20120910.jar:8.1.7.v20120910]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_112]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_112]
	at com.alibaba.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:679) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:624) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.common.utils.ReflectUtils.forName(ReflectUtils.java:608) ~[dubbo-2.5.3.jar:2.5.3]
	... 21 common frames omitted

本人对dubbo框架了解的并不深入。看这个错误日志，最疑惑的是172.16.250.50这个ip地址是做什么用的，没搞明白，本地也没有这个ip的地址啊。跪求路过的大神解惑！

**Comment by agapple** [comment]
连不上node？

**Comment by ZhiXingHeYiApple** [comment]
错误日志中172.16.250.50这个ip是因为本地开启了openVPN的缘故，在网络访问时会替换原有ip。但是关掉openVPN后这个错误还是出现。后面清空otter底层数据库的所有配置表，重新配置任务并运行，又正常了。我觉得应该不是配置的原因，之前跑成功过的。

**Comment by xf0516** [comment]
2018-02-01 11:02:40.860 [New I/O client worker #1-9] WARN  c.alibaba.dubbo.rpc.support.RpcUtils -  [DUBBO] Not found class endpoint, cause: endpoint, dubbo version: 2.8.4, current host: 192.168.73.14
java.lang.IllegalStateException: Not found class endpoint, cause: endpoint
	at com.alibaba.dubbo.common.utils.ReflectUtils.forName(ReflectUtils.java:610) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:68) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:84) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:117) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:98) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:134) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:95) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46) [dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:134) [dubbo-2.8.4.jar:2.8.4]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:540) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.2.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
Caused by: java.lang.ClassNotFoundException: endpoint
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_67]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_67]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_67]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_67]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_67]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_67]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_67]
	at java.lang.Class.forName0(Native Method) ~[na:1.7.0_67]
	at java.lang.Class.forName(Class.java:270) ~[na:1.7.0_67]
	at com.alibaba.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:679) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:624) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.common.utils.ReflectUtils.forName(ReflectUtils.java:608) ~[dubbo-2.8.4.jar:2.8.4]
	... 21 common frames omitted

**Comment by ZhiXingHeYiApple** [comment]
@xf0516 你好，这个otter问题，你后面解决了吗？怎么解决的？

**Comment by quanllong** [comment]
我也报了这个错
