### ISSUE TITLE
has an error, retrying. caused by  java.nio.channels.ClosedByInterruptException: null

### ISSUE THREAD

**Issue by hittanic** [alibaba/otter#434]
WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"xxxxx","port":xxxxxx}},"postion":{"included":false,"journalName":"mysql-bin.000004","position":75784970,"serverId":212,"timestamp":1513663476000}}
2017-12-19 14:08:33.488 [destination = GZ2CQ_CANAL , address = /xxxxx:xxxxxx, EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address xxxxx:xxxxxx, has an error, retrying. caused by 
java.nio.channels.ClosedByInterruptException: null
	at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49) ~[canal.parse.driver-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:69) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]

otter部署为双向同步，一个节点正常，不报错， 另一个不支持ddl的node节点每隔2分钟报一次上面的错误，看了下binlog的位点，是到了最后的位点，binlog有没有新的日志写进来。 但是为什么另一个节点不报这个错误。 而且过了一段时间， channel 就挂点了，通过 manager启动channel 失败！！！！
查看manager的日志，报如下错误：

**Comment by hittanic** [comment]
![image](https://user-images.githubusercontent.com/7236171/34143335-3b7e87c4-e4c7-11e7-80b5-e02d877d8f5e.png)

**Comment by agapple** [comment]
ClosedByInterruptException应该是哪里发送过canal处理异常，导致binlog dump链接被关闭

**Comment by hittanic** [comment]
发现channel挂掉的原因是这个， dubbo 连接池被用完了， 我看代码里是写死的50个。

**Comment by snecker** [comment]
@hittanic 连接池用完的问题解决了吗？
