### ISSUE TITLE
KILL DUMP 1911674 failure:java.io.IOException: ErrorPacket [errorNumber=1094

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#448]
manager一直刷报这种日志，数据没法同步

```
pid:5 nid:1 exception:canal:yycsdb:java.io.IOException: KILL DUMP 1911674 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 1911674, sqlState=HY000, sqlStateMarker=#]
with command: KILL CONNECTION 1911674
at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
at java.lang.Thread.run(Thread.java:745)

at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by agapple** [comment]
这个应该是老版本的错误，可以考虑升级

**Comment by luyee** [comment]
4.2.13  升级到4.2.15 需要做哪些改动嘛 还是重新部署下otter就好了。zk上的位点节点，otter数据库可以无缝兼容吗？

**Comment by agapple** [comment]
重新部署即可
