### ISSUE TITLE
谁遇到这个错误

### ISSUE THREAD

**Issue by robert1070** [alibaba/otter#466]
2018-02-06 23:02:26.512 [destination = tuia_news , address = /xxx:port , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /xxx:port  has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:59) ~[aviator-2.2.1.jar:na]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[canal.filter-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:373) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:66) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:337) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:184) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:145) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: com.google.common.collect.ComputationException: com.alibaba.otter.canal.filter.exception.CanalFilterException: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889) ~[guava-18.0.jar:na]
	at com.alibaba.otter.canal.filter.PatternUtils.getPattern(PatternUtils.java:41) ~[canal.filter-1.0.25.jar:na]
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24) ~[canal.filter-1.0.25.jar:na]
	at Script_1517926445082_0.execute0(Unknown Source) ~[na:na]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[aviator-2.2.1.jar:na]
	... 9 common frames omitted
Caused by: com.alibaba.otter.canal.filter.exception.CanalFilterException: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
Caused by: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
	at org.apache.oro.text.regex.Perl5Compiler.compile(Unknown Source) ~[oro-2.0.8.jar:na]
	at org.apache.oro.text.regex.Perl5Compiler.compile(Unknown Source) ~[oro-2.0.8.jar:na]
	at com.alibaba.otter.canal.filter.PatternUtils$1.apply(PatternUtils.java:30) ~[canal.filter-1.0.25.jar:na]
	at com.alibaba.otter.canal.filter.PatternUtils$1.apply(PatternUtils.java:25) ~[canal.filter-1.0.25.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356) ~[guava-18.0.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182) ~[guava-18.0.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151) ~[guava-18.0.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67) ~[guava-18.0.jar:na]
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885) ~[guava-18.0.jar:na]
	at com.alibaba.otter.canal.filter.PatternUtils.getPattern(PatternUtils.java:41) ~[canal.filter-1.0.25.jar:na]
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24) ~[canal.filter-1.0.25.jar:na]
	at Script_1517926445082_0.execute0(Unknown Source) ~[na:na]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[aviator-2.2.1.jar:na]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[canal.filter-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:373) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:66) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:337) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:184) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:145) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by robert1070** [comment]
我试着减少了同步的分表，是解决了对应的问题，是否可以支持到更大的分表了

**Comment by agapple** [comment]
org.apache.oro.text.regex.MalformedPatternException: Expression is too large.

**Comment by agapple** [comment]
建议用正则

**Comment by zk19930911** [comment]
@agapple  我使用正则了，还是报上边的错误

**Comment by zk19930911** [comment]
@agapple 
我一个channel下同步了4个分表，一共1536张表，也报这个错误；一个channel下同步2个分表，一共718张表没问题。
四个分表如下:
order1.order_[0-255],
order1.order_detail_[0-511],
order2.order_[0-255],
order2.order_detail_[0-511]
