### ISSUE TITLE
从4.2.14升级到4.2.15后无法同步了，报以下错误

### ISSUE THREAD

**Issue by dev-v** [alibaba/otter#481]
2018-03-07 12:22:21.796 [destination = canal_3307 , address = /ip:3307 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"ip","port":3307}},"postion":{"included":false,"journalName":"mysql-bin.005368","position":389137045,"serverId":433307,"timestamp":1520169481000}}
2018-03-07 12:22:22.801 [destination = canal_3307 , address = /ip:3307 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from position > file size
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:94) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137) [canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) [canal.parse-1.0.25.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2018-03-07 12:22:22.801 [destination = canal_3307 , address = /ip:3307 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /ip:3307 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from position > file size
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:94) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2018-03-07 12:22:22.802 [destination = canal_3307 , address = /ip:3307 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:3[5:canal:canal_3307:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from position > file size
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:94)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
	at java.lang.Thread.run(Thread.java:745)
]

**Comment by luyee** [comment]
位点不对吧。。
