### ISSUE TITLE
[求助]查看node信息，报Failed to invoke Valve[#2/3, level 3]错误。

### ISSUE THREAD

**Issue by davidhefan** [alibaba/otter#495]
node分别在中国法国，查看中国node信息没有问题，查看法国node，报出如下错误信息（详细的在附件中）。请问会是什么原因导致的呢？
[node_error.txt](https://github.com/alibaba/otter/files/1844167/node_error.txt)

`HTTP ERROR 500
Problem accessing /node_info.htm. Reason:

    Failed to invoke Valve[#2/3, level 3]: com.alibaba.citrus.turbine.pipeline.valve.PerformTemplateScreenValve#2c9306d3:PerformTemplateScreenValve
Caused by:
com.alibaba.citrus.service.pipeline.PipelineException: Failed to invoke Valve[#2/3, level 3]: 

com.alibaba.citrus.turbine.pipeline.valve.PerformTemplateScreenValve#2c9306d3:PerformTemplateScreenValve
	at com.alibaba.citrus.service.pipeline.impl.PipelineImpl$PipelineContextImpl.invokeNext(PipelineImpl.java:161)
	at com.alibaba.citrus.turbine.pipeline.valve.PerformActionValve.invoke(PerformActionValve.java:73)
	at com.alibaba.citrus.service.pipeline.impl.PipelineImpl$PipelineContextImpl.invokeNext(PipelineImpl.java:157)
	at com.alibaba.citrus.service.pipeline.impl.PipelineImpl$PipelineContextImpl.invoke(PipelineImpl.java:210)
	at com.alibaba.citrus.service.pipeline.impl.valve.ChooseValve.invoke(ChooseValve.java:98)`

**Comment by elefaint** [comment]
hostname -i 获取的ip地址不正确

**Comment by davidhefan** [comment]
谢谢你的回答，但是我在2台服务器上分别查了hostname，是正确的

**Comment by hongjun0619** [comment]
I met the same problem

**Comment by hongjun0619** [comment]
我之前是实现中美数据库同步，之前也是用的两个node，然后遇到的问你和你一样，查看是小事，最后配置完不能同步，这是非常尴尬的，最后我只在中国搭建了唯一的一个node，可以实现他们之间的正常同步，你可以试试
