### ISSUE TITLE
 illegal json data

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#498]
otter 4.2.13

```
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: illegal json data
	at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_scalar(JsonConversion.java:150) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_value(JsonConversion.java:67) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.element(JsonConversion.java:272) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.toJsonString(JsonConversion.java:285) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.toJsonString(JsonConversion.java:295) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:957) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:99) ~[canal.parse.dbsync-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:467) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:377) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:111) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:327) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:177) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

**Comment by luyee** [comment]
拉了几个patch[illegal+json+data](https://github.com/alibaba/canal/issues?utf8=%E2%9C%93&q=illegal+json+data)想替换canal1.0.22 ,没解决

临时解决方案，用node4.2.13跟4.2.15 交替跑。 原因是4.2.13 不支持json, 4.2.15  不稳定

正常跑4.2.13  
碰到json问题临时跑4.2.15
