### ISSUE TITLE
 java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#500]
```
pid:60 nid:2 exception:canal:yoolifin_ yoolifin:com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.OutOfMemoryError: Java heap space
Caused by: java.lang.OutOfMemoryError: Java heap space
at java.lang.String.substring(String.java:1969)
at com.alibaba.druid.sql.parser.Lexer.subString(Lexer.java:134)
at com.alibaba.druid.sql.parser.Lexer.scanString2(Lexer.java:1045)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlLexer.scanString(MySqlLexer.java:406)
at com.alibaba.druid.sql.parser.Lexer.nextTokenValue(Lexer.java:388)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseValueClause(SQLStatementParser.java:3229)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2514)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:47)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:165)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:473)
at com.alibaba.otter.canal.parse.inbound.mysql.ddl.DruidDdlParser.parse(DruidDdlParser.java:47)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsQueryEvent(LogEventConvert.java:300)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:122)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:66)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:337)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:184)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:145)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by f-zhao** [comment]
看一下node的JVM配置

**Comment by luyee** [comment]
dump出来发现buffer里边Event实例有13332个，总大小有6G多.

<img width="802" alt="2018-04-02 15 06 10" src="https://user-images.githubusercontent.com/3666051/38187214-49f8e2c2-3689-11e8-8d17-9eb2ff6c0cc5.png">

起初Xmx增大到8192m了，修改了pipeline的batchSize,还是不行。

其实应该修改canal的参数，内存存储buffer记录数。

**Comment by agapple** [comment]
嗯，这个是ringbuffer里的缓存

**Comment by jinyse** [comment]
> dump出来发现buffer里边Event实例有13332个，总大小达6.8G多.
> 
> <img alt="2018-04-02 15 06 10" width="802" src="https://user-images.githubusercontent.com/3666051/38187214-49f8e2c2-3689-11e8-8d17-9eb2ff6c0cc5.png">
> 
> 起初慢慢增大Xmx到8192m了，修改了pipeline的batchSize,还是会出现OOM。
> 
> 其实应该修改canal的参数(内存存储buffer记录数)。这个默认是32768

这里要设置canal的ringbuffer小一点吗

**Comment by Liushao1** [comment]
怎么设置内存存储buffer记录数啊。我找不到设置的地方
