### ISSUE TITLE
otter SocketTimeoutException

### ISSUE THREAD

**Issue by LeoLiang666** [alibaba/otter#501]
您好，
请问这个exception有什么影响？可以解决吗？谢谢！
pid:1 nid:1 exception:canal:180->132:java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
    at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:90)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:80)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:144)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
    at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
出现之后自动恢复之后就正常了？

**Comment by LeoLiang666** [comment]
就是这个报错好像对同步是没影响的。同步的数据是正常的。

**Comment by LeoLiang666** [comment]
就是晚上数据库跑批的时候 有几十个这样的exception

**Comment by dnfhujun** [comment]
我也是，一直报这么异常，不知道是什么原因引起的，请问找到原因了么？ @agapple

**Comment by guixincui** [comment]
`
pid:4 nid:1 exception:canal:sync-ods-talkplatform-order:java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds. at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:90) at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:80) at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:144) at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) at java.lang.Thread.run(Thread.java:745)
`

**Comment by uang520** [comment]
我也遇到这样的问题，导致部分数据同步存在延迟。。。。
2018-08-30 22:38:37.272 [destination = 10.20.105.57_3307 , address = /10.20.105.57:3307 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.0-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.0-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.0-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:217) [canal.parse-1.1.0-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:248) [canal.parse-1.1.0-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by uang520** [comment]
目前我做了下紧急处理，用了早前版本的NIO版本，测试3-4个小时，没有发生数据延迟的情况，已经发到线上。希望新的版本早点出NIO版本的。

**Comment by beebol** [comment]
也遇到了，上游delete数据，按主键一条条删除，也会报异常。
```
2020-11-26 10:47:36.384 [destination = psystem , address = /10.43.x8.x1:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:90) ~[canal.parse.driver-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:80) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:146) [canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:227) [canal.parse-1.0.26-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2020-11-26 10:47:36.392 [destination = payment_system , address = /10.43.x8.x1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 10.43.x8.x1/10.43.x8.x1:3306 has an error, retrying. caused by
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:90) ~[canal.parse.driver-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:80) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:146) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:227) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2020-11-26 10:47:36.392 [destination = payment_system , address = /10.43.x.x1:3306 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:1[24:canal:payment_system:java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:90)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:80)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:146)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:227)
        at java.lang.Thread.run(Thread.java:745)
]
```

**Comment by beebol** [comment]
确认升级到当前最新版本，也有异常。
```

pid:24 nid:2 exception:canal:payment_system:java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:124)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:169)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:279)
at java.lang.Thread.run(Thread.java:748)
```
