### ISSUE TITLE
show master status成功，但是后续message parser时却报数据库连接超时

### ISSUE THREAD

**Issue by lbj2016** [alibaba/otter#506]
show master status成功，也就是pipeline已经处于工作中状态，但是后续message parser时却报数据库连接超时：
2018-04-09 19:22:59.446 [pipelineId = 1,taskName = SelectTask] WARN  c.a.o.shared.arbitrate.impl.setl.monitor.MainstemMonitor - mainstem is not run any in node
2018-04-09 19:23:00.798 [destination = identity_canal_hangzhou , address = /10.122.188.162:3330 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"10.122.188.162","port":3330}},"postion":{"included":false,"journalName":"mysql-bin.000001","position":273441701,"serverId":7048,"timestamp":1523263722000}}
2018-04-09 19:24:05.611 [pipelineId = 1,taskName = ProcessSelect] ERROR com.alibaba.otter.node.etl.select.SelectTask - [1] selectTask is error!
com.alibaba.otter.node.etl.select.exceptions.SelectException: com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
        at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:211) ~[node.etl-4.2.15.jar:na]
        at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:258) ~[node.etl-4.2.15.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236) [node.etl-4.2.15.jar:na]

**Comment by lbj2016** [comment]
会跟数据库权限有关系吗？一开始show master status也是失败的，后来叫DBA开通了权限就可以了

**Comment by ssyue** [comment]
解决了吗？
