### ISSUE TITLE
明明表存在，确提示找不到表

### ISSUE THREAD

**Issue by guixincui** [alibaba/otter#520]
# **find table [XXX] error**

pid:8 nid:1 exception:setl:com.google.common.collect.ComputationException: org.apache.commons.lang.exception.NestableRuntimeException: find table [talkplatform_course.base_course_class_student_refund] error
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:109)
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect.findTable(AbstractDbDialect.java:113)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:114)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:50)
at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: find table [talkplatform_course.base_course_class_student_refund] error
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$2.apply(AbstractDbDialect.java:188)
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$2.apply(AbstractDbDialect.java:172)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
... 11 more
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: no found table [talkplatform_course.base_course_class_student_refund] , pls check
at com.alibaba.otter.node.etl.common.db.dialect.AbstractDbDialect$2.apply(AbstractDbDialect.java:182)
... 17 more

**Comment by chenyanter** [comment]
检查一下源库和目标库是不是都有这个表存在

**Comment by guixincui** [comment]
@chenyanter 都有的
