### ISSUE TITLE
otter中node挂起，报错信息显示数组越界

### ISSUE THREAD

**Issue by chenggaw** [alibaba/otter#526]
pid:4 nid:1 exception:setl:com.google.common.collect.ComputationException: java.lang.ArrayIndexOutOfBoundsException: 0
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx.getZkClient(ZkClientx.java:34)
    at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.getZkclientx(CanalInstanceWithManager.java:401)
    at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.initMetaManager(CanalInstanceWithManager.java:121)
    at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.(CanalInstanceWithManager.java:76)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1$1.(CanalEmbedSelector.java:139)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1.generate(CanalEmbedSelector.java:139)
    at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:68)
    at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:65)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
    at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
    at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:98)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.start(CanalEmbedSelector.java:206)
    at com.alibaba.otter.node.etl.select.SelectTask.startup(SelectTask.java:170)
    at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:126)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at java.util.Arrays$ArrayList.get(Arrays.java:2866)
    at com.alibaba.otter.canal.common.zookeeper.ZooKeeperx.connect(ZooKeeperx.java:68)
    at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1228)
    at org.I0Itec.zkclient.ZkClient.(ZkClient.java:157)
    at org.I0Itec.zkclient.ZkClient.(ZkClient.java:131)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx.(ZkClientx.java:58)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx.(ZkClientx.java:54)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx.(ZkClientx.java:42)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx.(ZkClientx.java:38)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx$1.apply(ZkClientx.java:29)
    at com.alibaba.otter.canal.common.zookeeper.ZkClientx$1.apply(ZkClientx.java:26)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
    at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
    ... 17 more

**Comment by CodeWangYJ** [comment]
2021年了，有幸重现了这个错误。
