### ISSUE TITLE
源数据库cancal:java.io.IOException: Received error packet: errno = 1236

### ISSUE THREAD

**Issue by ppj19891020** [alibaba/otter#548]
帮忙看下这个是什么原因的？？？错误如下
pid:1 nid:1 exception:canal:源数据库cancal:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Misconfigured master - server_id was not set
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:105)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:146)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:227)
    at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
server_id was not set，mysql数据库需要配置serverId
