### ISSUE TITLE
有位点时间，无定位时间，只能单向同步（Caused by: java.net.ConnectException: Connection timed out）

### ISSUE THREAD

**Issue by leageshine** [alibaba/otter#561]
配置双向同步，其中A-->B是好的，但B-->A不执行同步。
查看pipeline状态，A-->B有位点时间，也有定位时间，正常；但B-->A只有位点时间，没有定位时间。
channel时常挂起，查看pipeline日志，B-->A有异常如下：

pid:15 nid:3 exception:setl:com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory.getDbDialect(DbDialectFactory.java:113)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:99)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:49)
at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:331)
at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory$2$1.apply(DbDialectFactory.java:81)
at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory$2$1.apply(DbDialectFactory.java:76)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
... 13 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
... 17 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
at com.mysql.jdbc.MysqlIO.(MysqlIO.java:338)
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2237)
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270)
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:794)
at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:44)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
... 21 more
Caused by: java.net.ConnectException: Connection timed out
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
at com.mysql.jdbc.MysqlIO.(MysqlIO.java:297)
... 37 more

部署环境：
A上部署ZK，manager，node，canal
B上部署node，canal

主要配置：
NodeA：内网IP：192.168.1.191，外网IP：www.myweb.com，勾选了使用外网IP；
              其中 www.myweb.com在本地解析到192.168.1.191，在外网解析到外网IP（120.22.22.11）；
NodeB：内网IP：172.16.52.24，外网IP：10.12.1.114，勾选了使用外网IP；

CanalA:  数据库地址192.168.1.191:3306;120.22.22.11:23306;
CanalB：数据库地址10.12.1.114:3306；

A上的2181，1099，2088，2089，2090，3306端口开启；防火墙开启；
B上的2088，2089，2090端口开启。防火墙开启；

从现象看，貌似B上连接不到A的mysql，但是在B上telnet 120.22.22.11 3306是好的，telnet www.myweb.com 3306也是好的，其他端口也是好的。
实在想不出是什么原因了。

拜托各位大神帮帮忙啊，这个问题折腾我好几天了。。。。。。。

**Comment by leageshine** [comment]
关键是不清楚，B同步到A时，Node B与Node A通信是用的Node A的外网地址，还是canalA的地址，还是别的什么地方配的地址？

**Comment by leageshine** [comment]
另外，pipeline的配置，B-->A 如下：
Select机器： nodeB;
Load机器：NodeB；
Canal:  canalB;

A-->B 如下：
Select机器： NodeA;
Load机器：NodeA；
Canal:  canalA;

**Comment by leageshine** [comment]
解决了。果然是pipeline设置错了。**Select机器要设置为靠近源节点，Load机器靠近目的节点。**
之前按照一个教程上盲目地设置成了源节点，单向同步竟然可以同步。误导了我，还是对底层原理不理解所致。
