### ISSUE TITLE
4.2.15 node出现无响应状态。

### ISSUE THREAD

**Issue by js1688** [alibaba/otter#568]
大家好!
    部署的otter 在运行了一段时候后，或者说一两天后,会出现一种无响应的状态,这时候无论是在页面上操作停止 还是启动 都会一直卡住, 查看node 列表 显示是已启动,但是我感觉有什么东西停掉了,这个状态不准,每次都需要重启node,才可以继续启动工作,
otter版本是4.2.15 
canal是1.0.25
有谁碰到过这种情况吗

**Comment by js1688** [comment]
2018-07-24 11:54:03.243 [main-SendThread(192.168.3.70:22181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x164c9fec3db0001 for server 192.168.3.70/192.168.3.70:22181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_171]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_171]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_171]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_171]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_171]
