### ISSUE TITLE
Dubbo data length too large

### ISSUE THREAD

**Issue by payonxp** [alibaba/otter#583]
有没有什么方式可以配置dubbo的 max payload? 

2018-08-12 00:00:02.133 [pipelineId = 24,taskName = transformWorker] ERROR c.a.o.s.c.core.impl.DefaultCommunicationClientImpl - call[10.10.100.81:2088] , retry[1]
com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote method: acceptEvent, provider: dubbo://10.10.100.81:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&iothreads=4&lazy=true&serialization=java&threads=50, cause: Data length too large: 8848345, max payload: 8388608, channel: NettyChannel [channel=[id: 0x3ebee14c, /10.10.100.154:39062 => /10.10.100.81:2088]]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:100) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:142) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.dubbo.common.bytecode.proxy1.acceptEvent(proxy1.java) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationConnection.call(DubboCommunicationConnection.java:45) ~[shared.communication-4.2.15.jar:na]
        at com.alibaba.otter.shared.communication.core.impl.DefaultCommunicationClientImpl.call(DefaultCommunicationClientImpl.java:96) ~[shared.communication-4.2.15.jar:na]
        at com.alibaba.otter.node.common.communication.NodeCommmunicationClient.call(NodeCommmunicationClient.java:51) [node.common-4.2.15.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.rpc.RowDataRpcPipe.get(RowDataRpcPipe.java:60) [node.etl-4.2.15.jar:na]
        at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:146) [node.etl-4.2.15.jar:na]
        at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:77) [node.etl-4.2.15.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: com.alibaba.dubbo.remoting.RemotingException: Data length too large: 8848345, max payload: 8388608, channel: NettyChannel [channel=[id: 0x3ebee14c, /10.10.100.154:39062 => /10.10.100.81:2088]]
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:218) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:137) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:111) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95) ~[dubbo-2.5.10-ctrip.2.jar:2.0.1]
        ... 14 common frames omitted

**Comment by agapple** [comment]
你传输模式选择为auto吧,自动会基于大小判断走HTTP还是RPC
