### ISSUE TITLE
rds binlog 一直报这个错 该如何处置

### ISSUE THREAD

**Issue by smfor** [alibaba/otter#604]
pid:1 nid:1 exception:canal:canaltest_dev:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252)
    at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
binlog被删除，重置一下位点

**Comment by smfor** [comment]
我是重新建了个canal，可以了。重置位点我一直报找不到start position 是为什么，是我写的格式错了么

**Comment by agapple** [comment]
新的报错是啥

**Comment by funyule** [comment]
重新定位Binlog就能解决这个问题

**Comment by funyule** [comment]
我遇到的是 binlog刷新太快时，就假死了，而且 node节点cpu异常飙高，最终拖死node。加上有没有Node高可用，最后同步停止

**Comment by clixiang** [comment]
去哪里找到位点进行重置？

**Comment by xmapst** [comment]
> 我是重新建了个canal，可以了。重置位点我一直报找不到start position 是为什么，是我写的格式错了么

nice, Just great!!!!!
