### ISSUE TITLE
Timeout occurred, failed to read xxx in 25000 milliseconds.

### ISSUE THREAD

**Issue by qiunan92** [alibaba/otter#625]
现象：升级到4.2.16版本运行一段时间后，某个Channel突然报超时挂掉，Pipeline的mainstem状态在定位中与工作中来回切换。即使在工作中状态，吞吐量也为0。

操作：检查数据源网络及数据库均无问题后，修改Pipeline超时时间、chanal默认超时时间均无效，同时发现修改chanal默认超时时间后，查看chanal信息时，页面没加载默认超时时间。

希望能给出帮助定位问题，跪谢

报错信息如下：java.net.SocketTimeoutException: Timeout occurred, failed to read 8175 bytes in 25000 milliseconds.
at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252)
at java.lang.Thread.run(Thread.java:748)

**Comment by zhengwang-qtl** [comment]
@qiunan92  hello, 请问是怎么解决的呢？ 我也遇到这个问题了！

**Comment by qiunan92** [comment]
> @qiunan92 hello, 请问是怎么解决的呢？ 我也遇到这个问题了！

mysql的大事务引起的，node在处理大事务的时候，处理时间超过了异常监控的时间，manager认为node失去了响应，然后切换node来处理。我的处理方法是把manager的监控都关闭，让node跑完这个大事务就好了
