### ISSUE TITLE
GTID问题

### ISSUE THREAD

**Issue by javahun** [alibaba/otter#635]
如下异常如何处理
pid:8 nid:1 exception:canal:canal1027:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:185)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:260)
at java.lang.Thread.run(Thread.java:748)

**Comment by SwaggyQ** [comment]
解决办法:在你zk中的/otter/canal/destination/xx/xx/cursor中，配置你的gtid set

**Comment by f-zhao** [comment]
顶楼上
