### ISSUE TITLE
单表Pipeline管理->日志记录报错

### ISSUE THREAD

**Issue by shubiao-yao** [alibaba/otter#643]
数据单向同步日志记录中报错：
![image](https://user-images.githubusercontent.com/32409300/48464049-09244b00-e819-11e8-857a-3710e8b6043a.png)

求大神指点。

报错信息如下：

pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.alibaba.otter.node.etl.select.exceptions.SelectException: this rowdata has no pks , entry: header {
version: 1
logfileName: "mysql-bin.000005"
logfileOffset: 35321
serverId: 1
serverenCode: "UTF-8"
executeTime: 1542176173000
sourceType: MYSQL
schemaName: "test"
tableName: "user"
eventLength: 48
eventType: INSERT
props {
key: "rowsCount"
value: "1"
}
}
entryType: ROWDATA
storeValue: "\bn\020\001P\000bF\022\034\b\000\020\004\032\002id \000(\0010\000B\003212R\aint(11)\022&\b\001\020\f\032\004name \000(\0010\000B\ahahahahR\vvarchar(50)"
and rowData: afterColumns {
index: 0
sqlType: 4
name: "id"
isKey: false
updated: true
isNull: false
value: "212"
mysqlType: "int(11)"
}
afterColumns {
index: 1
sqlType: 12
name: "name"
isKey: false
updated: true
isNull: false
value: "hahahah"
mysqlType: "varchar(50)"
}

at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:212)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:278)
at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.otter.node.etl.select.exceptions.SelectException: this rowdata has no pks , entry: header {
version: 1
logfileName: "mysql-bin.000005"
logfileOffset: 35321
serverId: 1
serverenCode: "UTF-8"
executeTime: 1542176173000
sourceType: MYSQL
schemaName: "test"
tableName: "user"
eventLength: 48
eventType: INSERT
props {
key: "rowsCount"
value: "1"
}
}
entryType: ROWDATA
storeValue: "\bn\020\001P\000bF\022\034\b\000\020\004\032\002id \000(\0010\000B\003212R\aint(11)\022&\b\001\020\f\032\004name \000(\0010\000B\ahahahahR\vvarchar(50)"
and rowData: afterColumns {
index: 0
sqlType: 4
name: "id"
isKey: false
updated: true
isNull: false
value: "212"
mysqlType: "int(11)"
}
afterColumns {
index: 1
sqlType: 12
name: "name"
isKey: false
updated: true
isNull: false
value: "hahahah"
mysqlType: "varchar(50)"
}

at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:585)
at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:391)
at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:142)
... 9 more

![image](https://user-images.githubusercontent.com/32409300/48463927-a92da480-e818-11e8-9396-855bd781d188.png)

![image](https://user-images.githubusercontent.com/32409300/48463940-b480d000-e818-11e8-9d31-ec0616896cc2.png)
Channel信息：
![image](https://user-images.githubusercontent.com/32409300/48463956-c4001900-e818-11e8-89f2-e6e7b5334f76.png)

**Comment by shubiao-yao** [comment]
问题已解决，我这导致这个问题的原因是两张表都没设置主键。我把主键加上就可以了
