### ISSUE TITLE
4.2.14升级4.2.16节点无法同步

### ISSUE THREAD

**Issue by qinly** [alibaba/otter#651]
错误信息：

```
Error When doing Register slave:ErrorPacket [errorNumber=1105, fieldCount=-1, message=Failed to register slave; too long 'report-password', sqlState=HY000, sqlStateMarker=#]
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.sendRegisterSlave(MysqlConnection.java:287)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:148)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by agapple** [comment]
Failed to register slave; too long 'report-password'，mysql的报错
