### ISSUE TITLE
ddl操作导致pipleline一直报错

### ISSUE THREAD

**Issue by hobo212** [alibaba/otter#657]
进行ddl操作,加了一个索引
ALTER TABLE `a`.`b` 
ADD INDEX `c` (`d` ASC);
就一直报错:
pid:6 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.NullPointerException
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:211)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:308)
    at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
    at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
    at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
    at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:380)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:183)
    ... 9 more

**Comment by junjie-tang99** [comment]
你这张表上，是不是没有加主键？
