### ISSUE TITLE
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.IllegalArgumentException: No enum constant com.alibaba.otter.shared.etl.model.EventType.XACOMMIT

### ISSUE THREAD

**Issue by puper** [alibaba/otter#658]
同步挂起，是这个常量不存在么

pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.IllegalArgumentException: No enum constant com.alibaba.otter.shared.etl.model.EventType.XACOMMIT
	at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:212)
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:278)
	at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
	at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
	at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No enum constant com.alibaba.otter.shared.etl.model.EventType.XACOMMIT
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.alibaba.otter.shared.etl.model.EventType.valueOf(EventType.java:24)
	at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:333)
	at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:142)
	... 9 more

**Comment by agapple** [comment]
目前不支持mysql XA事务的同步

**Comment by puper** [comment]
没有使用, 这种错误怎么跳过呢

**Comment by deyehorse** [comment]
请问现在能支持xa事务了吗?

**Comment by czxin788** [comment]
我也遇到了这个问题，请问怎么跳过呢
