### ISSUE TITLE
SocketTimeoutException异常，每隔一分钟就出一个，但是同步没有问题

### ISSUE THREAD

**Issue by vinnie888** [alibaba/otter#677]
![image](https://user-images.githubusercontent.com/16188007/49998676-df08a900-ffcf-11e8-9f03-92306fb01c81.png)
pid:3 nid:1 exception:canal:ytz_feiqiu:java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:124)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:159)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
at java.lang.Thread.run(Thread.java:748)

日志记录里面每分钟都会又这个异常，但是同步也没有问题，都能正常同步数据，
用的是docker，数据源是mysql 5.1.73，
另一个数据源mysql 5.6.42的就没有这个问题，
请问
这个异常跟数据库版本有关系吗？
该从哪里调查希望能给个提示

**Comment by bh-sky** [comment]
同问

**Comment by liulangwa** [comment]
我也遇到同样的报错，但是数据没法同步，一直提示定位中

**Comment by vinnie888** [comment]
参考 [canal #951](https://github.com/alibaba/canal/issues/951)
我觉得是一样的，数据源是5.1.73时的问题，
数据源也不能升级到更高的版本，但是不断的出这个错误日志也是太讨厌了，
曲线救国，弄了个表，建了一个event，每隔20秒更新一下，现在就看不到这个异常了，
我想这样基本上没增加什么负担，长期应该也没什么问题吧，
如果各位大侠有更好的处理办法请指教

**Comment by jsonchina** [comment]
同问啊 最新版也是这样的

**Comment by hanzixiaoshu** [comment]
这个问题各位解决了吗？

pid:1 nid:1 exception:canal:canaltest:java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:124)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:159)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
可参考 vinnie888 的做法，在mysql库上定时产生心跳. 

产生这个异常的本质，mysql在25秒内都没有任何binlog事件，canal等了25秒没有任何消息就会出现类似的错误，mysql新版本针对无消息时引入了heartbeat事件，也有同学发现mysql并不是准时按照masterheart设置的时间发心跳包，经常会超过2个轮询才会发心跳包，即30s+

**Comment by enclairfarron** [comment]
@vinnie888 按你这个方法尝试了一下 发现这个错误数量减少了 但是依然会存在 设置的是10s更新一下数据 错误每隔4小时到6小时会发生几次 请问还有什么别的细节么

**Comment by vinnie888** [comment]
@enclairfarron 没有别的了 agapple也解释过了 我的方法就是让数据源定时产生binlog 如果还有问题应该是其它的原因了吧

**Comment by wojiaoliuhao** [comment]
我这边也出现这个问题了，不过是一关闭同步任务A，任务B、C等等就会报出错误。
