### ISSUE TITLE
JmxConnectorServerFactoryBean 客户端无法获取JMXserver连接

### ISSUE THREAD

**Issue by HackerRookie** [alibaba/otter#690]
JmxConnectorServerFactoryBean 中service:jmx:rmi://127.0.0.1:{0}/jndi/rmi://127.0.0.1:{0}/mbean..导致jmx client 服务获取连接 报异常

Caused by: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source)
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at com.alibaba.otter.manager.biz.remote.impl.NodeMBeanServiceImpl$1.apply(NodeMBeanServiceImpl.java:76)
	... 67 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 75 more

**Comment by kaikai2000** [comment]
参考下面步骤设置 http://note.youdao.com/noteshare?id=ab70fb625f63ba170a96b57dc828c303&sub=1C94FFCBEF4344A9B5CDD9425B1DE369

**Comment by HackerRookie** [comment]
> 参考下面步骤设置 http://note.youdao.com/noteshare?id=ab70fb625f63ba170a96b57dc828c303&sub=1C94FFCBEF4344A9B5CDD9425B1DE369

这个是解决方法有点复杂..能不能改成JmxConnectorServerFactoryBean 中service:jmx:rmi://{ip}:{port}/jndi/rmi://{ip}:{port}/mbean..这样是不是就不用在服务器端修改host配置
