### ISSUE TITLE
otter4.2.17在解析日志时报错(mysql数据库版本为5.7.3-m13)

### ISSUE THREAD

**Issue by foreveri7** [alibaba/otter#691]
解析日志报错如下：
pid:20 nid:8 exception:canal:canal-mideast:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Slave can not handle replication events with the checksum that master is configured to log; the first event 'mysql-bin.000003' at 887181, the last event read from '.\mysql-bin.000003' at 120, the last byte read from '.\mysql-bin.000003' at 120. 
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) 
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:154) 
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266) 
at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
Slave can not handle replication events with the checksum that master is configured to log; the first event 'mysql-bin.000003' at 887181, the last event read from '.\mysql-bin.000003' at 120, the last byte read from '.\mysql-bin.000003' at 120.
