### ISSUE TITLE
添加EventProcessor后报ClassNotFoundException

### ISSUE THREAD

**Issue by liuyikun** [alibaba/otter#732]
现象比较奇怪，有时save 后没有exception 正常工作，有时改了save后却报异常，请问下是什么问题啊？有尝试 restart container，仍没有效果。
谢谢

pid:1 nid:1 exception:setl:com.alibaba.otter.shared.common.utils.compile.exception.CompileExprException: compile error, source : 
.TestEventProcessor, []
    at com.alibaba.otter.shared.common.utils.compile.impl.JdkCompiler.compile(JdkCompiler.java:58)
    at com.alibaba.otter.shared.common.utils.extension.DefaultExtensionFactory.getExtensionInternal(DefaultExtensionFactory.java:63)
    at com.alibaba.otter.shared.common.utils.extension.DefaultExtensionFactory.access$000(DefaultExtensionFactory.java:33)
    at com.alibaba.otter.shared.common.utils.extension.DefaultExtensionFactory$1.apply(DefaultExtensionFactory.java:44)
    at com.alibaba.otter.shared.common.utils.extension.DefaultExtensionFactory$1.apply(DefaultExtensionFactory.java:41)
    at com.alibaba.otter.shared.common.utils.cache.ExtensionMemoryMirror.get(ExtensionMemoryMirror.java:65)
    at com.alibaba.otter.shared.common.utils.extension.DefaultExtensionFactory.getExtension(DefaultExtensionFactory.java:50)
    at com.alibaba.otter.node.etl.extract.extractor.ProcessorExtractor.extract(ProcessorExtractor.java:81)
    at com.alibaba.otter.node.etl.extract.extractor.ProcessorExtractor.extract(ProcessorExtractor.java:51)
    at com.alibaba.otter.node.etl.extract.extractor.OtterExtractorFactory.extract(OtterExtractorFactory.java:50)
    at com.alibaba.otter.node.etl.extract.ExtractTask$1.run(ExtractTask.java:79)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.otter.shared.common.utils.compile.exception.JdkCompileException: java.lang.ClassNotFoundException: .TestEventProcessor
    at com.alibaba.otter.shared.common.utils.compile.impl.JdkCompileTask.compile(JdkCompileTask.java:153)
    at com.alibaba.otter.shared.common.utils.compile.impl.JdkCompileTask.compile(JdkCompileTask.java:109)
    at com.alibaba.otter.shared.common.utils.compile.impl.JdkCompiler.compile(JdkCompiler.java:53)
    ... 15 more
**Caused by: java.lang.ClassNotFoundException: .TestEventProcessor**
    at java.lang.ClassLoader.findClass(ClassLoader.java:530)
    at com.alibaba.otter.shared.common.utils.compile.model.JdkCompilerClassLoader.findClass(JdkCompilerClassLoader.java:67)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at com.alibaba.otter.shared.common.utils.compile.model.JdkCompilerClassLoader.loadClass(JdkCompilerClassLoader.java:88)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.alibaba.otter.shared.common.utils.compile.impl.JdkCompileTask.loadClass(JdkCompileTask.java:162)
    at com.alibaba.otter.shared.common.utils.compile.impl.JdkCompileTask.compile(JdkCompileTask.java:147)
    ... 17 more

**Comment by agapple** [comment]
Caused by: java.lang.ClassNotFoundException: .TestEventProcessor
at java.lang.ClassLoader.findClass(ClassLoader.java:530)

检查一下扩展类，看看是否可以编译通过
