### ISSUE TITLE
同步异常

### ISSUE THREAD

**Issue by ericlijm** [alibaba/otter#74]
配置了 一个双向同步的channel，数据库都是mysql的 ，刚开始从 a 到 b，从b到a 的pipeline都 可以正常同步，后来发现从b 到 a 的 pipeline 不能正常同步了(从a到b的pipeline还可以正常同步)，有如下异常信息：
jio.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:78)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:116)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)
]，

尝试过重启 channel，重启node应用，之后还是抛同样的异常信息，能帮忙解答一下吗？谢谢！

**Comment by agapple** [comment]
Connection reset by peer.  是被mysql主动关闭链接的异常
