### ISSUE TITLE
双向同步，一段时间没有数据同步，channel挂起，mainsteam和pipeline状态正常，position状态没有更新，求解答

### ISSUE THREAD

**Issue by stickmanth** [alibaba/otter#746]
pid:2 nid:2 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.alibaba.otter.node.etl.select.exceptions.SelectException: this rowdata has no pks , entry: header {
version: 1
logfileName: "mysql-bin.000180"
logfileOffset: 36354060
serverId: 2
serverenCode: "UTF-8"
executeTime: 1554235662000
sourceType: MYSQL
schemaName: "mysql"
tableName: "yongger2"
eventLength: 40
eventType: INSERT
props {
key: "rowsCount"
value: "1"
}
}
entryType: ROWDATA
storeValue: "\b\356\002\020\001P\000b\037\022\035\b\000\020\324\017\032\004data \000(\0010\000B\000R\bLONGBLOB"
and rowData: afterColumns {
index: 0
sqlType: 2004
name: "data"
isKey: false
updated: true
isNull: false
value: ""
mysqlType: "LONGBLOB"
}

at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:212)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:278)
at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.otter.node.etl.select.exceptions.SelectException: this rowdata has no pks , entry: header {
version: 1
logfileName: "mysql-bin.000180"
logfileOffset: 36354060
serverId: 2
serverenCode: "UTF-8"
executeTime: 1554235662000
sourceType: MYSQL
schemaName: "mysql"
tableName: "yongger2"
eventLength: 40
eventType: INSERT
props {
key: "rowsCount"
value: "1"
}
}
entryType: ROWDATA
storeValue: "\b\356\002\020\001P\000b\037\022\035\b\000\020\324\017\032\004data \000(\0010\000B\000R\bLONGBLOB"
and rowData: afterColumns {
index: 0
sqlType: 2004
name: "data"
isKey: false
updated: true
isNull: false
value: ""
mysqlType: "LONGBLOB"
}

at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:585)
at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:391)
at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:142)
... 9 more

**Comment by stickmanth** [comment]
截图应该是位点信息没有更新导致的

**Comment by xuyixiuge** [comment]
表没有加主键

**Comment by agapple** [comment]
this rowdata has no pks
