### ISSUE TITLE
update语法 select阶段获取的字段不是全部字段，导致load阶段报错

### ISSUE THREAD

**Issue by ppj19891020** [alibaba/otter#757]
1.otter版本：4.2.17版本 
2.sql为更新语句：update push_message2 set `status` = "update" where traceId =1057206508440159962; 
3.node select阶段eventdata发现更新字段只有2个，导致load阶段生成sql语句报错

备注：我们是用jmeter跑1个线程，每次有insert操作，50%概率会做update操作，50%概率做删除操作，每次操作会延时1s，半夜突然出现这个现象。

node error log
```
- PairId: 40 , TableId: 10 , EventType : U , Time : 1555372497000
- Consistency : M , Mode :
-----------------
---Pks
	EventColumn[index=0,columnType=-5,columnName=id,columnValue=1057206508440159962,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
	EventColumn[index=4,columnType=12,columnName=status,columnValue=update,isNull=false,isKey=false,isUpdate=true]
	EventColumn[index=12,columnType=93,columnName=modifyTime,columnValue=2019-04-16 07:54:57,isNull=false,isKey=false,isUpdate=true]
	EventColumn[index=0,columnType=0,columnName=traceId,columnValue=<null>,isNull=true,isKey=false,isUpdate=true]
	EventColumn[index=0,columnType=0,columnName=userId,columnValue=<null>,isNull=true,isKey=false,isUpdate=true]
	EventColumn[index=0,columnType=0,columnName=createTime,columnValue=<null>,isNull=true,isKey=false,isUpdate=true]
---Sql
	update `otter1`.`message_0` set  `status` = ? , `modifyTime` = ? , `traceId` = ? , `userId` = ? , `createTime` = ?  where ( `id` = ? )

2019-04-16 10:36:15.027 [pipelineId = 20,taskName = LoadWorker] ERROR com.alibaba.otter.node.etl.load.LoadTask - [20] loadWork executor is error! data:EtlEventData[currNid=2,nextNid=2,desc=[MemoryPipeKey[identity=Identity[channelId=22,pipelineId=20,processId=517702],time=1555382153881,dataType=DB_BATCH]],processId=517702,startTime=1555382153398,endTime=<null>,firstTime=1555372203000,batchId=524679,number=4327,size=<null>,exts=<null>,pipelineId=20]
com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update `otter1`.`message_0` set  `status` = ? , `modifyTime` = ? , `traceId` = ? , `userId` = ? , `createTime` = ?  where ( `id` = ? )]; Column 'traceId' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'traceId' cannot be null
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
```

**Comment by ppj19891020** [comment]
已找到原因，是message解析的时候，update只去查修改后的值，可以通过  同步模式配置行模式即可
