### ISSUE TITLE
ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by ghqaz3633** [alibaba/otter#76]
manager日志中报如下错误：
pid:49 nid:8 exception:canal:cn8:com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.ArrayIndexOutOfBoundsException: 0
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parseTableName(SimpleDdlParser.java:163)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parseDdl(SimpleDdlParser.java:115)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parse(SimpleDdlParser.java:80)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:150)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:99)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:323)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:124)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
    at java.lang.Thread.run(Thread.java:745)
#################
查看node日志：
2015-04-28 09:36:30.977 [destination = 8 , address = /***.***.***.***:*** , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address  /***.***.***.***:*** has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.ArrayIndexOutOfBoundsException: 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parseTableName(SimpleDdlParser.java:163) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parseDdl(SimpleDdlParser.java:115) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parse(SimpleDdlParser.java:80) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:150) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:99) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:323) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:124) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.19.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

**Comment by agapple** [comment]
请提供ddl解析出错的SQL文本，可以通过show binlog events in 'xxxx' from xx来获取

**Comment by ghqaz3633** [comment]
SQL比较长（110行），是关于存储过程的：
use `sc***1`;
CREATE DEFINER=`sc***me`@`%` PROCEDURE `SC_CORE_NODE_SAVE`(IN sc***mePassportId CHAR(32), INOUT nodeId CHAR(32), IN nodeName VARCHAR(255), IN nodeType VARCHAR(255), IN columnId CHAR(32), IN title VARCHAR(512), IN browse TINYINT(1), IN `comment` TINYINT(1), IN promote TINYINT(1), IN moderate TINYINT(1), IN sticky TINYINT(1), IN translate TINYINT(1), IN nodePartNames LONGTEXT, IN nodePartTitles LONGTEXT, IN sequences LONGTEXT, IN keywords LONGTEXT, IN tags LONGTEXT, IN contents LONGTEXT, IN langCode VARCHAR(200), OUT success INT,OUT info VARCHAR(128))
BEGIN
	SET @timeNow = NOW();
	IF nodeId IS NULL OR nodeId='' THEN
		SET @nodeId = NULL;
		SET @columnNodeId=UUID32();
		SELECT node.`ID` INTO @nodeId FROM `sc_core_node` node WHERE node.`NAME` = nodeName AND node.`TYPE`=nodeType LIMIT 1;
		IF @nodeId IS NULL THEN
			SET @nodeId=UUID32();
			INSERT INTO `sc_core_node` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `NAME`, `TYPE`, `REVISION_ID`, `AUTHOR`, `BROWSE`, `COMMENT`, `PROMOTE`, `MODERATE`, `STICKY`, `TRANSLATE`, `DISABLED`)
				VALUES (@nodeId, sc***mePassportId, @timeNow, sc***mePassportId, @timeNow, nodeName, nodeType, NULL, sc***mePassportId, browse, `comment`, promote, moderate, sticky, translate, 0);
			
			IF columnId IS NOT NULL AND columnId<>'' THEN
				INSERT INTO `sc_col_column_node` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `NODE_ID`, `COLUMN_ID`)
					VALUES (@columnNodeId, sc***mePassportId, @timeNow, sc***mePassportId, @timeNow, @nodeId, columnId);
			END IF;
		ELSE
			UPDATE `sc_core_node` SET `UPDATE_BY` = sc***mePassportId, `UPDATE_TIME` = @timeNow, `NAME` = nodeName, `REVISION_ID` = NULL, `AUTHOR` = sc***mePassportId, `BROWSE` = browse, `COMMENT` = `comment`, `PROMOTE` = promote, `MODERATE` = moderate, `STICKY` = sticky, `TRANSLATE` = translate WHERE `ID` = @nodeId;
		END IF;
		CALL SC_RES_RESOURCE_SAVE('sc_core_node', @nodeId, 'TITLE', langCode, title);
	ELSE
		SET @nodeId = nodeId;
		UPDATE `sc_core_node` SET `UPDATE_BY` = sc***mePassportId, `UPDATE_TIME` = @timeNow, `NAME` = nodeName, `REVISION_ID` = NULL, `AUTHOR` = sc***mePassportId, `BROWSE` = browse, `COMMENT` = `comment`, `PROMOTE` = promote, `MODERATE` = moderate, `STICKY` = sticky, `TRANSLATE` = translate WHERE `ID` = @nodeId;
		CALL SC_RES_RESOURCE_SAVE('sc_core_node', @nodeId, 'TITLE', langCode, title);
		
		
		DELETE FROM `sc_kwd_node_keyword` WHERE `NODE_ID` = nodeId;
	END IF;
	SET @numbers=0;
	IF keywords IS NOT NULL THEN
		SET @i=1;
		SET @numbers = FN_GET_ELEMENTS_COUNT(keywords, '|');
		WHILE @i <= @numbers DO
			SET @keyword = FN_FIND_ELEMENT_BYINDEX(keywords, '|', @i);
			SET @keywordId = NULL;
			SELECT nodeKeyword.`ID` INTO @keywordId FROM `sc_kwd_keyword` nodeKeyword WHERE nodeKeyword.`ID` = @keyword;
			IF @keywordId IS NOT NULL THEN
				SET @nodeKeywordId = UUID32();
				INSERT INTO `sc_kwd_node_keyword` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `KEYWORD_ID`, `NODE_ID`)
					VALUES(@nodeKeywordId, sc***mePassportId, @timeNow, sc***mePassportId, @timeNow, @keywordId, @nodeId);
			END IF;
			SET @i = @i + 1;
		END WHILE;
	END IF;
	IF tags IS NOT NULL THEN
		SET @i=1;
		SET @numbers = FN_GET_ELEMENTS_COUNT(tags, '|');
		WHILE @i <= @numbers DO
			SET @tag = FN_FIND_ELEMENT_BYINDEX(tags, '|', @i);
			SET @tagId = NULL;
			SELECT nodeTag.`ID` INTO @tagId FROM `sc_kwd_keyword` nodeTag WHERE nodeTag.`ID` = @tag;
			IF @tagId IS NOT NULL THEN
				SET @nodeTagId = UUID32();
				INSERT INTO `sc_kwd_node_keyword` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `KEYWORD_ID`, `NODE_ID`)
					VALUES(@nodeTagId, sc***mePassportId, @timeNow, sc***mePassportId, @timeNow, @tagId, @nodeId);
			END IF;
			SET @i = @i + 1;
		END WHILE;
	END IF;
	IF contents IS NOT NULL THEN
		SET @i=1;
		SET @numbers = FN_GET_ELEMENTS_COUNT(contents,'<part>');
		SET @nodePartNameStr = '';
		WHILE @i <= @numbers DO
			SET @content = FN_FIND_ELEMENT_BYINDEX(contents,'<part>',@i);
			IF nodePartNames IS NULL THEN
				SET @nodePartName = @i;
			ELSE
				SET @nodePartName = FN_FIND_ELEMENT_BYINDEX(nodePartNames,'<part>',@i);
			END IF;
			SET @nodePartNameStr = CONCAT(@nodePartNameStr,',\'',@nodePartName,'\'');
			IF nodePartTitles IS NULL THEN
				SET @nodePartTitle = title;
			ELSE
				SET @nodePartTitle = FN_FIND_ELEMENT_BYINDEX(nodePartTitles,'<part>',@i);
			END IF;
			IF sequences IS NULL THEN
				SET @sequence = 0;
			ELSE
				SET @sequence = FN_FIND_ELEMENT_BYINDEX(sequences,'<part>',@i);
			END IF;
			SET @content = FN_FIND_ELEMENT_BYINDEX(contents,'<part>',@i);
						
			SELECT COUNT(nodePart.ID) INTO @nodePartNum FROM sc_core_node_part nodePart WHERE nodePart.PART_NAME=@nodePartName AND nodePart.NODE_ID=@nodeId;
			IF @nodePartNum<1 THEN
				SET @nodePartId = UUID32();
				INSERT INTO `sc_core_node_part` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `PART_NAME`, `REVISION_ID`, `AUTHOR`, `NODE_ID`, `SEQUENCE`, `DISABLED`)
					VALUES(@nodePartId, sc***mePassportId, @timeNow, sc***mePassportId, @timeNow, @nodePartName, NULL, sc***mePassportId, @nodeId, @sequence, 0);
			ELSE
				SELECT nodePart.ID INTO @nodePartId FROM sc_core_node_part nodePart WHERE nodePart.PART_NAME=@nodePartName AND nodePart.NODE_ID=@nodeId;
			END IF;	
			CALL SC_RES_RESOURCE_SAVE('sc_core_node_part', @nodePartId, 'TITLE', langCode, @nodePartTitle);
			CALL SC_RES_RESOURCE_SAVE('sc_core_node_part', @nodePartId, 'CONTENT', langCode, @content);
			SET @i = @i + 1;
		END WHILE;
		IF CHAR_LENGTH(@nodePartNameStr)>0 THEN
			SET @nodePartNameStr = SUBSTRING(@nodePartNameStr,2);
		ELSE
			SET @nodePartNameStr = '\'\'';
		END IF;
		SET @listPost=CONCAT('DELETE FROM sc_core_node_part WHERE NODE_ID=? AND PART_NAME NOT IN (',@nodePartNameStr,')');
		PREPARE _stmt FROM @listPost;
		EXECUTE _stmt USING @nodeId;
		DEALLOCATE PREPARE _stmt;
		
	END IF;
	SET nodeId=@nodeId;
	SET success = 1;
    END

**Comment by ghqaz3633** [comment]
目前是在生产环境出现这个问题，能否先提供一个解决方法，先谢谢大神了

**Comment by agapple** [comment]
可以重置解析位点，跳到出错日志的下一个事务begin位点

**Comment by ghqaz3633** [comment]
跳到出错日志的下一个事务begin位点,报然包同样的错误

**Comment by agapple** [comment]
1. 重置位点可能没成功
2. 下个位点还有同样sql语句

**Comment by agapple** [comment]
see issue : https://github.com/alibaba/canal/issues/116

**Comment by ghqaz3633** [comment]
位点我已经试过好几个了，还是问题依旧，但是SQL确实都差不多，而且也比较长。
目前是主从出问题，为了保证数据一致，我计划将主库上的数据备份在从库上恢复，重新配置otter。

**Comment by agapple** [comment]
代码已经提交，可以重新本地打包下canal和otter

在 2015年4月30日 下午12:37，ghqaz3633 <notifications@github.com>写道：

**Comment by ghqaz3633** [comment]
现在又报错了：一下为报错日志：
pid:59 nid:8 exception:canal:cn87canal-->84:com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: SimpleDdlParser process query failed. pls submit issue with this queryString: CREATE DEFINER=`sco*erce`@`%` PROCEDURE `SC_CPN_CODES_SAVE_ACTION`(IN cosmosPassportId CHAR(32), IN orderId CHAR(32), IN codeIds TEXT)
BEGIN
SET @orderId = orderId;
SET @timeNow = NOW();
START TRANSACTION;
DELETE FROM `sc_ord_coupon` WHERE `ORDER_ID` = @orderId;
SET @i=1;
SET @numbers = FN_GET_ELEMENTS_COUNT(codeIds, '|');
WHILE @i <= @numbers DO
    SET @codeId = FN_FIND_ELEMENT_BYINDEX(codeIds, '|', @i);
    SET @orderCodeId = UUID32();
    INSERT INTO `sc_ord_coupon` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `ORDER_ID`, `CODE_ID`)
        VALUES(@orderCodeId, cosmosPassportId, @timeNow, cosmosPassportId, @timeNow, @orderId, @codeId);
    SET @i = @i + 1;
END WHILE;
COMMIT;
END , and DdlResult: DdlResult [schemaName=scm**801, tableName=null, oriSchemaName=null, oriTableName=null, type=CINDEX]
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: SimpleDdlParser process query failed. pls submit issue with this queryString: CREATE DEFINER=`sco**ce`@`%` PROCEDURE `SC_CPN_CODES_SAVE_ACTION`(IN cosmosPassportId CHAR(32), IN orderId CHAR(32), IN codeIds TEXT)
BEGIN
SET @orderId = orderId;
SET @timeNow = NOW();
START TRANSACTION;
DELETE FROM `sc_ord_coupon` WHERE `ORDER_ID` = @orderId;
SET @i=1;
SET @numbers = FN_GET_ELEMENTS_COUNT(codeIds, '|');
WHILE @i <= @numbers DO
    SET @codeId = FN_FIND_ELEMENT_BYINDEX(codeIds, '|', @i);
    SET @orderCodeId = UUID32();
    INSERT INTO `sc_ord_coupon` (`ID`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `ORDER_ID`, `CODE_ID`)
        VALUES(@orderCodeId, cosmosPassportId, @timeNow, cosmosPassportId, @timeNow, @orderId, @codeId);
    SET @i = @i + 1;
END WHILE;
COMMIT;
END , and DdlResult: DdlResult [schemaName=sc***1, tableName=null, oriSchemaName=null, oriTableName=null, type=CINDEX]

**Comment by agapple** [comment]
see issue : alibaba/canal#116
