### ISSUE TITLE
IndexOutOfBoundsException: Index: 0

### ISSUE THREAD

**Issue by lichi6174** [alibaba/otter#771]
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.IndexOutOfBoundsException: Index: 0
at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:212)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:278)
at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454)
at com.alibaba.otter.canal.protocol.CanalEntry$RowChange.getRowDatas(CanalEntry.java:8189)
at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:110)
... 9 more

###
channel一直挂起，报错日志如上，该怎么处理呢！

**Comment by yanghongkjxy** [comment]
遇到同样问题了，用的v4.1.17,在v4.1.14上正常

**Comment by yanghongkjxy** [comment]
2019-05-22 09:17:31.066 [destination = xxxy , address = /xxx , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.004515,position=677276492,serverId=<null>,gtid=<null>,timestamp=<null>] cost : 18ms , the next step is binlog dump
2019-05-22 09:17:31.476 [pipelineId = 41,taskName = ProcessSelect] ERROR com.alibaba.otter.node.etl.select.SelectTask - [41] selectTask is error!
com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.IndexOutOfBoundsException: Index: 0
        at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:212) ~[node.etl-4.2.17.jar:na]
        at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:278) ~[node.etl-4.2.17.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236) [node.etl-4.2.17.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94) [node.etl-4.2.17.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208) [node.etl-4.2.17.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4454) ~[na:1.8.0_45]
        at com.alibaba.otter.canal.protocol.CanalEntry$RowChange.getRowDatas(CanalEntry.java:8189) ~[canal.protocol-1.1.2.jar:na]
        at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:110) ~[node.etl-4.2.17.jar:na]

**Comment by yanghongkjxy** [comment]
https://github.com/alibaba/otter/issues/650  这个有解决方案

**Comment by jdj199222** [comment]
node/etl/src/main/java/com/alibaba/otter/node/etl/select/selector/MessageParser.java
最新版已经修复了,替换旧版源码,重新打包就行了
