### ISSUE TITLE
mysql 5.7.3-m13-log向mysql 5.7.11-log同步Read Q_FLAGS2_CODE error: limit excceed: 76

### ISSUE THREAD

**Issue by dreamofkevin** [alibaba/otter#776]
注：源库与目标库均为新建立的schema. 
pid:1 nid:2 exception:canal:192.168.1.118:java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 76
    at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:717)
    at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.(QueryLogEvent.java:495)
    at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
    at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:162)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: limit excceed: 76
    at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:562)
    at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:612)
    ... 6 more

**Comment by agapple** [comment]
对应的otter和canal是什么版本？应该是binlog协议格式解析失败，先升级到最新版本看看
