### ISSUE TITLE
下载错误download_error

### ISSUE THREAD

**Issue by ghqaz3633** [alibaba/otter#78]
报错日志：
pid:9 nid:1 exception:setl:com.alibaba.otter.node.etl.common.pipe.exception.PipeException: download_error
Caused by: com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: aborted for some configration error.

**Comment by agapple** [comment]
到node机器上看具体的日志，确认下aria2c是否安装成功+可用

**Comment by ghqaz3633** [comment]
aria2c是没有问题的，该问题会导致同步停止，重启node节点后恢复正常，但一段时间后又会出现该报错，同步的数据量大的时候经常出现。具体环境：中美异地机房，双写。

**Comment by ghqaz3633** [comment]
报错日志如下，：
2015-05-11 03:54:33.022 [pipelineId = 1,taskName = transformWorker] ERROR com.alibaba.otter.node.etl.transform.TransformTask - [1] transformWork executor is error! data:EtlEventData[currNid=3,nextNid=10,desc=[HttpPipeKey[identity=Identity[channelId=2,pipelineId=1,processId=15316],crc=<null>,key=<null>,url=http://192.168.193.87:9090/download/DbBatch-2015-05-11-11-49-48-2-1-15316.gzip,dataType=DB_BATCH]],processId=15316,startTime=1431316188099,endTime=<null>,firstTime=1431312467000,batchId=20,number=1351,size=<null>,exts=<null>,pipelineId=1]
com.alibaba.otter.node.etl.common.pipe.exception.PipeException: download_error
com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: aborted for some configration error.
2015-05-11 03:54:37.521 [pipelineId = 1,taskName = transformWorker] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:10[1:setl:com.alibaba.otter.node.etl.common.pipe.exception.PipeException: download_error
Caused by: com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: aborted for some configration error.
]
2015-05-11 03:56:34.440 [pipelineId = 1,taskName = transformWorker] ERROR c.a.o.n.e.common.io.download.impl.aria2c.Aria2cRetriever - Cannot run program "aria2c": error=2, No such file or directory
com.alibaba.otter.node.etl.common.io.download.exception.DataRetrieveException: Cannot run program "aria2c": error=2, No such file or directory
java.io.IOException: Cannot run program "aria2c": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_71]
	at java.lang.Runtime.exec(Runtime.java:617) ~[na:1.7.0_71]
	at java.lang.Runtime.exec(Runtime.java:450) ~[na:1.7.0_71]
	at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:62) ~[shared.common-4.2.11.jar:na]
	at com.alibaba.otter.shared.common.utils.cmd.Exec.execute(Exec.java:49) ~[shared.common-4.2.11.jar:na]
	at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandDownload.download(AbstractCommandDownload.java:70) ~[node.etl-4.2.11.jar:na]
	at com.alibaba.otter.node.etl.common.io.download.impl.AbstractCommandRetriever.doRetrieve(AbstractCommandRetriever.java:62) [node.etl-4.2.11.jar:na]
	at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:199) [node.etl-4.2.11.jar:na]
	at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71) [node.etl-4.2.11.jar:na]
	at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128) [node.etl-4.2.11.jar:na]
	at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76) [node.etl-4.2.11.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_71]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186) ~[na:1.7.0_71]
	at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_71]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028) ~[na:1.7.0_71]
	... 15 common frames omitted

看日志信息是不能运行aria2c，本机的aria2c位置： 
[root@sinobio logs]# whereis aria2c 
aria2c: /usr/local/bin/aria2c

**Comment by agapple** [comment]
java.io.IOException: Cannot run program "aria2c": error=2, No such file or directory.  
确认java进程启动时装载的PATH路径中是否包含了aria2c

**Comment by ghqaz3633** [comment]
感谢，由于安装过程中没有配置aria2c的环境变量，配置后运行两天，该错误一直没有出现过。

**Comment by dusonchen** [comment]
@agapple  aria2 要什么版本的，有1.90，但编译不通过，下载1.6.4后，需要的依赖一大堆，这些依赖也找不到源下载

**Comment by hyrzzh** [comment]
@agapple 我的也报这个错误,node.log日志中没有报错

**Comment by yanghongkjxy** [comment]
error=2, 是超时了，aria2 都是有安装的
