### ISSUE TITLE
Otter全量同步retl_buffer表中concat pk 的顺序问题

### ISSUE THREAD

**Issue by liuyikun** [alibaba/otter#785]
问题如下：
insert的pk是concat(id,char(1),time)，出现exception，发现是顺序问题id当做time解析：

`pid:1 nid:2 exception:setl:com.alibaba.otter.node.etl.extract.exceptions.ExtractException: java.util.concurrent.ExecutionException: org.apache.commons.beanutils.ConversionException: Value format invalid: For input string: "B6Gm0wC0SfKdvUPe/hwnFw=="
Caused by: java.util.concurrent.ExecutionException: org.apache.commons.beanutils.ConversionException: Value format invalid: For input string: "B6Gm0wC0SfKdvUPe/hwnFw=="
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor.extract(DatabaseExtractor.java:139)
    at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor.extract(DatabaseExtractor.java:81)
    at com.alibaba.otter.node.etl.extract.extractor.DatabaseExtractor$$FastClassByCGLIB$$f79e22c6.invoke()
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)`

然后delete掉retl_buffer的数据后改变顺序insert concat(time,char(1),id),后重启node 还是报错。后来干脆干掉了retl_buffer中所有的数据，重启node仍然出现同样的exception。

请问是否哪里的缓存引起的，或者必须做什么特别的操作？ 谢谢！

**Comment by agapple** [comment]
上一次的retl_buffer的binlog一直被堵着，必须得跳过binlog才行
