### ISSUE TITLE
otter DDL 出错，日志循环输出column size is not match for table 和  Duplicate column name 

### ISSUE THREAD

**Issue by hudajin1980** [alibaba/otter#787]
大神，好！

在使用Otter的时候，发现channel挂起，看日志，发现类似下面错误日志。
在这期间主库添加了字段，数据量快2000万。

看了一些源码，感觉如果开启跳过ddl异常开关，如果由于网络抖动或者其他原因，会不会真的没有执行ddl？如果关闭跳过ddl异常开关，又一直挂起，manager管理页面操作解挂，没有解决问题。

请问如何处理？

2019-06-18 17:25:35.166 [destination = 192.168.56.21 , address = /192.168.56.10:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ---> find start position successfully, EntryPosition[included=false,journalName=
mysql-bin.000005,position=247775225,serverId=2,gtid=,timestamp=1560849905000] cost : 498ms , the next step is binlog dump
2019-06-18 17:25:43.815 [destination = 192.168.56.21 , address = /192.168.56.10:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## parse this event has an error , last position : [EntryPosition[included
=false,journalName=mysql-bin.000005,position=252882764,serverId=2,gtid=,timestamp=1560849914000]]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:xxl.student,6 vs 5
2019-06-18 17:25:43.815 [destination = 192.168.56.21 , address = /192.168.56.10:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 192.168.56.10/192.168.56.10:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:xxl.student,6 vs 5
2019-06-18 17:25:43.816 [destination = 192.168.56.21 , address = /192.168.56.10:3306 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:1[1:canal:192.168.56.21:com.alibaba.otter.canal.parse.exception.CanalParse
Exception: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:xxl.student,6 vs 5
]
2019-06-18 17:25:44.989 [pipelineId = 1,taskName = LoadWorker] ERROR com.alibaba.otter.node.etl.load.LoadTask - [1] loadWork executor is error! data:EtlEventData[currNid=1,nextNid=1,desc=[MemoryPipeKey[identity=Identity[channelId=1,pipelineId=1,processId=58],time=1560849943808,dataType=DB_BATCH]],processId=58,startTime=1560849943801,endTime=<null>,firstTime=1560849908000,batchId=60,number=1,size=<null>,exts=<null>,pipelineId=1]
com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'is_delete'
Caused by: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'is_delete'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_212]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_212]
        at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader.load(DataBatchLoader.java:107) ~[node.etl-4.2.17.jar:na]
        at com.alibaba.otter.node.etl.load.loader.OtterLoaderFactory.load(OtterLoaderFactory.java:50) ~[node.etl-4.2.17.jar:na]
        at com.alibaba.otter.node.etl.load.LoadTask$1.run(LoadTask.java:85) ~[node.etl-4.2.17.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysq
l.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'is_delete'
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplic
ate column name 'is_delete'
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'is_delete'
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:98) ~[spring-jdbc-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80) ~[spring-jdbc-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407) ~[spring-jdbc-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doDdl(DbLoadAction.java:357) ~[node.etl-4.2.17.jar:na]

**Comment by hudajin1980** [comment]
版本，4.2.17

**Comment by agapple** [comment]
Duplicate column name 'is_delete'，应该是重复的ddl同步，可以高级设置里关闭DDL复制
