### ISSUE TITLE
otter 实时同步mysql 8.0.16

### ISSUE THREAD

**Issue by Yanhua1017** [alibaba/otter#788]
用otter最新版实时同步mysql8.0.16 -> mysql8.0.16报如下错误，怎么解决哈？
exception:setl:com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unknown system variable 'query_cache_size')
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory.getDbDialect(DbDialectFactory.java:115)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:111)
at com.alibaba.otter.node.etl.transform.transformer.RowDataTransformer.transform(RowDataTransformer.java:50)
at com.alibaba.otter.node.etl.transform.transformer.OtterTransformerFactory.transform(OtterTransformerFactory.java:77)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:86)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by yaoqi** [comment]
把mysql驱动升上来看看？

**Comment by Yanhua1017** [comment]
> 把mysql驱动升上来看看？

我升级了mysql驱动，数据源都能连上，就是在启动channel同步时，说目的端的springframework连不上

**Comment by happyguy1986** [comment]
https://www.cnblogs.com/nicknailo/articles/9074804.html  碰到问题先自己到网上找解决方案啊

**Comment by day-by-day** [comment]
将mysql-connector-java-5.1.40.jar 升级为 mysql-connector-java-5.1.47.jar
