### ISSUE TITLE
添加字段报错

### ISSUE THREAD

**Issue by laopangzhang** [alibaba/otter#79]
主库中添加一个字段'unionid’，发现日志有如下报错，添加一个字段'unionid’，发现日志有如下报错，

首先是在表里面没有发现这个字段，而后，就说有重复的字段，我返回数据查询，发现从库已经添加这个字段了。但同步channel已经挂起了。不知道是什么原因。

2015-05-21 11:40:49 pid:2 nid:2 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: unionid is not found in Table [name=users; 37 columns] and source : dji_store_production..*

2015-05-21 11:41:48
pid:2 nid:2 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'unionid'
Caused by: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'unionid'
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:188)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader.load(DataBatchLoader.java:107)
at com.alibaba.otter.node.etl.load.loader.OtterLoaderFactory.load(OtterLoaderFactory.java:50)
at com.alibaba.otter.node.etl.load.LoadTask$1.run(LoadTask.java:85)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'unionid'
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'unionid'
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'unionid'
at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTransl

**Comment by agapple** [comment]
检查是否配置了双向同步，并且两个方向都开启了DDL同步，关闭其中一个方向的DDL同步

**Comment by laopangzhang** [comment]
从的一边的ddl都已经关闭，不会同步到主的，另外，后面的加字段就没有报过这个错误，一切都是正常，出一次，不知道什么原因导致的。并且，从库的一边根本 没有ddl的权限。

**Comment by agapple** [comment]
Duplicate column name 'unionid'， 可能是otter的自动恢复机制导致出现重复同步，可忽略DDL同步异常跳过

**Comment by ninglianjie** [comment]
“otter的自动恢复机制”有相关的资料说明吗？

**Comment by agapple** [comment]
1.  ddl同步流程估计出现过了重复处理，忽略整个DDL同步可以跳过
2. 自动恢复机制可以翻下wiki

2016-06-27 18:22 GMT+08:00 ninglianjie <notifications@github.com>:

**Comment by aiaix** [comment]
@laopangzhang 这个问题有解决吗
