### ISSUE TITLE
otter同步出错

### ISSUE THREAD

**Issue by laopangzhang** [alibaba/otter#80]
otter一直都是正常工作的，突然一天，报了以下的错误，导致延时一天，我停用以后又 启用，正常同步了。但是很想知道是什么原因导致的。

pid:2 nid:2 exception:setl:com.alibaba.otter.node.etl.common.pipe.exception.PipeException: deserial_error
Caused by: java.io.FileNotFoundException: /app/otter/node/bin/../download/DbBatch-2015-05-28-12-20-12-2-2-715816.gzip (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.(FileInputStream.java:146)
at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.getDbBatch(RowDataHttpPipe.java:216)
at com.alibaba.otter.node.etl.common.pipe.impl.http.RowDataHttpPipe.get(RowDataHttpPipe.java:71)
at com.alibaba.otter.node.etl.common.pipe.impl.RowDataPipeDelegate.get(RowDataPipeDelegate.java:128)
at com.alibaba.otter.node.etl.transform.TransformTask$1.run(TransformTask.java:76)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
可能是因为网络同步延迟，导致基于aria2c同步的临时文件被删除，建议开启系统self.monitor，可以自动进行重试恢复

**Comment by Bruce2jiang** [comment]
laopangzhang 你好，文件怎么配置，把大概思路讲一下

**Comment by agapple** [comment]
https://github.com/alibaba/otter/wiki/Otter%E6%89%A9%E5%B1%95%E6%80%A7
