### ISSUE TITLE
otter解析binlog失败

### ISSUE THREAD

**Issue by tianqizhanhao1234** [alibaba/otter#805]
引起解析失败的语句如下：
sql_mode=''
UPDATE members SET money = money + **103.**  WHERE id = 1234 AND money >= '**103.**' 

otter报错日志如下
 exception:canal:to_big:com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NumberFormatException: For input string: "1300."
Caused by: java.lang.NumberFormatException: For input string: "1300."
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.math.BigInteger.(BigInteger.java:470)
at java.math.BigInteger.(BigInteger.java:606)
at com.alibaba.fastsql.sql.parser.Lexer.integerValue(Lexer.java:2442)
at com.alibaba.fastsql.sql.parser.SQLExprParser.primary(SQLExprParser.java:386)
at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:205)
at com.alibaba.fastsql.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:121)
at com.alibaba.fastsql.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:208)
at com.alibaba.fastsql.sql.parser.SQLExprParser.additiveRest(SQLExprParser.java:2099)
at com.alibaba.fastsql.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:106)
at com.alibaba.fastsql.sql.parser.SQLExprParser.expr(SQLExprParser.java:99)
at com.alibaba.fastsql.sql.parser.SQLExprParser.parseUpdateSetItem(SQLExprParser.java:1910)
at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlSelectParser.parseUpdateStatment(MySqlSelectParser.java:496)
at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseUpdateStatement(MySqlStatementParser.java:111)
at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:218)
at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:93)
at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:534)
at com.alibaba.otter.canal.parse.inbound.mysql.ddl.DruidDdlParser.parse(DruidDdlParser.java:51)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsQueryEvent(LogEventConvert.java:379)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:130)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:67)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:409)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:209)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:168)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
at java.lang.Thread.run(Thread.java:748)

**Comment by linqh1** [comment]
你这更新语句能执行成功？

**Comment by tianqizhanhao1234** [comment]
Hi linqh-qtl:
感谢您百忙中进行回复。
由于设置了sql_mode='',请看如下截图。
[image: image.png]
解析出来的binlog如下
/*!*/;
# at 999
#190815  0:24:38 server id 1013306  end_log_pos 1087 CRC32 0x30c2c955
Rows_query
# update members set money=money-103. where id=1 and money>='103.'
# at 1087
#190815  0:24:38 server id 1013306  end_log_pos 1139 CRC32 0x9cb0d005
Table_map: `db1`.`members` mapped to number 108
# at 1139
#190815  0:24:38 server id 1013306  end_log_pos 1201 CRC32 0x031ff742
Update_rows: table id 108 flags: STMT_END_F
### UPDATE `db1`.`members`
### WHERE
###   @1=1 /* INT meta=0 nullable=0 is_null=0 */
###   @2=106.00 /* DECIMAL(16,2) meta=4098 nullable=1 is_null=0 */
### SET
###   @1=1 /* INT meta=0 nullable=0 is_null=0 */
###   @2=3.00 /* DECIMAL(16,2) meta=4098 nullable=1 is_null=0 */
# at 1201
#190815  0:24:38 server id 1013306  end_log_pos 1232 CRC32 0xc329b95d Xid =
25
COMMIT/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;

linqh-qtl <notifications@github.com> 于 2019年8月14日周三 14:53写道：

**Comment by tianqizhanhao1234** [comment]
![image](https://user-images.githubusercontent.com/54062748/63039993-103acf80-bef7-11e9-87b3-fa789c0155af.png)

**Comment by linqh1** [comment]
那感觉是otter解析sql语句漏掉了某种情况吧？

`java.lang.NumberFormatException: For input string: "1300."`
不知道这个`1300.`怎么出现的

**Comment by linqh1** [comment]
可以给canal提个issue

**Comment by linqh1** [comment]
话说你数据库的binlog_format是STATEMENT?

**Comment by tianqizhanhao1234** [comment]
不是的，是row格式

linqh-qtl <notifications@github.com> 于 2019年8月15日周四 17:40写道：

**Comment by tianqizhanhao1234** [comment]
这个已经骂过了开发

linqh-qtl <notifications@github.com> 于 2019年8月15日周四 17:35写道：

**Comment by agapple** [comment]
最新的canal版本已经解决，otter可以升级最新版本
