### ISSUE TITLE
zookeeper配置异常，但manager启动未识别其异常状态，仍强制启动

### ISSUE THREAD

**Issue by tongsir** [alibaba/otter#808]
我在配置zookeeper时用了一个老的zoo集群，该集群需要auth认证。当我启动manager进程时，manager日志打印了zoo的认证错误，但manager未识别该错误，而是继续强制启动进程。
``` txt
Caused by: org.I0Itec.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /otter
  at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:68) ~[zkclient-0.10.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.retryUntilConnected(ZkClientx.java:785) ~[shared.common-4.2.17.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.create(ZkClientx.java:404) ~[shared.common-4.2.17.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.createPersistent(ZkClientx.java:323) ~[shared.common-4.2.17.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.createPersistent(ZkClientx.java:333) ~[shared.common-4.2.17.jar:na]
  at com.alibaba.otter.shared.arbitrate.impl.setl.monitor.NodeMonitor.<init>(NodeMonitor.java:64) ~[shared.arbitrate-4.2.17.jar:na]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_201]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_201]
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_201]
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_201]
  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]
  ... 37 common frames omitted
Caused by: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /otter
  at org.apache.zookeeper.KeeperException.create(KeeperException.java:113) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
  at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
  at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
  at org.I0Itec.zkclient.ZkConnection.create(ZkConnection.java:95) ~[zkclient-0.10.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx$2.call(ZkClientx.java:408) ~[shared.common-4.2.17.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx$2.call(ZkClientx.java:404) ~[shared.common-4.2.17.jar:na]
  at com.alibaba.otter.shared.common.utils.zookeeper.ZkClientx.retryUntilConnected(ZkClientx.java:775) ~[shared.common-4.2.17.jar:na]
  ... 46 common frames omitted
2019-08-22 15:50:45.209 [] INFO  com.alibaba.otter.manager.deployer.JettyEmbedServer - ##Jetty Embed Server is startup!
2019-08-22 15:50:45.209 [] INFO  com.alibaba.otter.manager.deployer.OtterManagerLauncher - ## the manager server is running now ......
```

**Comment by agapple** [comment]
先关闭auth认证吧
