### ISSUE TITLE
Throw exception 'Not found class endpoint' when start the otter.

### ISSUE THREAD

**Issue by a51764579** [alibaba/otter#811]
The exception is :
c.alibaba.dubbo.rpc.support.RpcUtils -  [DUBBO] Not found class endpoint, cause: endpoint, dubbo version: 2.8.4, current host: 127.0.0.1
java.lang.IllegalStateException: Not found class endpoint, cause: endpoint ?

**Comment by linqh1** [comment]
Could you describe what steps you did before the exception occurs?

**Comment by a51764579** [comment]
> Could you describe what steps you did before the exception occurs?

After I restart the node then I modify some data, I find the exception in logfile.

**Comment by linqh1** [comment]
It looks like there are some problem with communicataion between node and manager

**Comment by linqh1** [comment]
> > Could you describe what steps you did before the exception occurs?
> 
> After I restart the node then I modify some data, I find the exception in logfile.

It looks like there are some problem with communicataion between node and manager

**Comment by a51764579** [comment]
> > > Could you describe what steps you did before the exception occurs?
> > 
> > 
> > After I restart the node then I modify some data, I find the exception in logfile.
> 
> It looks like there are some problem with communicataion between node and manager

My manage and My node are in the same machine. The config??

**Comment by linqh1** [comment]
Same Issue: #426

**Comment by a51764579** [comment]
> Same Issue: #426

The answer could not resolve my problem.

**Comment by quanllong** [comment]
I meet the same error
2023-09-04 19:40:50.995  WARN 9197 --- [lientWorker-1-1] com.alibaba.dubbo.rpc.support.RpcUtils   :  [DUBBO] Not found class endpoint, cause: endpoint, dubbo version: 2.6.9, current host: 10.74.52.56

java.lang.IllegalStateException: Not found class endpoint, cause: endpoint
	at com.alibaba.dubbo.common.utils.ReflectUtils.forName(ReflectUtils.java:605) ~[dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:67) ~[dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:110) [dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:143) [dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88) [dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:125) [dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:85) [dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46) [dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:95) [dubbo-2.6.9.jar:2.6.9]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.53.Final.jar:4.1.53.Final]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372]
Caused by: java.lang.ClassNotFoundException: endpoint
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:51) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_372]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_372]
	at com.alibaba.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:668) ~[dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:618) ~[dubbo-2.6.9.jar:2.6.9]
	at com.alibaba.dubbo.common.utils.ReflectUtils.forName(ReflectUtils.java:603) ~[dubbo-2.6.9.jar:2.6.9]
	... 27 common frames omitted

**Comment by OsmondGao** [comment]
I think the problem is the bean of endpoint' full name at "com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationConnectionFactory", 
DUBBO_SERVICE_URL = "dubbo://{0}:{1}/**endpoint**?client=netty&codec=du.........
The endpoint should be replaced with "com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationEndpoint "
