### ISSUE TITLE
otter-node 节点连接manager 超时 com.alibaba.dubbo.rpc.RpcException: Invoke remote method timeout.

### ISSUE THREAD

**Issue by yanghongkjxy** [alibaba/otter#815]
2019-08-28 10:03:21.004 [communication-async-0] ERROR c.a.o.s.c.core.impl.DefaultCommunicationClientImpl - call[10.12.21.20:1199] , retry[1]
com.alibaba.dubbo.rpc.RpcException: Invoke remote method timeout. method: acceptEvent, provider: dubbo://10.12.21.20:1199/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&iothreads=4&lazy=true&payload=8388608&serialization=java&threads=50, cause: Waiting server-side response timeout by scan timer. start time: 2019-08-28 10:02:31.001, end time: 2019-08-28 10:03:21.003, client elapsed: 0 ms, server elapsed: 50002 ms, timeout: 50000 ms, request: Request [id=151484479, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=acceptEvent, parameterTypes=[class com.alibaba.otter.shared.communication.core.model.Event], arguments=[ThroughputStatEvent[stats=[ThroughputStat[id=<null>,pipelineId=19,startTime=2019-08-28 10:02:30,endTime=2019-08-28 10:02:31,type=ROW,number=3,size=363,gmtCreate=<null>,gmtModified=<null>]],type=throughputStat]], attachments={path=endpoint, version=0.0.0}]], channel: /10.30.38.20:6578 -> /10.12.21.20:1199
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:99) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.common.bytecode.proxy0.acceptEvent(proxy0.java) ~[na:2.5.3]
        at com.alibaba.otter.shared.communication.core.impl.dubbo.DubboCommunicationConnection.call(DubboCommunicationConnection.java:45) ~[shared.communication-4.2.17.jar:na]
        at com.alibaba.otter.shared.communication.core.impl.DefaultCommunicationClientImpl.call(DefaultCommunicationClientImpl.java:96) ~[shared.communication-4.2.17.jar:na]
        at com.alibaba.otter.node.common.communication.NodeCommmunicationClient.callManager(NodeCommmunicationClient.java:74) [node.common-4.2.17.jar:na]
        at com.alibaba.otter.node.common.communication.NodeCommmunicationClient$1.run(NodeCommmunicationClient.java:98) [node.common-4.2.17.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2019-08-28 10:02:31.001, end time: 2019-08-28 10:03:21.003, client elapsed: 0 ms, server elapsed: 50002 ms, timeout: 50000 ms, request: Request [id=151484479, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=acceptEvent, parameterTypes=[class com.alibaba.otter.shared.communication.core.model.Event], arguments=[ThroughputStatEvent[stats=[ThroughputStat[id=<null>,pipelineId=19,startTime=2019-08-28 10:02:30,endTime=2019-08-28 10:02:31,type=ROW,number=3,size=363,gmtCreate=<null>,gmtModified=<null>]],type=throughputStat]], attachments={path=endpoint, version=0.0.0}]], channel: /10.30.38.20:6578 -> /10.12.21.20:1199
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96) ~[dubbo-2.5.3.jar:2.5.3]
        ... 12 common frames omitted

**Comment by yanghongkjxy** [comment]
manager一直报线程池满

2019-08-28 21:39:31.019 [] WARN  org.jboss.netty.channel.DefaultChannelPipeline -  [DUBBO] An exception was thrown by a user handler while handling an exception event ([id: 0x429f324a, /10.12.90.45:29421 => /10.12.21.224:1199] EXCEPTION: com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process received event .), dubbo version: 2.5.3, current host: 10.12.21.224
com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process caught event .
        at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:67) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.caught(AbstractPeer.java:127) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.exceptionCaught(NettyHandler.java:112) ~[dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.exceptionCaught(NettyCodecAdapter.java:165) ~[dubbo-2.5.3.jar:2.5.3]
        at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:52) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.2.Final.jar:na]
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:148) ~[dubbo-2.5.3.jar:2.5.3]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) ~[netty-3.2.2.Final.jar:na]
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.2.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.util.concurrent.RejectedExecutionException: Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-127.0.0.1:1199, Pool Size: 50 (active: 50, core: 50, max: 50, largest: 50), Task: 99384445 (completed: 99384395), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://127.0.0.1:1199!
        at com.alibaba.dubbo.common.threadpool.support.AbortPolicyWithReport.rejectedExecution(AbortPolicyWithReport.java:53) ~[dubbo-2.5.3.jar:2.5.3]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) [na:1.8.0_45]
        at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:65) ~[dubbo-2.5.3.jar:2.5.3]
        ... 18 common frames omitted

**Comment by yanghongkjxy** [comment]
@longdafeng

**Comment by zk19930911** [comment]
我们同步了100多个channel，目前也报这个错误，但是不影响channel同步数据

**Comment by zk19930911** [comment]
node节点的日志，manager节点的日志就是上边的错误

**Comment by agapple** [comment]
DubboServerHandler-127.0.0.1:1199, Pool Size: 50 (active: 50, core: 50, max: 50, largest: 50)

感觉是资源满了

**Comment by linqh1** [comment]
> DubboServerHandler-127.0.0.1:1199, Pool Size: 50 (active: 50, core: 50, max: 50, largest: 50)
> 
> 感觉是资源满了

这个怎么处理? 配置文件好像没看到对应的参数
