### ISSUE TITLE
啥时候更新正式版canal组件到1.1.3

### ISSUE THREAD

**Issue by jin544642965** [alibaba/otter#817]
报错如下
pid:75 nid:1 exception:canal:canal_wq_to_ehuzhuProd_ims_mc_mapping_fans:com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
with command: select @@global.binlog_checksum
Caused by: java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
with command: select @@global.binlog_checksum
at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:105)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:508)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:151)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
at java.lang.Thread.run(Thread.java:748)

问题说是1.1.3才解决了，啥时候更新到1.1.3

**Comment by agapple** [comment]
最新otter版本，已经升级canal到1.1.4
