### ISSUE TITLE
otter挂起，报错如下

### ISSUE THREAD

**Issue by Perterually** [alibaba/otter#821]
otter 版本：4.2.17
系统：windows server 2018 r2

pid:2 nid:1 exception:setl:java.lang.NullPointerException 
at com.alibaba.otter.shared.arbitrate.impl.setl.memory.MemoryStageController.getLastData(MemoryStageController.java:85) 
at com.alibaba.otter.shared.arbitrate.impl.setl.memory.ExtractMemoryArbitrateEvent.await(ExtractMemoryArbitrateEvent.java:52) 
at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.ExtractDelegateArbitrateEvent.await(ExtractDelegateArbitrateEvent.java:36) 
at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.ExtractDelegateArbitrateEvent$$FastClassByCGLIB$$b36a599b.invoke() 
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) 
at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689) 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) 
at com.alibaba.otter.shared.arbitrate.impl.interceptor.LogInterceptor.invoke(LogInterceptor.java:53) 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) 
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) 
at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.ExtractDelegateArbitrateEvent$$EnhancerByCGLIB$$9c91b4da.await() 
at com.alibaba.otter.node.etl.extract.ExtractTask.run(ExtractTask.java:53)

**Comment by linqh1** [comment]
channel暂停，推送一下再试试？

**Comment by Perterually** [comment]
> channel暂停，推送一下再试试？

重新启动了服务好多次 .莫名其妙就好了
