### ISSUE TITLE
4.2.17升级4.2.18后无法select，报java.lang.NullPointerException。4.2.17正常使用

### ISSUE THREAD

**Issue by sunailong** [alibaba/otter#828]
2019-09-09 16:58:01.295 [pipelineId = 17,taskName = SelectTask] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:5[17:setl:com.google.common.collect.ComputationException: java.lang.NullPointerException
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:137)
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.start(CanalEmbedSelector.java:212)
	at com.alibaba.otter.node.etl.select.SelectTask.startup(SelectTask.java:170)
	at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:126)
Caused by: java.lang.NullPointerException
	at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.doInitEventParser(CanalInstanceWithManager.java:337)
	at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.initEventParser(CanalInstanceWithManager.java:261)
	at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.<init>(CanalInstanceWithManager.java:93)
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1$1.<init>(CanalEmbedSelector.java:145)
	at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1.generate(CanalEmbedSelector.java:145)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:85)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:82)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
	... 4 more
]

**Comment by sunailong** [comment]
重新配置后已解决

**Comment by RobinDu325** [comment]
> 重新配置后已解决

你好，我遇到和你同样的问题，请问你是怎么解决的？多谢
