### ISSUE TITLE
很简单的一个表，联合主键，只有几条数据，一更新就挂起，日志很简单，看不出所以然

### ISSUE THREAD

**Issue by elefaint** [alibaba/otter#834]
pid:7 nid:5 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: java.lang.ClassCastException
:-----------------
- PairId: 75 , TableId: 102 , EventType : U , Time : 1568856232000 
- Consistency : , Mode : 
-----------------
---Pks
    EventColumn[index=0,columnType=-5,columnName=user_id,columnValue=99424,isNull=false,isKey=true,isUpdate=true]
    EventColumn[index=1,columnType=12,columnName=user_key,columnValue=temp_room_4,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=2,columnType=2004,columnName=value,columnValue=,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=5,columnType=93,columnName=mtime,columnValue=2019-09-19 09:23:51,isNull=false,isKey=false,isUpdate=true]
---Sql
    update `sync_ijdbs`.`t_user_dict` set `value` = ? , `mtime` = ? where ( `user_id` = ? and `user_key` = ? )

Caused by: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: java.lang.ClassCastException
:-----------------
- PairId: 75 , TableId: 102 , EventType : U , Time : 1568856232000 
- Consistency : , Mode : 
-----------------
---Pks
    EventColumn[index=0,columnType=-5,columnName=user_id,columnValue=99424,isNull=false,isKey=true,isUpdate=true]
    EventColumn[index=1,columnType=12,columnName=user_key,columnValue=temp_room_4,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=2,columnType=2004,columnName=value,columnValue=,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=5,columnType=93,columnName=mtime,columnValue=2019-09-19 09:23:51,isNull=false,isKey=false,isUpdate=true]
---Sql
    update `sync_ijdbs`.`t_user_dict` set `value` = ? , `mtime` = ? where ( `user_id` = ? and `user_key` = ? )

    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader.load(DataBatchLoader.java:107)
    at com.alibaba.otter.node.etl.load.loader.OtterLoaderFactory.load(OtterLoaderFactory.java:50)
    at com.alibaba.otter.node.etl.load.LoadTask$1.run(LoadTask.java:85)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: java.lang.ClassCastException
:-----------------
- PairId: 75 , TableId: 102 , EventType : U , Time : 1568856232000 
- Consistency : , Mode : 
-----------------
---Pks
    EventColumn[index=0,columnType=-5,columnName=user_id,columnValue=99424,isNull=false,isKey=true,isUpdate=true]
    EventColumn[index=1,columnType=12,columnName=user_key,columnValue=temp_room_4,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=2,columnType=2004,columnName=value,columnValue=,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=5,columnType=93,columnName=mtime,columnValue=2019-09-19 09:23:51,isNull=false,isKey=false,isUpdate=true]
---Sql
    update `sync_ijdbs`.`t_user_dict` set `value` = ? , `mtime` = ? where ( `user_id` = ? and `user_key` = ? )

Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: java.lang.ClassCastException
:-----------------
- PairId: 75 , TableId: 102 , EventType : U , Time : 1568856232000 
- Consistency : , Mode : 
-----------------
---Pks
    EventColumn[index=0,columnType=-5,columnName=user_id,columnValue=99424,isNull=false,isKey=true,isUpdate=true]
    EventColumn[index=1,columnType=12,columnName=user_key,columnValue=temp_room_4,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=2,columnType=2004,columnName=value,columnValue=,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=5,columnType=93,columnName=mtime,columnValue=2019-09-19 09:23:51,isNull=false,isKey=false,isUpdate=true]
---Sql
    update `sync_ijdbs`.`t_user_dict` set `value` = ? , `mtime` = ? where ( `user_id` = ? and `user_key` = ? )

Caused by: com.alibaba.otter.node.etl.load.exception.LoadException: java.lang.ClassCastException
:-----------------
- PairId: 75 , TableId: 102 , EventType : U , Time : 1568856232000 
- Consistency : , Mode : 
-----------------
---Pks
    EventColumn[index=0,columnType=-5,columnName=user_id,columnValue=99424,isNull=false,isKey=true,isUpdate=true]
    EventColumn[index=1,columnType=12,columnName=user_key,columnValue=temp_room_4,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=2,columnType=2004,columnName=value,columnValue=,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=5,columnType=93,columnName=mtime,columnValue=2019-09-19 09:23:51,isNull=false,isKey=false,isUpdate=true]
---Sql
    update `sync_ijdbs`.`t_user_dict` set `value` = ? , `mtime` = ? where ( `user_id` = ? and `user_key` = ? )

**Comment by elefaint** [comment]
| t_user_dict | CREATE TABLE `t_user_dict` (
  `user_id` bigint(20) NOT NULL,
  `user_key` varchar(255) NOT NULL,
  `value` blob,
  `modify_time` int(10) NOT NULL,
  `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`user_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |

**Comment by elefaint** [comment]
blob为可空字段，更新数据为NULL

**Comment by linqh1** [comment]
联合主键吗？otter好像要求有一个唯一主键

**Comment by h2012c106** [comment]
问题出在空blob字段上。  
在[SqlUtils](https://github.com/alibaba/otter/blob/master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/SqlUtils.java#L141)中，如果blob字段值是空，且`isEmptyStringNulled`为false，这个函数会返回一个空字符串，而在[DbLoadAction](https://github.com/alibaba/otter/blob/master/node/etl/src/main/java/com/alibaba/otter/node/etl/load/loader/db/DbLoadAction.java#L786)中会对上述返回值强转byte[]，此时如果`param`是空字符串就会报你的错。  
我用binary(4)类型也报了这个错

**Comment by linqh1** [comment]
> 问题出在空blob字段上。
> 在[SqlUtils](https://github.com/alibaba/otter/blob/master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/SqlUtils.java#L141)中，如果blob字段值是空，且`isEmptyStringNulled`为false，这个函数会返回一个空字符串，而在[DbLoadAction](https://github.com/alibaba/otter/blob/master/node/etl/src/main/java/com/alibaba/otter/node/etl/load/loader/db/DbLoadAction.java#L786)中会对上述返回值强转byte[]，此时如果`param`是空字符串就会报你的错。
> 我用binary(4)类型也报了这个错

问下你最后怎么处理这个问题的?

**Comment by h2012c106** [comment]
> > 问题出在空blob字段上。
> > 在[SqlUtils](https://github.com/alibaba/otter/blob/master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/SqlUtils.java#L141)中，如果blob字段值是空，且`isEmptyStringNulled`为false，这个函数会返回一个空字符串，而在[DbLoadAction](https://github.com/alibaba/otter/blob/master/node/etl/src/main/java/com/alibaba/otter/node/etl/load/loader/db/DbLoadAction.java#L786)中会对上述返回值强转byte[]，此时如果`param`是空字符串就会报你的错。
> > 我用binary(4)类型也报了这个错
> 
> 问下你最后怎么处理这个问题的?

`DbLoadAction.java`内处理各类型往`PreparedStatement`中塞的逻辑时，BLOB改成如下逻辑
```
case Types.BLOB:
    if (param instanceof String && ((String) param).length() == 0) {
        lobCreator.setBlobAsBytes(ps, paramIndex, new byte[0]);
    } else {
        lobCreator.setBlobAsBytes(ps, paramIndex, (byte[]) param);
    }
    break;
```
