### ISSUE TITLE
otter线上应用报创建线程失败

### ISSUE THREAD

**Issue by kangjiabang** [alibaba/otter#841]
[DubboServerHandler-127.0.0.1:2088-thread-50] ERROR c.a.o.shared.communication.core.CommunicationEndpoint - endpoint_error
com.alibaba.otter.shared.communication.core.exception.CommunicationException: method_invoke_error:onNotifyChannel
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at com.alibaba.otter.shared.communication.core.impl.AbstractCommunicationEndpoint.acceptEvent(AbstractCommunicationEndpoint.java:72) ~[shared.comm
unication-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.dubbo.common.bytecode.Wrapper0.invokeMethod(Wrapper0.java) [na:2.5.3]
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108) [dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84) [dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170) [dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) [dubbo-2.5.3.jar:2.5.3]
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82) [dubbo-2.5.3.jar:2.5.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) [na:1.8.0_151]
        at java.lang.Thread.start(Thread.java:717) [na:1.8.0_151]
        at com.alibaba.otter.node.etl.OtterController.startTask(OtterController.java:196) ~[node.etl-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.node.etl.OtterController.startPipeline(OtterController.java:171) ~[node.etl-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.node.etl.OtterController.process(OtterController.java:151) ~[node.etl-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.node.common.config.impl.NodeTaskServiceImpl.notifyListener(NodeTaskServiceImpl.java:429) ~[node.common-4.2.16-SNAPSHOT.jar:na
]
        at com.alibaba.otter.node.common.config.impl.NodeTaskServiceImpl.onNotifyChannel(NodeTaskServiceImpl.java:421) ~[node.common-4.2.16-SNAPSHOT.jar:n
a]
        ... 15 common frames omitted

请问如何解决？需要加机器还是修改配置？

**Comment by kangjiabang** [comment]
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method) [na:1.8.0_151]
at java.lang.Thread.start(Thread.java:717) [na:1.8.0_151]

**Comment by agapple** [comment]
估计是主机内存资源不足
