### ISSUE TITLE
4.2.18版本下载后启动management报错，提示无效正则flag 0x1000

### ISSUE THREAD

**Issue by SoulCoding** [alibaba/otter#843]
nested exception is java.lang.IllegalArgumentException: Unknown flag 0x1000
查源码应该是citrus-webx-all-3.2.0 jar包类ClassNameWildcardCompiler中的变量 MATCH_PREFIX = 0x1000; 
Caused by: java.lang.IllegalArgumentException: Unknown flag 0x1000
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1409) ~[na:na]
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1094) ~[na:na]
        at com.alibaba.citrus.util.regex.ClassNameWildcardCompiler.compileClassName(ClassNameWildcardCompiler.java:84) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        at com.alibaba.citrus.service.moduleloader.impl.factory.ClassModuleFactoryDefinitionParser.doParse(ClassModuleFactoryDefinitionParser.java:76) ~[citrus-webx-all-3.2.0.jar:3.2.0]
        at org.springframework.beans.factory.xml.AbstractSingleBeanDefinitionParser.parseInternal(AbstractSingleBeanDefinitionParser.java:85) ~[spring-beans-3.1.2.RELEASE.jar:3.1.2.RELEASE]

**Comment by qingw1983** [comment]
我在版本4.2.17 下把JDK 升级到14，启动Manager 有一样的问题

**Comment by dys001** [comment]
Manager版本是4.2.18，JDK尝试了17、18，启动Manager有一样的问题。请问大家使用的jdk版本号？

**Comment by FlyingZC** [comment]
使用 JDK 1.8 即可，https://github.com/alibaba/otter/issues/850
