### ISSUE TITLE
otter内部错误

### ISSUE THREAD

**Issue by ccjetweat** [alibaba/otter#851]
pid:1 nid:2 exception:canal:souche-to-diandan:com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NumberFormatException: -
Caused by: java.lang.NumberFormatException: -
    at com.alibaba.fastsql.sql.parser.Lexer.integerValue(Lexer.java:2571)
    at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseValueClause(SQLStatementParser.java:5444)
    at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:4658)
    at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:44)
    at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:237)
    at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:95)
    at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:545)
    at com.alibaba.otter.canal.parse.inbound.mysql.ddl.DruidDdlParser.parse(DruidDdlParser.java:51)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsQueryEvent(LogEventConvert.java:383)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:134)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:69)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:417)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:217)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:178)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:279)
    at java.lang.Thread.run(Thread.java:748)

**Comment by ccjetweat** [comment]
版本4.2.18  回退一个版本4.2.17测试没问题，但是4.2.18的能修复吗

**Comment by ccjetweat** [comment]
问题版本：
4.2.18
解决办法：
回退一个版本到4.2.17
疑问：
 是4.2.18新引入的这个异常吗？
