### ISSUE TITLE
Channel启动后，报空指针异常：NullPointerException

### ISSUE THREAD

**Issue by lang-zai** [alibaba/otter#866]
pid:3 nid:1 exception:setl:com.google.common.collect.ComputationException: java.lang.NullPointerException
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:137)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.start(CanalEmbedSelector.java:212)
at com.alibaba.otter.node.etl.select.SelectTask.startup(SelectTask.java:170)
at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:126)
Caused by: java.lang.NullPointerException
at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.doInitEventParser(CanalInstanceWithManager.java:337)
at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.initEventParser(CanalInstanceWithManager.java:261)
at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.(CanalInstanceWithManager.java:93)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1$1.(CanalEmbedSelector.java:145)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1.generate(CanalEmbedSelector.java:145)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:85)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:82)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
... 4 more

**Comment by calwang414** [comment]
同样的问题，manager启动时报空指针错误

**Comment by kuweilong** [comment]
我也遇到同样的问题，怎么解决啊？

**Comment by theskyzero** [comment]
> 
> 
> 我也遇到同样的问题，怎么解决啊？

你们配canal了吗，这里的空指针报错，看上去是canalserver没有，是不是canal配置有问题或者权限有问题，可以检查下node机器的日志看看呢

**Comment by kuweilong** [comment]
是manager问题，替换了一个manager不报这个错误了
