### ISSUE TITLE
mysql-8.0.18同步失败，Read Q_FLAGS2_CODE error: limit excceed: 64

### ISSUE THREAD

**Issue by mawenbin666** [alibaba/otter#920]
mysq版本:8.0.18
otter manage 版本：4.2.18
otter node 版本：4.2.12
centos 系统：7.6

monitor_info.log报错如下：

```
2020-05-12 09:50:15.942 INFO  monitorInfo - has suppressed alarm : pid:1 nid:2 exception:canal:guangzhou_to_idc:java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 64
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:650)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:477)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:154)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:106)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:115)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: limit excceed: 64
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:561)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:563)
	... 6 more

```
manager.log报错如下：
```
2020-05-12 09:31:31.545 [/?action=channelAction&channelId=1&status=start&pageIndex=1&searchKey=&eventSubmitDoStatus=true] WARN  com.alibaba.dubbo.remoting.transport.AbstractClient -  [DUBBO] client reconnect to 192.168.32.22:2088 find error . url: dubbo://192.168.32.22:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&payload=8388608&send.reconnect=true&serialization=java&threads=50, dubbo version: 2.5.3, current host: 192.168.32.33
com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.32.22:2088/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&payload=8388608&send.reconnect=true&serialization=java&threads=50) failed to connect to server /192.168.32.22:2088,error message is:Connection refused
	at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:145) ~[dubbo-2.5.3.jar:2.5.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_92]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_92]
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) ~[netty-3.2.2.Final.jar:na]
	... 3 common frames omitted
```
node节点的日志报错：
```
2020-05-12 09:54:00.924 [destination = guangzhou_to_idc , address = /192.168.32.22:3306 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:2[1:canal:guangzhou_to_idc:java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 64
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:650)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:477)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:154)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:106)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:115)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: limit excceed: 64
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:561)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:563)
	... 6 more

```
究竟是什么原因呢。

**Comment by mawenbin666** [comment]
把otter_node的版本升级到4.2.18就可以了。
