### ISSUE TITLE
关于部分节点无法连接到canal的问题

### ISSUE THREAD

**Issue by yuanboyumena** [alibaba/otter#931]
pid:1004 nid:1000 exception:canal:by_byh-health-management:com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /192.167.128.113:3306 failure
Caused by: java.io.IOException: connect /192.167.128.113:3306 failure
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:183)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes
    at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:91)
    at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:19)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:160)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80)
    ... 4 more

**Comment by yuanboyumena** [comment]
有人遇到过这个问题吗   有部分节点是可以连接到的  但是有4个节点是连接不到的  公用的同一个node

**Comment by mawenbin666** [comment]
请问，楼主解决了吗，我也遇到这个问题，

**Comment by yuanboyumena** [comment]
> 请问，楼主解决了吗，我也遇到这个问题
我这边是mysql服务端dns解析的问题,我这边直接跳过了   在mysql服务端配置加上skip-name-resolve试试吧
