### ISSUE TITLE
同步的时候经常报这个错误，不知道什么原因，jdk版本？还是？

### ISSUE THREAD

**Issue by zhuhuawu** [alibaba/otter#951]
pid:5 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'com.mysql.jdbc.Driver' for connect URL 'jdbc:mysql://192.168.3.11:3306'
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:209)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:258)
    at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
    at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
    at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.collect.ComputationException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'com.mysql.jdbc.Driver' for connect URL 'jdbc:mysql://192.168.3.11:3306'
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:167)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:116)
    at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67)
    at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:623)
    at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory.getDbDialect(DbDialectFactory.java:113)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:427)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:388)
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:139)
    ... 9 more
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'com.mysql.jdbc.Driver' for connect URL 'jdbc:mysql://192.168.3.11:3306'
    at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:331)
    at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory$2$1.apply(DbDialectFactory.java:81)
    at com.alibaba.otter.node.etl.common.db.dialect.DbDialectFactory$2$1.apply(DbDialectFactory.java:76)
    at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155)
    ... 16 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'com.mysql.jdbc.Driver' for connect URL 'jdbc:mysql://192.168.3.11:3306'
    at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1452)
    at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
    at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
    at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
    at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
    ... 20 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mysql.jdbc.Util
    at com.mysql.jdbc.NonRegisteringDriver.parseURL(NonRegisteringDriver.java:730)
    at com.mysql.jdbc.NonRegisteringDriver.acceptsURL(NonRegisteringDriver.java:260)
    at java.sql.DriverManager.getDriver(DriverManager.java:299)
    at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1437)
    ... 24 more

**Comment by linqh1** [comment]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mysql.jdbc.Util

用的哪个版本的otter? 怎么启动的?

**Comment by linqh1** [comment]
你少了某些jar包吧?
