### ISSUE TITLE
otter  bug 紧急

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#97]
你好
，我配置正则表达式((?!^(test3|test4|test7|test88)$).)*，意思是不同步test3 test4 test7 test88 4个表，这个正则表达式我验证是ok的，但是pipeline一会运行正常，一会挂起，如果运行正常可以同步数据，如果挂起，数据就不能同步了，更糟糕的是，重启channl后，没有同步成功的数据也不能同步了，我觉得这个可能是个otter 的bug，请帮助解决。
pipeline挂起时，异常日志如下 ：
pid:4 nid:5 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.alibaba.otter.shared.common.model.config.ConfigException: no such DataMedia , the namespace = otter1 name = test7
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:209)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:254)
    at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
    at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
    at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: com.alibaba.otter.shared.common.model.config.ConfigException: no such DataMedia , the namespace = otter1 name = test7

关闭

**Comment by agapple** [comment]
建议使用canal配置里的表过滤黑名单，避免使用复杂正则表达式

**Comment by bh-sky** [comment]
> 建议使用canal配置里的表过滤黑名单，避免使用复杂正则表达式

在otter中如何配置
