### ISSUE TITLE
manager的web错误503，node提示连不上本地1099端口，求助，是java版本问题吗，已经从11改到1.6+

### ISSUE THREAD

**Issue by yy1ft122784216** [alibaba/otter#978]
at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.getInstance(ZooKeeperClient.java:61)
	at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.getInstance(ZooKeeperClient.java:54)
	at com.alibaba.otter.shared.arbitrate.impl.setl.rpc.ExtractRpcArbitrateEvent.<init>(ExtractRpcArbitrateEvent.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 45 more
Caused by: com.alibaba.otter.shared.common.model.config.ConfigException: nid:1 in manager[127.0.0.1:1099]is not found!

**Comment by quanllong** [comment]
遇到相同问题，nid:1 in manager[127.0.0.1:1099]is not found!

**Comment by quanllong** [comment]
> ```
> at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.getInstance(ZooKeeperClient.java:61)
> at com.alibaba.otter.shared.arbitrate.impl.zookeeper.ZooKeeperClient.getInstance(ZooKeeperClient.java:54)
> at com.alibaba.otter.shared.arbitrate.impl.setl.rpc.ExtractRpcArbitrateEvent.<init>(ExtractRpcArbitrateEvent.java:45)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
> at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
> ... 45 more
> ```

> Caused by: com.alibaba.otter.shared.common.model.config.ConfigException: nid:1 in manager[127.0.0.1:1099]is not found!
遇到相同问题，请问怎么解决的

**Comment by quanllong** [comment]
本机node请求manager connect timeout（MacbookPro m2）
