### ISSUE TITLE
我配置正则表达式：((?!^(sb_proinfo)$).)* ，不同步sb_proinfo这个表

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#98]
我配置正则表达式：((?!^(sb_proinfo)$).)* ，不同步sb_proinfo这个表，但是每次sb_proinfo有数据写入的时候，otter就会报：pid:18 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.alibaba.otter.shared.common.model.config.ConfigException: no such DataMedia , the namespace = edu_jyg2 name = sb_proinfo
    at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:209)
    at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:254)
    at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
    at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
    at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
    at java.util.concurrent.FutureTask.run(FutureTask.java:149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
    at java.lang.Thread.run(Thread.java:738)
Caused by: com.alibaba.otter.shared.common.model.config.ConfigException: no such DataMedia , the namespace = edu_jyg2 name = sb_proinfo

**Comment by agapple** [comment]
先使用简单正则吧，复杂正则未经过严格测试
