### ISSUE TITLE
zookeeper问题，白名单，执行报空指针

### ISSUE THREAD

**Issue by LDWBFS** [alibaba/otter#987]
pid:1 nid:1 exception:setl:com.google.common.collect.ComputationException: java.lang.NullPointerException
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:137)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.start(CanalEmbedSelector.java:212)
at com.alibaba.otter.node.etl.select.SelectTask.startup(SelectTask.java:170)
at com.alibaba.otter.node.etl.select.SelectTask.run(SelectTask.java:126)
Caused by: java.lang.NullPointerException
at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.doInitEventParser(CanalInstanceWithManager.java:337)
at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.initEventParser(CanalInstanceWithManager.java:261)
at com.alibaba.otter.canal.instance.manager.CanalInstanceWithManager.(CanalInstanceWithManager.java:93)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1$1.(CanalEmbedSelector.java:145)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector$1.generate(CanalEmbedSelector.java:145)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:85)
at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:82)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)

![image](https://user-images.githubusercontent.com/79618159/109097176-cffa1580-7759-11eb-8a79-df17508fa706.png)

**Comment by linqh1** [comment]
zookeeper配置问题吧，是不是有白名单之类的配置。网上查一下

**Comment by LDWBFS** [comment]
> zookeeper配置问题吧，是不是有白名单之类的配置。网上查一下

查过，加一句话，加上以后更离谱了，全是空白了，刷新就是500，报array错误

**Comment by linqh1** [comment]
> > zookeeper配置问题吧，是不是有白名单之类的配置。网上查一下
> 
> 查过，加一句话，加上以后更离谱了，全是空白了，刷新就是500，报array错误

是不是你的canal/node指向了一个被删除的zookeeper?

**Comment by LDWBFS** [comment]
> > > zookeeper配置问题吧，是不是有白名单之类的配置。网上查一下
> > 
> > 
> > 查过，加一句话，加上以后更离谱了，全是空白了，刷新就是500，报array错误
> 
> 是不是你的canal/node指向了一个被删除的zookeeper?

没，我第一次配置时，报空指针，zookeeper拒绝服务，于是我重新导入otter系统表，重新配置zookeeper，还是不行，出的这个错误，白名单，
![image](https://user-images.githubusercontent.com/79618159/109247809-8a078500-781f-11eb-929d-24bd3d7af227.png)
![image](https://user-images.githubusercontent.com/79618159/109247841-9ab7fb00-781f-11eb-8c11-6ba0afd3ea57.png)
![image](https://user-images.githubusercontent.com/79618159/109247870-a3a8cc80-781f-11eb-99a3-95f428ee46db.png)
没有角色，代表没有服务

**Comment by LDWBFS** [comment]
> > > zookeeper配置问题吧，是不是有白名单之类的配置。网上查一下
> > 
> > 
> > 查过，加一句话，加上以后更离谱了，全是空白了，刷新就是500，报array错误
> 
> 是不是你的canal/node指向了一个被删除的zookeeper?

甚至改过端口，让这个zookeeper给气死了！

**Comment by 007akuan** [comment]
> > > > zookeeper配置问题吧，是不是有白名单之类的配置。网上查一下
> > > 
> > > 
> > > 查过，加一句话，加上以后更离谱了，全是空白了，刷新就是500，报array错误
> > 
> > 
> > 是不是你的canal/node指向了一个被删除的zookeeper?
> 
> 甚至改过端口，让这个zookeeper给气死了！

你好，请问这个问题最终怎么解决的，我现在遇到同样的问题，刷新就报空指针异常

**Comment by linqh1** [comment]
你是不是修改过otter上面的zookeeper配置，比如删除了某个zookeeper服务？
如果是这样的话，可以尝试先暂停channel，然后推送一下，再重启channel

**Comment by linqh1** [comment]
还有一种可能，就是你的zookeeper删了，但是你某个canal引用了这个zookeeper集群。。。
这样也会空指针
