### ISSUE TITLE
同步卡住

### ISSUE THREAD

**Issue by hjs0916633** [alibaba/otter#991]
pipeline会卡住无法正常同步，log会出现以下信息
2021-04-01 11:40:00.490 [pipelineId = 71,taskName = ProcessSelect] INFO  com.alibaba.otter.node.etl.select.SelectTask - [71] selectTask is interrrupt!
java.lang.InterruptedException: null
        at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:242) ~[node.etl-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236) [node.etl-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94) [node.etl-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208) [node.etl-4.2.15-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2021-04-01 11:40:00.490 [pipelineId = 71,taskName = ProcessTermin] INFO  com.alibaba.otter.node.etl.select.SelectTask - [71] ProcessTermin is interrupted!
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_111]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_111]
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[na:1.8.0_111]
        at com.alibaba.otter.node.etl.select.SelectTask$3.run(SelectTask.java:387) ~[node.etl-4.2.15-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2021-04-01 11:40:00.490 [pipelineId = 71,taskName = SelectTask] WARN  c.a.o.shared.arbitrate.impl.setl.monitor.MainstemMonitor - mainstem check is interrupt
2021-04-01 11:40:00.494 [pipelineId = 71,taskName = ExtractTask] INFO  com.alibaba.otter.node.etl.extract.ExtractTask - [71] extractTask is interrupted!
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_111]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_111]
        at com.alibaba.otter.shared.arbitrate.impl.setl.helper.ReplyProcessQueue.take(ReplyProcessQueue.java:57) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.memory.MemoryStageController.waitForProcess(MemoryStageController.java:75) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.memory.ExtractMemoryArbitrateEvent.await(ExtractMemoryArbitrateEvent.java:47) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.ExtractDelegateArbitrateEvent.await(ExtractDelegateArbitrateEvent.java:36) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.ExtractDelegateArbitrateEvent$$FastClassByCGLIB$$b36a599b.invoke(<generated>) ~[cglib-nodep-2.2.jar:na]
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) ~[cglib-nodep-2.2.jar:na]
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.shared.arbitrate.impl.interceptor.LogInterceptor.invoke(LogInterceptor.java:53) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.ExtractDelegateArbitrateEvent$$EnhancerByCGLIB$$a0db6661.await(<generated>) ~[cglib-nodep-2.2.jar:na]
        at com.alibaba.otter.node.etl.extract.ExtractTask.run(ExtractTask.java:53) ~[node.etl-4.2.15-SNAPSHOT.jar:na]
2021-04-01 11:40:00.494 [pipelineId = 71,taskName = LoadTask] INFO  com.alibaba.otter.node.etl.load.LoadTask - [71] loadTask is interrupted!
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_111]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_111]
        at com.alibaba.otter.shared.arbitrate.impl.setl.helper.ReplyProcessQueue.take(ReplyProcessQueue.java:57) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.memory.MemoryStageController.waitForProcess(MemoryStageController.java:75) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.memory.LoadMemoryArbitrateEvent.await(LoadMemoryArbitrateEvent.java:53) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.LoadDelegateArbitrateEvent.await(LoadDelegateArbitrateEvent.java:36) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.LoadDelegateArbitrateEvent$$FastClassByCGLIB$$df5299b2.invoke(<generated>) ~[cglib-nodep-2.2.jar:na]
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) ~[cglib-nodep-2.2.jar:na]
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.shared.arbitrate.impl.interceptor.LogInterceptor.invoke(LogInterceptor.java:53) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.LoadDelegateArbitrateEvent$$EnhancerByCGLIB$$a42cbe6e.await(<generated>) ~[cglib-nodep-2.2.jar:na]
        at com.alibaba.otter.node.etl.load.LoadTask.run(LoadTask.java:55) ~[node.etl-4.2.15-SNAPSHOT.jar:na]
2021-04-01 11:40:00.494 [pipelineId = 71,taskName = TransformTask] INFO  com.alibaba.otter.node.etl.transform.TransformTask - [71] transformTask is interrupted!
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_111]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_111]
        at com.alibaba.otter.shared.arbitrate.impl.setl.helper.ReplyProcessQueue.take(ReplyProcessQueue.java:57) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.memory.MemoryStageController.waitForProcess(MemoryStageController.java:75) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.memory.TransformMemoryArbitrateEvent.await(TransformMemoryArbitrateEvent.java:47) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.TransformDelegateArbitrateEvent.await(TransformDelegateArbitrateEvent.java:36) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.TransformDelegateArbitrateEvent$$FastClassByCGLIB$$3eefb486.invoke(<generated>) ~[cglib-nodep-2.2.jar:na]
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) ~[cglib-nodep-2.2.jar:na]
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.shared.arbitrate.impl.interceptor.LogInterceptor.invoke(LogInterceptor.java:53) ~[shared.arbitrate-4.2.15-SNAPSHOT.jar:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.TransformDelegateArbitrateEvent$$EnhancerByCGLIB$$b5a67e4a.await(<generated>) ~[cglib-nodep-2.2.jar:na]
        at com.alibaba.otter.node.etl.transform.TransformTask.run(TransformTask.java:57) ~[node.etl-4.2.15-SNAPSHOT.jar:na]
2021-04-01 11:40:25.924 [pipelineId = 71,taskName = SelectTask] WARN  c.a.o.shared.arbitrate.impl.setl.monitor.MainstemMonitor - mainstem is not run any in node /otter/channel/68/71/mainstem
2021-04-01 11:40:25.985 [destination = canal_bill_to_rpt_base_new , address = /10.18.68.210:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"10.18.68.210","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.000179","position":496959996,"serverId":168964498,"timestamp":1617246549000}}

**Comment by hjs0916633** [comment]
重启channel后就恢复正常，不知道是什么问题
