### ISSUE TITLE
load.exception Data truncation: Incorrect datetime value: '0000-00-00 00:00:00' for column 'create_time' at row 1

### ISSUE THREAD

**Issue by zj452008181** [alibaba/otter#994]
pid:5 nid:2 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [insert into `url_project`.`csessioninfo`(`salesman_id` , `union_id` , `web_open_id` , `open_id` , `tt_openid` , `tt_anonymous_openid` , `uuid` , `skey` , `create_time` , `last_visit_time` , `session_key` , `user_info` , `nick_name` , `gender` , `avatar_url` , `country` , `city` , `province` , `language` , `watermark` , `created_at` , `updated_at` , `phone` , `is_phone_verified` , `remember_token` , `points` , `is_blacklist` , `blacklist_time` , `black_record` , `platform` , `city_id` , `create_blacklist_time` , `is_specialist` , `is_salesman_unlimited` , `black_reason` , `individual_resume` , `name` , `wechat_code` , `wechat_qrcode` , `sales_man_recommend_index` , `coins` , `sales_man_like_num` , `sales_man_attention_num` , `sales_man_page_views` , `sales_man_consulting_num` , `tag` , `is_sys_user` , `is_manual` , `is_auto` , `sys_status` , `phrase_id` , `wechat_avatar_url` , `account_type_id` , `v_flag` , `followings` , `followers` , `scene` , `id_card` , `id`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `salesman_id`=values(`salesman_id`) , `union_id`=values(`union_id`) , `web_open_id`=values(`web_open_id`) , `open_id`=values(`open_id`) , `tt_openid`=values(`tt_openid`) , `tt_anonymous_openid`=values(`tt_anonymous_openid`) , `uuid`=values(`uuid`) , `skey`=values(`skey`) , `create_time`=values(`create_time`) , `last_visit_time`=values(`last_visit_time`) , `session_key`=values(`session_key`) , `user_info`=values(`user_info`) , `nick_name`=values(`nick_name`) , `gender`=values(`gender`) , `avatar_url`=values(`avatar_url`) , `country`=values(`country`) , `city`=values(`city`) , `province`=values(`province`) , `language`=values(`language`) , `watermark`=values(`watermark`) , `created_at`=values(`created_at`) , `updated_at`=values(`updated_at`) , `phone`=values(`phone`) , `is_phone_verified`=values(`is_phone_verified`) , `remember_token`=values(`remember_token`) , `points`=values(`points`) , `is_blacklist`=values(`is_blacklist`) , `blacklist_time`=values(`blacklist_time`) , `black_record`=values(`black_record`) , `platform`=values(`platform`) , `city_id`=values(`city_id`) , `create_blacklist_time`=values(`create_blacklist_time`) , `is_specialist`=values(`is_specialist`) , `is_salesman_unlimited`=values(`is_salesman_unlimited`) , `black_reason`=values(`black_reason`) , `individual_resume`=values(`individual_resume`) , `name`=values(`name`) , `wechat_code`=values(`wechat_code`) , `wechat_qrcode`=values(`wechat_qrcode`) , `sales_man_recommend_index`=values(`sales_man_recommend_index`) , `coins`=values(`coins`) , `sales_man_like_num`=values(`sales_man_like_num`) , `sales_man_attention_num`=values(`sales_man_attention_num`) , `sales_man_page_views`=values(`sales_man_page_views`) , `sales_man_consulting_num`=values(`sales_man_consulting_num`) , `tag`=values(`tag`) , `is_sys_user`=values(`is_sys_user`) , `is_manual`=values(`is_manual`) , `is_auto`=values(`is_auto`) , `sys_status`=values(`sys_status`) , `phrase_id`=values(`phrase_id`) , `wechat_avatar_url`=values(`wechat_avatar_url`) , `account_type_id`=values(`account_type_id`) , `v_flag`=values(`v_flag`) , `followings`=values(`followings`) , `followers`=values(`followers`) , `scene`=values(`scene`) , `id_card`=values(`id_card`) , `id`=values(`id`)]; Data truncation: Incorrect datetime value: '0000-00-00 00:00:00' for column 'create_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '0000-00-00 00:00:00' for column 'create_time' at row 1
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:625)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:617)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:545)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:462)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:275)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '0000-00-00 00:00:00' for column 'create_time' at row 1
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:818)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
... 21 more

**Comment by zj452008181** [comment]
这条sql如何跳过

**Comment by zj452008181** [comment]
已解决，发现是两边数据库sql_mode不一致，调整参数后解决
